### ISSUE TITLE
Clang intrinsics support for <experimental/coroutine>

### ISSUE THREAD

**Issue by sylveon** [microsoft/STL#100]
Currently this header uses MSVC specific intrinsics. Due to the intrinsics being forward declared, Clang ends up with a linker error, because it does not recognize the forward declarations as intrinsics.

The header should detect Clang and use its equivalent intrinsics. Clang 8 seems to not use the `std::experimental` namespace anymore (from quick testing, don't quote me on that) and therefore is broken even if the header is manually patched for those intrinsics, but older versions still use `std::experimental` for the coroutine support library. Moving this header to non-experimental would be ideal for support of the latest Clang compiler.

As C++20 goes near release, and since VS now boasts built-in Clang support, I don't think it's too unreasonable to support coroutines on Clang too.

See also: https://github.com/llvm-mirror/libcxx/blob/master/include/experimental/coroutine
Clang intrinsics are `__builtin_coro_resume`, `__builtin_coro_destroy` and `__builtin_coro_done` and MSVC's are `_coro_resume`, `_coro_destroy` and `_coro_done`. Might need to have `from_promise` and `promise()` use `__builtin_coro_promise`.

**Comment by CaseyCarter** [comment]
We do not support Clang in `<experimental/coroutine>` because Clang and MSVC do not agree on the ABI of coroutine frames. (We likely never will never support Clang in the `experimental` header now that there's a standard `<coroutine>` header.)  It's not simply a question of using differently-named intrinsics, the intrinsics expect pointers to structures with different layouts. 

That said, there's an effort underway to get both compilers to agree on ABI for coroutine frames for  C++20, so I'm hopeful that we will be able to properly support Clang in non-experimental `<coroutine>`.

**Comment by CaseyCarter** [comment]
I've noted this suggestion in #40.
