### ISSUE TITLE
STL (debug mode) iterators operator+ causes exception, what's a workaround?

### ISSUE THREAD

**Issue by MarcDirven** [microsoft/STL#1077]
I have a question on the following piece of code.  In any case, this code is located in the `std::array` iterator, probably also in several other iterators.
https://github.com/microsoft/STL/blob/c10ae01b4d9508eed9d5f059a120ee7223b6ac12/stl/inc/array#L205

I'm currently creating a set of iterators.  Most of the iterators are random access.  In order to test the `operator>` and `operator>=`, I need to add a certain number so that the iterator created from `begin()` points to the element greater than or equal to `end()`.  But this is not possible because the `_Verify_offset(_Off)` function throws an exception if `begin()` (the iterator) points to an element greather than `end()`. This is easy fixable by using the iterator in a following manner:
```
if (std::begin(arr) != std::end(arr) {
    auto end = &*(std::prev(std::end(arr), 1)) + 1; // create pointer to last element
    function(*&std::begin(arr), end + 1);
}
```
But, as you can guess, this only works for contiguous iterators/containers. In order to fix this, I have created a template struct that can check whether a container has a `.data()` function, making it very likely that its corresponding iterator is random access.

My questions therefore are:
- Why does it throw? Why doesn't it throw at the `operator*`?
- Am I correct that I can check whether a container is contiguous by checking if it has a `.data()` function?
- Are there any other workarounds for this?

**Comment by miscco** [comment]
These iterators are checked. The reason is that nothing good can happen with an iterator that moves past the end of an array.

You would access data that is not part of the array leading to severe security/correctness issues.

If you are in a C++20 environement you can check whether an iterator is random access via the `random_access_iterator` concept. 

If you are not there yet you could try out [iterator_traits](https://en.cppreference.com/w/cpp/iterator/iterator_traits) and check the `iterator_category`. 

Is there a reason you need to check beyond `end()`. Before ranges there are no sentinels in the STL so the iterator type of `begin()` must be the same as the iterator type of `end()`. Therefore, I do not really see a reason why you would try to check against `past end` when `past begin` would suffice.

Also to sure that we are on the same page regarding ranges in the STL. They are always half open ranges aka `[begin, end)`. This means that the element that the `end` iterator points to is*not* part of the array.

**Comment by MarcDirven** [comment]
> If you are not there yet you could try out iterator_traits and check the iterator_category.

You mean, that if the `iterator_category` is random acces, I can safely convert it to a pointer?

> Therefore, I do not really see a reason why you would try to check against past end when past begin would suffice.

Well, the only reason I would want to check it is because when one implements a random access iterator, it is recommended or even mandatory to implement all the `operator<, >, <=, >=`s as stated [here](http://www.cplusplus.com/reference/iterator/RandomAccessIterator/). Furthermore, I'd like to tests these relational `operator`s using a test framework.

> This means that the element that the end iterator points to is not part of the array. So to access the last element of an array you need to access std::prev(std::end(arr), 1)

Ah yes my bad. I meant one position past the last element.

**Comment by AlexGuteniev** [comment]
Greater than end is Undefined. Even for vector.
You may observe this on some hypothetical platform, where your vector is allocated at the edge of addressable space, so that `end()` is largest possible address.
You may observe this even on a real platform, if you'll be adding megabytes to the `end()`.

**Comment by MarcDirven** [comment]
> 
> 
> Greater than end is Undefined. Even for vector.
> You may observe this on some hypothetical platform, where your vector is allocated at the edge of addressable space, so that `end()` is largest possible address.
> You may observe this even on a real platform, if you'll be adding megabytes to the `end()`.

Hmm then I think I misunderstood its relational operators. When are they used anyway if greater than is undefined?

**Comment by AlexGuteniev** [comment]
_Greater than operator_ is defined.

attempt of obtaining _values greater than end()_ is undefined.

**Comment by MarcDirven** [comment]
That I do know. I just need a way to test the `operator>(=)`, if there is any

**Comment by fsb4000** [comment]
>Am I correct that I can check whether a container is contiguous by checking if it has a .data() function?

You can check with overloading implementations by iterator_tags:

https://en.cppreference.com/w/cpp/iterator/iterator_tags

https://gcc.godbolt.org/z/Ez45G1

**Comment by fsb4000** [comment]
>. I'm not dereferencing it, just testing.

Even if you are not dereferencing it then test it is still UB.

Great way to check if something is UB or not, try to do it at compile time:

https://gcc.godbolt.org/z/jnc1T8

**Comment by MarcDirven** [comment]
> 
> 
> > . I'm not dereferencing it, just testing.
> 
> Even if you are not dereferencing it then test it is still UB.
> 
> Great way to check if something is UB or not, try to do it at compile time:
> 
> https://gcc.godbolt.org/z/jnc1T8

Thank you! So the point of the `operator>` isn't for checking (past) the end iterator at all then?

**Comment by fsb4000** [comment]
Yes.

**Comment by MarcDirven** [comment]
Alright. This issue can be closed then.

**Comment by CaseyCarter** [comment]
> Thank you! So the point of the `operator>` isn't for checking (past) the end iterator at all then?

That's correct: no iterator can ever be past the end iterator in a program with defined behavior.
