### ISSUE TITLE
Use of VS2015 and VS2019 binary compatibility

### ISSUE THREAD

**Issue by AlexGuteniev** [microsoft/STL#1079]
I guess I'm interested to try this. I never realized this was an option.

But I want to clarify, if the following is no problem:
* Some libraries, that distribute pre-built binaries, like boost or Qt, have distinct binaries for V2015 and VS2019
* Whereas the solution uses `/MD` (`/MDd` in debug), most of the libraries are linked statically (some with compiled `.lib` files in repo, few with `.dll` files)
* Whereas the solution generally avoids `/LTCG` (to avoid some codegen bugs as well as speed up linking), some libraries may  use it (accidentally, or for 3rd party libs)

**Comment by StephanTLavavej** [comment]
Mixing all the way from VS 2015 RTM to VS 2019 16.latest should work, obeying the restrictions documented on MSDN: the final link must be performed by the newest toolset involved (or newer), the redist must be from the newest toolset involved (or newer), and absolutely no LTCG.

> Some libraries, that distribute pre-built binaries, like boost or Qt, have distinct binaries for V2015 and VS2019

While version mixing *works*, it's still best to reduce the version variation as much as possible (to get all of the latest correctness and performance fixes). So if newer builds of your third-party dependencies are available, you should use them.

> Whereas the solution uses /MD (/MDd in debug), most of the libraries are linked statically (some with compiled .lib files in repo, few with .dll files)

As long as all object files and static libs linked into a single binary (user EXE/DLL) agree on their setting of /MD versus /MT, that's fine. In particular, it's totally fine to have *static user libraries* (libboost_meow.lib) compiled with /MD (using the CRT/STL dynamically). They're just slightly fancier versions of object files as far as the linker is concerned.

Mismatching /MD versus /MT within a single user binary is a dire ODR violation and we forbid it, enforced by `#pragma detect_mismatch` as much as possible.

Having user binaries loaded into a single process that *disagree* on their /MD versus /MT settings isn't necessarily a bug, but it's risky and generally undesirable. It will result in multiple CRT/STLs being loaded (some mix of static and dynamic) and the different "domains" can't communicate CRT/STL objects (like `FILE *`). If their interfaces are purely binary-stable (C/COM/etc) then this can work.

> Whereas the solution generally avoids /LTCG (to avoid some codegen bugs as well as speed up linking), some libraries may use it (accidentally, or for 3rd party libs)

This is forbidden as documented by Microsoft Docs. LTCG emits an unstable version of the compiler's intermediate representation that may not be mixable between even minor updates of a single major version (e.g. 16.4 and 16.5). LTCG is for when you control all of the LTCG objects. (It is fine to mix in non-LTCG objects; indeed that happens if you link against the STL).
