### ISSUE TITLE
Issues with libcxx tests for the C++20 synchronization library

### ISSUE THREAD

**Issue by AlexGuteniev** [microsoft/STL#1087]
In my latch/semaphore/barrier branch, I have already somewhat working latch and semaphore, so libcxx tests pass, as well as mine. Though some libcxx tests still fail, but apparently for a bogus reason:
```
# *** LIKELY BOGUS TESTS ***
# "error: _LIBCPP_VERSION not defined"
std/thread/thread.latch/version.pass.cpp FAIL
std/thread/thread.semaphore/version.pass.cpp FAIL

# "error C3861: 'assert': identifier not found"
std/thread/thread.semaphore/timed.pass.cpp FAIL
std/thread/thread.semaphore/try_acquire.pass.cpp FAIL
```

Version tests test only `_LIBCPP_VERSION` instead of testing whatever they should test.
Other two semaphore tests appear to be valid and useful test, but they lack `#include <cassert>`

Does it make sense to attempt a PR there? Any advice on this?

**Comment by StephanTLavavej** [comment]
I definitely recommend submitting upstream changes to fix libcxx tests! They're currently talking about migrating from Phabricator to GitHub pull requests, but since that hasn't happened yet, you'll need to follow their current process. (At least it can be done entirely within git now; previously svn was a headache.) 

https://libcxx.llvm.org/ says:
> If you want to contribute a patch to libc++, the best place for that is [Phabricator](https://llvm.org/docs/Phabricator.html). Please add libcxx-commits as a subscriber.

Let us know if you have any questions about the process. (I've never used their Arcanist tool that they suggest; git diffs with maximum context have worked for me.)

**Comment by CaseyCarter** [comment]
The versions tests are legitimate - every header has a similar test case - but they should be in the `llvm-project/libcxx/test/libcxx` tree instead of under `llvm-project/libcxx/test/std`. (Aside: how confusing is it that libcxx has `test/libcxx` and `test/std` whereas we have `tests/libcxx` and `tests/std`, but with different meanings?) I agree that it looks like the others are inadvertently depending on transitive inclusion of `assert.h` or `cassert`.

**Comment by AlexGuteniev** [comment]
I don't understand how to fix `version.pass.cpp` then

**Comment by AlexGuteniev** [comment]
I've searched their code, and noticed that they prefer `<cassert>` (over 4000 occurrences int `test/std`) over `<assert.h>` (two occurrences in `test/std`)

I'm afraid it is too complex process, even though it is two line change. Can we just wait for GitHub PRs transition to happen?

**Comment by AlexGuteniev** [comment]
I guess I'll focus on `<barrier>` first to see the situation there, to make it all at once.

**Comment by AlexGuteniev** [comment]
Update, barrier only adds another `version.pass.cpp` with the same reason, all other barrier tests pass too

**Comment by AlexGuteniev** [comment]
Actually, few more tests will fail. Barrier tests  pass callback without `noexcept`. If we enforce the callback to be `noexcept` (which is required by Standard), these test would fail too.

**Comment by fsb4000** [comment]
I think the issue could be closed.
It was fixed in https://github.com/microsoft/STL/commit/355f8f560ecbde3a8832a5893ce7b4da7840549d#diff-c50aa2a14e33d2bb981f482119b46d7f69a3c46afb1963d4541368cf066a327aL485-L493
Now, there are no libc++ tests skipped related to C++20 synchronization library.
Only: https://github.com/microsoft/STL/blob/7f04137880e1c3df5125c1baf808f16f399dee2e/tests/libcxx/skipped_tests.txt#L1171
But it works in reality and it related to internal test suite:
https://github.com/microsoft/STL/blob/7f04137880e1c3df5125c1baf808f16f399dee2e/tests/libcxx/skipped_tests.txt#L946-L947
![изображение](https://user-images.githubusercontent.com/4289847/175568050-15139ba8-ca7e-4c96-9d6d-68fbfa6ea093.png)
