### ISSUE TITLE
CMakeLists.txt: Please build only a single final shared and/or static target 

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/STL#116]
Simply put. Doing this:
https://github.com/microsoft/STL/blob/7f65140761947af4ed7f9dfc11adee8c86c9e4c2/stl/CMakeLists.txt#L472-L473
and this:
https://github.com/microsoft/STL/blob/7f65140761947af4ed7f9dfc11adee8c86c9e4c2/stl/CMakeLists.txt#L486-L490

or more precisely generating a lot of targets which only differ in suffixes will always require a lot of extra patching to get it correctly into a package manager like vcpkg. It also makes it quite difficult to generally consume those targets in CMake.

Please have a look how I solved the configuration problem in https://github.com/microsoft/vcpkg/pull/8217.

In this PR downstream CMake targets can simply link against the target `microsoft::libcpmt` or `microsoft::msvcp_implib` without the madness of extra suffixes depending on the build configuration and/or iterator debug level.

**Comment by BillyONeal** [comment]
This is a consequence of our test baseline -- we need the result to produce something where all of `/MT`, `/MTd`, `/MD`, and `/MDd` are functional as part of one build step; to only build one flavor at a time as is usually done in CMake scripts produces a not functional compiler. I investigated trying to do multiple cmake configure passes and attaching them together with subninja, but that didn't end up being mature enough to use (ninja spews a ton of errors due to duplicate targets cmake emits).

Going into vcpkg is going to be a problem due to the circular dependency between Boost and us; we talked to them about this and the explicitly said we would need to vendor it before we would be able to integrate smoothly. (As in, when vcpkg builds boost, it's going to build it with the STL that comes with your Visual Studio, not the STL built here, leaving you with an inconsistent configuration).

That's not to say that we are completely averse to getting somewhere that behaves as a better CMake citizen - I spent a fair amount of time trying to come up with something that behaved reasonably - but we value producing a set of libraries that result in a functional compiler over following usual CMake conventions at this time.

**Comment by Neumann-A** [comment]
> This is a consequence of our test baseline -- we need the result to produce something where all of /MT, /MTd, /MD, and /MDd are functional as part of one build step;

If that is the case you probably want to introduce a variable `STL_INTERNAL_BUILD` which then defines the targets/builds you need for your internal build setup (until you figure out how to do it the usual CMake way). For other projects consuming the project via CMake those are not required and should follow the usual CMake conventions. 

> Going into vcpkg is going to be a problem due to the circular dependency between Boost and us;

ah you are only using boost::headers so it is not really a circular dependency more a two step process ;). So the trick here is to have two vcpkg folders. One where this projects is build and one which directly uses the output of the other vcpkg folder. Probably requires a `VCPKG_ENV_OVERRIDES_FILE` for a correct setup of the environment in the second folder but that seems doable. It is basically the same process which is explained in your README (1. How to build / 2. How to consume.).

**Comment by BillyONeal** [comment]
>until you figure out how to do it the usual CMake way

Again, the "usual CMake way" does not and can not produce a consistent outcome here due to the circular dependency between the Boost targets and ours, so there's nothing we could do instead.

>So the trick here is to have two vcpkg folders.

If you need to go "outside the CMake system" by having a staged build then the mechanism we use does not matter.

**Comment by StephanTLavavej** [comment]
We've lived with the current scheme for 5 years, and I don't see any advantage to changing it now. Notably, microsoft/STL is essentially used for development only - it is not generally consumed directly as a dependency by anyone (which we initially thought might be a possibility).
