### ISSUE TITLE
Consider replacing _STD forward<T> with static_cast<T&&>

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#1208]
Replacing `_STD forward<T>` with `static_cast<T&&>` STL-wide would:

* Improve performance in non-optimized debug mode (by avoiding real function calls)
* Improve compiler throughput by some, possibly extremely small, amount. (Probably more significant for non-optimized debug mode.)
* Reduce readability, by making it harder to tell when we intend to forward, and harder to notice `static_cast`s doing other work.

The current convention is to use `forward` except when we are in such a central header that it isn't available, or in certain rare situations where we seem to be exceptionally concerned about the perf/throughput effects.

Originally filed as Microsoft-internal VSO-541778 / [AB#541778](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/541778) .

**Comment by StephanTLavavej** [comment]
I personally believe that we **shouldn't** do this. Instead, the compiler should implement Microsoft-internal VSO-437566 "<utility> C1XX should understand `move` and `forward`, and not emit functions into the obj/PDB". (Clang should do the same, if it doesn't already.) I am deeply concerned about the readability impact, and teaching the compiler to understand `move` and `forward` would help all modern C++ projects, not just the STL.

**Comment by MikeGitb** [comment]
> " C1XX should understand move and forward, and not emit functions into the obj/PDB"

I know this is not the compiler feedback channel, but YES PLEASE!

Personally I never understood, why such fundamental constructs have to be provided by the library and not by the compiler in the first place, but thats a different can of worms.

**Comment by AlexGuteniev** [comment]
Can't you just have `_STD_MOVE` macro that hides `static_cast`? It is not "bad, control flow macro", although not "good, conditional feature macro" either

**Comment by AlexGuteniev** [comment]
Honestly I'm surprised that `/O0` builds have that much of performance considerations.

Wanna debug with overall release performance? Use `#pragma optimize("", off) in the place being debugged.

**Comment by StephanTLavavej** [comment]
I would be somewhat nervous about adding a `_STD_FORWARD` macro using `decltype` although I can't immediately imagine a scenario where it would cause harm.

**Comment by AlexGuteniev** [comment]
It is `_STD_MOVE` needs `decltype`, `_STD_FORWARD` takes `T&&` as the first parameter.

**Comment by NN---** [comment]
Reminds this article https://foonathan.net/2020/09/move-forward/

**Comment by MikeGitb** [comment]
@StephanTLavavej : Just wondering: Have you actually talked about this with the comiler devs?

**Comment by AlexGuteniev** [comment]
> * Improve performance in non-optimized debug mode (by avoiding real function calls)

Improve debugging experience by skipping this step! to me it is more important than debugging performance.

**Comment by AlexGuteniev** [comment]
WG21-p1221 appears to address this by giving better macros than current macros

**Comment by fsb4000** [comment]
> Microsoft-internal [VSO-437566](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/437566) " C1XX should understand move and forward, and not emit functions into the obj/PDB"

DevCom has the same feature request: DevCom-1681875

**Comment by MikeGitb** [comment]
the suggested `__forceinline` seems like a good intermediate solution. Is that already applied?

**Comment by fsb4000** [comment]
>Is that already applied?

No.

https://github.com/microsoft/STL/blob/4bb41db3d8e7605fc03656659752f3fad4133bc0/stl/inc/type_traits#L1345-L1354

But it helps only with `clang-cl`. 

![изображение](https://user-images.githubusercontent.com/4289847/157536958-d96ac88b-b505-43ef-92a7-604acca38380.png)


C1XX still emits function call.

![изображение](https://user-images.githubusercontent.com/4289847/157537084-e7a25a5f-5beb-4746-8dfb-163efd5a0c97.png)

**Comment by MikeGitb** [comment]
> But it helps only with clang-cl.

Ah, I keep forgetting that (I'm not using force_inline in my own code). Regardless of whether the msvc devs will implement special tratment of std::move/std::forward in the near future:  Providing a mode (a separate level for /Ob or just make it the default in bebug mode) in which __forceinline functions gets actually inlined would be a nice improvement.

**Comment by fsb4000** [comment]
> __forceinline functions gets actually inlined would be a nice improvement.

Yeah, maybe STL devs could slightly increase the priority of that.

From MS STL discord channel:
![изображение](https://user-images.githubusercontent.com/4289847/157675074-d663003a-eabb-4880-8ff1-05ec19fed3ba.png)

**Comment by eteran** [comment]
> Honestly I'm surprised that `/O0` builds have that much of performance considerations.
> 
> Wanna debug with overall release performance? Use `#pragma optimize("", off)` in the place being debugged. (And this is sort of last resort option for me; normally I just debug release)

@AlexGuteniev since this issue has suddenly had new life, I can help address this question:

Basically the issue is that often issues present themselves several minutes into an application run and you start off not knowing exactly where the bug is, so wrapping a block with a pragma is not ideal. So what happens is that we end up running a debug build which will turn those few minutes into MANY minutes, adding a lot of frustration to the debugging process.

So we end up in a situation where we want debug builds to be "reasonably fast" (for some definition of reasonable) and what many developers are finding is that the performance difference between using modern tools from the standard library and doing things "the old way" may be small in release builds, but is monumental in debug builds.

So they have a choice:

1. debug release builds, which makes it hard to see what's happening if you don't have a great starting point for where to look.
2. debug in debug mode, with modern coding style but have to tolerate application runs which are several orders of magnitude slower.
3. debug in debug mode, using old constructs, ignoring basically all of the standard library, and have reasonable debug performance

As you can imagine, many people choose option 3. If we can make unoptimized builds reasonably fast while using modern techniques, that would be a tremendous win for both productivity and the C++ community as a whole.

**Comment by MikeGitb** [comment]
> So they have a choice:

> 1.  debug release builds, which makes it hard to see what's happening if you don't have a great starting point for where to look.
> 2.  debug in debug mode, with modern coding style but have to tolerate application runs which are several orders of magnitude slower.
> 3. debug in debug mode, using old constructs, ignoring basically all of the standard library, and have reasonable debug performance

There isn't really just Debug und Release mode though: Afaik, msvc unfortunately doesn't really have a -Og equivalent, but have you checked if e.g. /Ob1 works for you?

**Comment by eteran** [comment]
@MikeGitb In full disclosure, I don't personally have this issue often, I am attempting to advocate for the more frustrated developers who seem to believe that their concerns are not being heard because I think that they are raising valid issues with the C++ development experience, especially when compared to languages which lean on "do it in the library" much less than C++ does (I think leaning on the library is a great part of the C++ ideology, but it can have its downsides).

So I can't speak specifically to what optimization levels work best for this...

However, I can say that things like `std::move` and `std::forward` are basically just a cast wrapped in a function. In a call stack, they are literally just noise to the developer. So if there is a way to have the compiler basically always elide them into just the cast and not even emit a function call, regardless of optimization level, that seems like a win for the developers in both debuggability, and performance when optimizations are disabled... AND a win for the optimizer/compile times since I'd expect that to just mean less work for the inliner to have to do.

All of that being said, personally, I'd also advocate for all trivial accessors (`operator[]`, `operator*`, `operator->`, `size`, etc...) in the standard library to be "always inline" because while the abstractions that standard containers offer are nice, they are only really usable from a performance perspective when inlined. But that's a separate discussion :-)

**Comment by MikeGitb** [comment]
> @MikeGitb In full disclosure, I don't personally have this issue often, I am attempting to advocate for the more frustrated developers

Ah sorry. Should have read your post more carefully. Just wanted to see if I could help out.

W.r.t. the rest of your post: I fully agree.  See my very first post in this thread.

**Comment by eteran** [comment]
@MikeGitb yeah, I gotcha. BTW, if I were to guess why the committee chose to implement forward and move in the library, I'd think it was so they didn't have to worry about creatively naming new keywords such that it is meaningful and also avoids collisions with existing code.

The library has no such worries.

Just a guess though 🤷‍♂️

**Comment by MikeGitb** [comment]
Well, that is a good argument to put such features into a restricted namespace (std:: being one, _Ugly being another). However, that doesn't mean it has to be provided by the library. E.g. I personally find it ridiculous that I have to include a standard library header to get access to such a fundamental language tool (same could be said for stuff like  is_constant_evaluated, launder std::byte, std::intXX_t and many of the type traits).

**Comment by fsb4000** [comment]
I have created DevCom-1690360

Let's see what will be implemented first: DevCom-1690360 or [VSO-437566](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/437566)

**Comment by CaseyCarter** [comment]
> Let's see what will be implemented first: [DevCom-1690360](https://developercommunity.visualstudio.com/t/1690360) or [VSO-437566](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/437566)

If you have an oracle for the Halting Problem, you could probably find a better use for it than this =)

**Comment by vittorioromeo** [comment]
Related: https://developercommunity.visualstudio.com/t/std::move-and-similar-functions-resu/1681875

**Comment by frederick-vs-ja** [comment]
I think special optimization of the compiler seems preferable, and all of these function templates should be consistently treated by the compiler (also mentioned in the comment of DevCom-1681875):
- `std::move`
- `std::forward`
- `std::move_if_noexcept`
- `std::as_const`
- `std::identity::operator()`
- `std::forward_like`

It would be inconvenient and error-prone if the library implementation decides to replace some of them with desugared casts.

**Comment by StephanTLavavej** [comment]
We talked about this at the weekly maintainer meeting and have decided to continue requesting compiler enhancements here. (We pinged internal VSO-1492685 which is the SuggestionTicket for DevCom-1681875.)
