### ISSUE TITLE
<fstream>: Does ifstream work in UWP?

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#1210]
Four years ago, a user reported a bug to us and it got buried in our database. :scream_cat: The repro was simple:

```cpp
#include <fstream>

int main() {
    std::ifstream infile;
    infile.open("C:/Users/Documents/123.txt"); // a file that exists
    bool result = infile.is_open();
}
```

The user reported that this returns `true` for ordinary console programs, but `false` for Universal Windows Platform apps.

We should verify whether this still repros. It's also possible that this was related to the absolute path being opened (perhaps UWP sandboxed apps only have access to relative paths in their directory? I know very little about UWP).

Originally tracked by Microsoft-internal VSO-260092 / [AB#260092](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/260092).

**Comment by fsb4000** [comment]
There are two UWP C++ variants of application.

C++/CX and C++/WinRT.

I tested both variants.
The code returns false for both: https://imgur.com/a/1AiKb6o

Yes, UWP  have access to relative paths in their directory.
Also you can ask user choose file for you: https://docs.microsoft.com/en-us/windows/uwp/files/quickstart-using-file-and-folder-pickers
And you can ask for special permissions: https://daniel-krzyczkowski.github.io/UWP-External-file-system-access-and-environment-variables/
But even so, you should use special functions, not standard С++ (or .Net) functions for working with files.

**Comment by fsb4000** [comment]
Actually, UWP can be not sandboxed application: https://github.com/microsoft/cppwinrt/issues/247#issuecomment-338237421

And for normal application ifstream works in UWP
```
C:\Dev\STL\playground>type main.cpp
#pragma comment(lib, "windowsapp")
#include <winrt/Windows.Foundation.Collections.h>
#include "winrt/Windows.UI.Core.h"

#include <iostream>
#include <fstream>

using namespace winrt;
using namespace Windows::Foundation;

int main()
{
    init_apartment();

    {
        // Just to ensure that we are building UWP program
        Uri uri(L"http://aka.ms/cppwinrt");
        printf("Hello, %ls!\n", uri.AbsoluteUri().c_str());
    }

    std::ifstream infile;
    infile.open("C:/temp/main.cpp"); // a file that exists
    bool result = infile.is_open();
    std::cout << "result = " << result << '\n';

}
C:\Dev\STL\playground>cl main.cpp /EHsc /std:c++latest /await
Оптимизирующий компилятор Microsoft (R) C/C++ версии 19.28.29115 для x86
(C) Корпорация Майкрософт (Microsoft Corporation).  Все права защищены.

/std:c++latest предоставляется как предварительная версия языковых функций из последнего
рабочего черновика C++. Мы приветствуем сообщения об ошибках и предложения к улучшению.
Однако обратите внимание, что эти функции предоставляются как есть, без поддержки и могут
измениться или быть удалены по мере развития рабочего черновика. Дополнительные сведения:
https://go.microsoft.com/fwlink/?linkid=2045807.

main.cpp
Microsoft (R) Incremental Linker Version 14.28.29115.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:main.exe
main.obj

C:\Dev\STL\playground>main.exe
Hello, http://aka.ms/cppwinrt!
result = 1
```

**Comment by MikeGitb** [comment]
I don't think that would qualify as an UWP app - its just an app using some winrt interfaces (which have previously been exclusive to UWP apps), but I'm no expert in this domain.

Regardless, if the original repro app didn't have permission to access the Documents folder, (which AFAIK would have required a manifest) not being able to open a file there (wihtout using the windows file picker) would have been indeed the expected behavior.

However, if the uwp app has the proper permissions, file access through std::filesystem should be possible - are there any test checking that?

**Comment by fsb4000** [comment]
Yes, I think you're right about my console example with C++/WinRT . It is not UWP.

I also want to add a relevant link: https://docs.microsoft.com/en-us/windows/uwp/files/file-access-permissions#accessing-additional-locations

**Comment by StephanTLavavej** [comment]
I think the question for the STL is whether there's a repro where `fopen()` from `<stdio.h>` can open a file, but `ifstream` can't. If they're equally affected, then it's not an STL bug.

**Comment by fsb4000** [comment]
No, fopen also can't open files.
https://imgur.com/a/G2vSYst

**Comment by fsb4000** [comment]
I also found that you can use Win32 API with UWP:

1) Create or Open file with UWP  Windows::Storage API
2) query a HANDLE from a StorageFile 
3) use  any Win32 API that takes a file HANDLE.

https://social.msdn.microsoft.com/Forums/office/en-US/a69503ba-e0f6-4060-a43e-d273785a18a0/uwpcbroadfilesystemaccess-and-win32-api-for-uwp?forum=wpdevelop

**Comment by StephanTLavavej** [comment]
Thanks for verifying! I will resolve this as "not an STL bug" then.

**Comment by sylveon** [comment]
As a sidenote - you don't need the `Windows::Storage` API, you can use [CreateFileFromApp](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/legacy/mt846585(v=vs.85))

**Comment by walbourn** [comment]
@StephanTLavavej 

The issue here is that the C/C++ Runtime is using ``CreateFile2`` for the I/O. This API was required for Windows 8 Store apps support, and this API can only open 'local rights' files.

If the C/C++ Runtime were to instead use ``CreateFileFromApp`` or ``CreateFile2FromApp``, then the C/C++ I/O routines could support both 'local rights' files and 'brokered' files because the OS API returns appropriate handles after doing rights validations. The primary issue here is that ``CreateFileFromApp`` / ``CreateFile2FromApp`` is only supported as of Windows 10, Version 1803.
