### ISSUE TITLE
<xmemory>: some std::allocator member functions still need to be removed in C++20

### ISSUE THREAD

**Issue by mnatsuhara** [microsoft/STL#1445]
`std::allocator` member functions `address`, `max_size`, `construct`, and `destroy`, should be removed in C++20 mode according to WG21-P0619.  Most of the removals in this paper were completed by GH-380, but these seem to have been missed.

**Comment by StephanTLavavej** [comment]
Removing the `cxx20` label which tracks top-level features and controls the [Status Chart](https://microsoft.github.io/STL/) (when it appears on issues, unlike PRs).

This will probably have some amount of source-breaking impact, but that should be mitigated by:

* These were deprecated in C++17 and we've been emitting warnings
* The STL itself should always be going through `allocator_traits` (and indeed we had to internally suppress deprecation warnings, because `allocator_traits` will use these member functions when present), so it should auto-adapt to the member functions vanishing
* A fine-grained escape hatch connected to our coarse-grained escape hatch will allow projects to opt-out of the removal, if they were previously suppressing or ignoring the deprecation warning

The escape hatch system is:

https://github.com/microsoft/STL/blob/9959929c77b18e25b6dfbc8886e311b913321925/stl/inc/yvals_core.h#L1012-L1047
