### ISSUE TITLE
<algorithm>: search_n returns first when count<=0

### ISSUE THREAD

**Issue by capatober** [microsoft/STL#148]
Hi,
It was found that `search_n` returns `first` when `count<=0`.
However, the C++ standard says ([N4659 draft](http://www.open-std.org/JTC1/SC22/WG21/docs/papers/2017/n4659.pdf), the last draft before C++17):

> Returns: The first iterator i in the range [first, last-count) such that for every non-negative integer n less than count the following corresponding conditions hold: *(i + n) == value, pred(*(i+ n),value) != false. Returns last if no such iterator is found. 

It seems that if `n>=0` and `count <=0` we don't have a chance to apply a predicate. So, we won't find "such iterator". According to this logic `last` should be returned. Am I right?
I'm just curious why does `search_n` implementation return `first`?

**Comment by MikeGitb** [comment]
Maybe a stupid question,  but aren't first and last the same if n == 0?

**Comment by StephanTLavavej** [comment]
Returning `first` is correct because "for every non-negative integer `n` less than `count`" is [vacuously true](https://en.wikipedia.org/wiki/Vacuous_truth) when `count <= 0`.

The Standardese here could be clarified along the lines of 
N4830 25.6.7 [alg.generate]/1 "Let *N* be max(0, `n`)". I'm tagging this as LWG-issue-needed, but I'd actually suggest filing an editorial issue since there's no behavioral change or restriction involved here.

**Comment by capatober** [comment]
Thanks @StephanTLavavej . It's pretty interesting. I wouldn't say that "for every non-negative integer `n` less than `count`" leads to `first` returning. Anyway, it should be clarified in the standard. Let me submit an editorial issue.

**Comment by CaseyCarter** [comment]
Now that an editorial issue has been submitted for the C++ working draft, this is in WG21's hands. There's nothing actionable remaining here.
