### ISSUE TITLE
<xhash>: dllexport emits error C2338: This function only works with multi containers

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#1638]
```
C:\Temp>type meow.cpp
```
```cpp
#include <unordered_set>
using namespace std;

struct __declspec(dllexport) SymTbl : unordered_set<int> {};
```
```
C:\Temp>cl /EHsc /nologo /W4 /MD /std:c++17 /c /wd4251 meow.cpp
meow.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29828\include\xhash(1996): error C2338: This function only works with multi containers
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29828\include\xhash(1995): note: while compiling class template member function 'bool std::_Hash<std::_Uset_traits<_Kty,std::_Uhash_compare<_Kty,_Hasher,_Keyeq>,_Alloc,false>>::_Multi_equal(const std::_Hash<std::_Uset_traits<_Kty,std::_Uhash_compare<_Kty,_Hasher,_Keyeq>,_Alloc,false>> &) const'
        with
        [
            _Kty=int,
            _Hasher=std::hash<int>,
            _Keyeq=std::equal_to<int>,
            _Alloc=std::allocator<int>
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29828\include\unordered_set(65): note: see reference to class template instantiation 'std::_Hash<std::_Uset_traits<_Kty,std::_Uhash_compare<_Kty,_Hasher,_Keyeq>,_Alloc,false>>' being compiled
        with
        [
            _Kty=int,
            _Hasher=std::hash<int>,
            _Keyeq=std::equal_to<int>,
            _Alloc=std::allocator<int>
        ]
meow.cpp(4): note: see reference to class template instantiation 'std::unordered_set<int,std::hash<int>,std::equal_to<int>,std::allocator<int>>' being compiled
```

This is because we have:
https://github.com/microsoft/STL/blob/47cd70315d560e4fe1ac699c0eb8ec8bfc5cb658/stl/inc/xhash#L1844-L1845
called by only:
https://github.com/microsoft/STL/blob/47cd70315d560e4fe1ac699c0eb8ec8bfc5cb658/stl/inc/xhash#L1949-L1950

The Standard says that `_Multi_equal()` will be instantiated "on demand" only when it's called, but dllexport tries to instantiate all non-template member functions.

Exporting classes that derive from STL containers isn't exactly recommended, but we should avoid this code pattern that causes compiler errors.

Reported as DevCom-1319981 and Microsoft-internal VSO-1270072 / AB#1270072 .

**Comment by CaseyCarter** [comment]
> Exporting classes that derive from STL containers isn't exactly recommended, but we should avoid this code pattern that causes compiler errors.

I'm confused. I thought we didn't support folks DLL-exporting STL templates, but this is at least the second time we've implemented a change to allow them to do so that I recall. If we're going to support this use case, we should have test coverage. If we aren't supporting it, then why are investing effort to make it work?

Also, FYI I changed "non-templated functions" to "non-template functions" in your description. Per the definition of a "templated entity" in the working draft, a non-template member functions of class templates - the entities that are being instantiated when DLL-exported that we need to not be instantiated - _are_ templated functions.
