### ISSUE TITLE
Interest in build symbol size potential improvements?

### ISSUE THREAD

**Issue by nick42** [microsoft/STL#164]
I am wondering if there is any interest in incorporating any of the build symbol size improvement suggested by Jorg Brown (et al, presumably), as described in his recent CppCon talk (https://www.youtube.com/watch?v=TyiiNVA1syk).

I have prototyped the equivalent for a couple of the changes described in the Microsoft STL, and they appear to compile/work, but I don't have the capability to check if they actually offer substantial build or debug time improvements in large code bases under MSVC. More than happy to submit them as pull requests if desired; I'll inline below for reference. See the above referenced talk (and/or the talk on "no zero cost abstractions") for details of "why".

```
// std::conditional potential replacement...

template <bool _Test>
struct conditional {
    template <class _Ty1, class _Ty2> using type = _Ty1;
};
template <>
struct conditional<false> {
    template <class _Ty1, class _Ty2> using type = _Ty2;
};

template <bool _Test, class _Ty1, class _Ty2>
using conditional_t = typename conditional<_Test>::type<_Ty1, _Ty2>;

// std::is_same potential replacement...

namespace detail {
	struct is_same_helper_base {
		static constexpr bool IsSame(void*) { return false; }
	};
	template<class _Ty>
	struct is_same_helper : is_same_helper_base {
		static constexpr bool IsSame(is_same_helper<_Ty>*) { return true; }
		using is_same_helper_base::IsSame;
	};
}

template<class _Ty1, class _Ty2>
struct is_same : integral_constant<bool, detail::is_same_helper<_Ty1>::IsSame((detail::is_same_helper<_Ty2>*)(nullptr))> {};
template<class _Ty1, class _Ty2>
_INLINE_VAR constexpr bool is_same_v = is_same<_Ty1, _Ty2>::value;

// ...
```

Please note I'm not a compiler expert, and I'm not advocating this change per se, I'm just asking about interest in incorporating this type of change. If there's a good reason not to do this for Microsoft STL, please just enlighten me. Thanks. :)

**Comment by nick42** [comment]
Note also: I'm not sure my is_same is actually better, but the using declaration version didn't compile. That is, the equivalent to the talk version is:

template<class _Ty1, class _Ty2>
using is_same = integral_constant<bool, detail::is_same_helper<_Ty1>::IsSame((detail::is_same_helper<_Ty2>*)(nullptr))>;

... but this breaks something elsewhere, and I'm not smart enough to figure out why. =/

**Comment by nick42** [comment]
Just a quick follow-up note, for reference, since I am trying to figure out why the using version of the is_same replacement isn't working...

This code compiles just fine (with the using version), and is (as far as I can discern) a direct replicate of the inner template expansion code which is failing to compile from the template instantiation in <memory>:

#include <xfacet>

static constexpr bool bIsSame_test = std::is_same_v<std::_Facet_base, std::default_delete<std::_Facet_base>>;

So... not sure what's going on with the compiler, and if the using version (ie: the actually potentially improved version) _should_ be working.

**Comment by nick42** [comment]
Also note: The replacements require additional code changes to work with the entire library, primarily to deal with other workarounds in the library. For example:

2>D:\Dev\ThirdParty\vcpkg\installed\x64-windows\include\fmt\core.h(660,69): error C2977:  'std::conditional': too many template arguments
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.22.27905\include\xtr1common(74): message :  see declaration of 'std::conditional'

Just thought I'd note that as well, for reference.

**Comment by StephanTLavavej** [comment]
According to my understanding, our current techniques substantially achieve this goal. We already use alias templates and variable templates aggressively (maybe not 100%, but close to it). Additionally, the MSVC compiler front-end C1XX has been taught to recognize common type traits and take immediate shortcuts (this is permissible because Standard type traits can't be user-specialized except in rare cases with explicit permission). While we consider Clang/LLVM to be a first-class citizen, we're inclined to think that if type trait throughput is a bottleneck, Clang should consider implementing similar shortcut optimizations, instead of putting more cleverness in the library.

Combined with the fact that the Standard prohibits design changes like what you originally depicted for `std::conditional`, it is unclear to me whether any significant work can usefully be done here.

I think we'd review a pull request that (1) conformed to the Standard, (2) noticeably improved object file size or compiler memory consumption for real-world usage, and (3) paid a reasonable cost in implementation complexity (i.e. proportional to the improvement). As I believe that significant gains are unlikely (although I would love to be proven wrong), I'm going to close this as "question resolved" instead of keeping it open forever.

Thanks!

**Comment by nick42** [comment]
Totally understand, and appreciate the answer to the inquiry. For reference, this is what I landed on eventually in my experimentation for conditional:

```
namespace detail {
	template <bool _Test>
	struct conditional_opt {
		template <class _Ty1, class _Ty2> using type = _Ty1;
	};
	template <>
	struct conditional_opt<false> {
		template <class _Ty1, class _Ty2> using type = _Ty2;
	};
}

template <bool _Test, class _Ty1, class _Ty2>
using conditional_t = typename detail::conditional_opt<_Test>::type<_Ty1, _Ty2>;

template <bool _Test, class _Ty1, class _Ty2>
struct conditional {
	using type = conditional_t<_Test, _Ty1, _Ty2>;
};

```
That is, I believe, compatible with the standard, and does give some compile-time size benefit in the conditional_t case (absent compiler internal optimizations). I was able to observe a small, but tangible decrease in PCH size compiling a test project with MSVC with this change, but as I said, I lack the infrastructure to validate the effect on larger and/or more varied codebases, and the compile time effect was indeterminate.

Aside: I did see that the library already have some Clang-specific code paths; something like this might perhaps be applicable for non-MSVC compilation.

Anyway, as noted, I appreciate the answer, and as Jorg mentioned in his talk, much of this type of optimization is likely to become immaterial over time, as compilers implement type traits as effective compiler intrinsics anyway. I just figured I'd ask the question. :)
