### ISSUE TITLE
Comment with Short Explanation of Date Conversions (_Civil_from_days, _Days_from_civil)

### ISSUE THREAD

**Issue by mnatsuhara** [microsoft/STL#1641]
In #1634, @statementreply has implemented clever date conversion algorithms with obvious benchmarks improvements.  These calculations have aptly-named variables, but still involve some values that are obscure to the uninformed reader.  It would be nice to include some brief comments throughout the algorithm to provide some context around the individual calculations performed.  

NOTE:
The previously-implemented algorithms appeared similarly involved, but the functions were commented with the date algorithms paper that introduced them, which contained explanations for the calculations.

**Comment by StephanTLavavej** [comment]
For example:
```cpp
const unsigned int _Year_of_century = (91867 * (_Day_of_century + 1)) >> 25; // [0, 99]
```
We eventually realized that this is implementing a division, as [2^25 / 91867](https://www.wolframalpha.com/input/?i=2%5E25+%2F+91867) is 365.25011... (I believe that this approximation behaves correctly because there are enough bits in `unsigned int`, as `static_assert`ed in the function, and any precision issues don't affect the result over the limited range of inputs that we care about.)
