### ISSUE TITLE
`<random>`: Optimize `uniform_int_distribution` with multiply-shift

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#178]
I reimplemented `uniform_int_distribution` long ago:

https://github.com/microsoft/STL/blob/53cdb9f8a85c2500077ccf0676619110340c03bf/stl/inc/xutility#L4878-L4942

This technique described by Daniel Lemire should be a significant improvement: https://lemire.me/blog/2016/06/27/a-fast-alternative-to-the-modulo-reduction/

**Comment by chris0x44** [comment]
I would like to work on this. In the hopes to not waste everyone's time with many needless iterations, I have a few questions.
- Is there an additional style guide apart from clang-format and the `_Ugly` rule?
- Since the calculation described by Daniel Lemire requires a promotion to the next larger integer type, should this fall back to normal modulo operation for types of unsigned long long?
- Is less code preferred over fast(er) code? In this case the power of 2 check `_Mask % _Index == _Udiff(_Index - 1)` could be extracted from the loop to introduce a special case, which would also reduce the work done inside the `for(;;)` loop, as it doesn't have to repeatedly check if index is a power of 2. Similar to the following
```cpp
    static constexpr bool _Is_power_of2(_Udiff _Value) {
        return _Value && !(_Value & (_Value - 1));
    }

    _Diff operator()(_Diff _Index) {
        if (_Is_power_of2(_Index)) {
            ...
            return static_cast<_Diff>(_Reduce_by_power2(_Ret, _Index));
        }
        for (;;) { ...
            if (_Ret / _Index < _Mask / _Index) {
                return static_cast<_Diff>(_Ret % _Index);
            }
        }
    }
```

On a site note, am I correct in assuming that `_Urng::max` and `_Urng::min` are not guaranteed to be constexpr? Otherwise this might offer a way to work around the special handling to avoid full shifts.

**Comment by CaseyCarter** [comment]
> * Is there an additional style guide apart from clang-format and the `_Ugly` rule?

There will eventually be, but there is none yet. For now all we can say is "try to imitate the style that's already there, and be prepared for us to communicate much of the style to you in code reviews".

> * Since the calculation described by Daniel Lemire requires a promotion to the next larger integer type, should this fall back to normal modulo operation for types of unsigned long long?

It depends on whether hardware 64-bit division is faster than a bespoke 64 x 64 = 128 bit multiply (See `_Big_multiply` in `<ratio>`).

> * Is less code preferred over fast(er) code?

In general, more and faster is preferable to less and slower but there are no absolutes. (Your example certainly looks reasonable.)

> On a side note, am I correct in assuming that `_Urng::max` and `_Urng::min` are not guaranteed to be constexpr? Otherwise this might offer a way to work around the special handling to avoid full shifts.

`G::max()` and GT::min()` must be constant expressions for `G` to model `uniform_random_bit_generator` (and consequently to satisfy the *uniform random bit generator requirements*) per [[rand.req.urng]](http://eel.is/c++draft/rand.req.urng).

**Comment by chris0x44** [comment]
Thanks for the clarification. I'll check which solution for the 64-bit case is faster and create a PR. With regard to testing, I assume that additional testcases for the changed code and where to put them can be discussed in the review and can be extended once the test-suites are also available here?

**Comment by StephanTLavavej** [comment]
> I'll check which solution for the 64-bit case is faster and create a PR.

Thanks for looking into this! Based on my experience with charconv/Ryu, I'm pretty sure that umul128 will be great on x64, and decent on x86 compared to runtime division (which was horrible until very recent architectures, where it is less horrible).

> With regard to testing, I assume that additional testcases for the changed code and where to put them can be discussed in the review and can be extended once the test-suites are also available here?

Yeah. We're hopefully about a month away from getting our test suites online.

Note that this enhancement is tagged vNext because I believe that it will break ABI - specifically, changing the observable behavior of `uniform_int_distribution` would lead to mix-and-match issues if we attempted to ship such a change in the current release series. Our vNext branch won't be ready for probably several months, but it *will* be available eventually.

(Unless the new technique happens to generate exactly the same values as the current technique, while storing the exact same data members, which seems unlikely.)

**Comment by CaseyCarter** [comment]
> Note that this enhancement is tagged vNext because I believe that it will break ABI - specifically, changing the observable behavior of `uniform_int_distribution` would lead to mix-and-match issues if we attempted to ship such a change in the current release series.

This doesn't seem more "ABI breaking" than any other behavior change: If we avoid changing the representation of `uniform_int_distribution`, then programs will continue to link and run whether they get the old version or the new version. They may not run *correctly* if they specifically depend on the old behavior or the new behavior, but that's not a problem I'd call an "ABI break".

**Comment by StephanTLavavej** [comment]
Ok, I'm convinced. (Note that adding non-static member functions is totally fine for ABI; only `virtual` member functions are a big deal.)

**Comment by CaseyCarter** [comment]
> This doesn't seem more "ABI breaking" than any other behavior change

I should clarify this for the lurkers: when we change the behavior of an *internal* function - something with an ugly name that users don't know about or call directly - we *do* consider it to be an ABI break. Users can't be expected to know that `vector::push_back` calls `vector::_Frobnicate`, or that they may need to recompile an OBJ somewhere with codegen for a `vector::_Frobnicate` specialization because we want to change what `_Frobnicate` does. In a case like that, we'll "bump" the name to `_Frobnicate2` to avoid new code / old code linking and all is well.

With "pretty" functions that users do call the burden is on them to recompile anything that touches e.g. `uniform_int_distribution::operator()` if they want to ensure the new behavior.

**Comment by chris0x44** [comment]
Leaving this here to avoid confusion about my previous suggestion. Seems like I took a wrong turn with my approach. The operation for an index of a power of 2 should just be `_Value & (_Index-1)`, which should be handled as a special case, the Lemire-optimization applies to the non-power of 2 cases.

**Comment by horenmar** [comment]
@CaseyCarter does this mean 

> This doesn't seem more "ABI breaking" than any other behavior change: If we avoid changing the representation of uniform_int_distribution, then programs will continue to link and run whether they get the old version or the new version. They may not run correctly if they specifically depend on the old behavior or the new behavior, but that's not a problem I'd call an "ABI break".

that a proposal to standardize outputs of distributions in `<random>` would not be considered breaking change by MS' STL team?

**Comment by CaseyCarter** [comment]
> does this mean that a proposal to standardize outputs of distributions in `<random>` would not be considered breaking change by MS' STL team?

There are many different kinds of breaking change. Assuming that we could standardize the outputs of distributions without storing additional state, that proposal would be a behavioral change - and therefore source-breaking - but not ABI breaking.
