### ISSUE TITLE
Determine ABI stability timeline for C++20

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#1814]
We're in a novel situation: never before have we completed a Standard so rapidly. Adding to this concern, `<format>` is both ABI-sensitive and performance-sensitive, and WG21 is expected to mandate ABI-breaking changes soon.

(C++17 was different; we finished `<charconv>` in 2019 having completed all other features much earlier, and while it was performance-sensitive, we had time to extensively test and tune it, and its function-oriented nature means that it has no ABI concerns and can be revised in the future.)

We were initially planning to declare ABI stability when finishing C++20 (along with the addition of `/std:c++20` as distinct from the always-experimental `/std:c++latest`), to align with the user expectation that non-experimental features supported for production use are also ABI stable. However, if this locks us into an implementation that can't keep up with retroactive changes to C++20, or freezes an implementation before it's had a chance for significant performance tuning, that will ultimately be harmful to users.

We should consider asking our bosses and boss-like entities for a change of plans: we will still declare C++20 to be feature-complete and ready for production use when we're done (as indicated by the feature-test macros), but we can announce that its ABI will potentially change for some defined period of time (3 months, 6 months, 1 year?) or number of releases (e.g. Dev17 17.x for some specific value of X). This will have no effect for `/std:c++14` and `/std:c++17` users, and we can expect that, at least initially, the population of `/std:c++20` users will be the most eager upgraders for whom rebuilding the world is the least onerous.

Additionally, to mitigate mix-and-match problems, we could add a `#pragma detect_mismatch` to `<format>` right now, allowing us to revise it in the future and have the linker detect any OBJ/static LIB mixing.

<hr/>

### **Update:** We arrived at a plan, see [the comment below](https://github.com/microsoft/STL/issues/1814#issuecomment-845572895).

**Comment by sylveon** [comment]
I personally think something like keeping the ABI unstable until the non-preview release of Dev17 would be a good idea.

Freezing it now will lead to major differences between standard libraries because of the new changes to the standard library require ABI breakage, meaning some libraries and consumers might be reluctant to adopting C++20 because of inconsistency between compilers/standard library implementations, and this will ultimately be detrimental to the MSVC ecosystem.

**Comment by timsong-cpp** [comment]
As @brevzin [noted](https://github.com/microsoft/STL/issues/1800#issuecomment-816270666), there are three Ranges papers in flight with ABI implications as well ([split](https://wg21.link/p2210), [default construction](https://wg21.link/p2325), and [join](https://wg21.link/p2328)).

**Comment by jovibor** [comment]
> We should consider asking our bosses and boss-like entities for a change of plans: we will still declare C++20 to be feature-complete and ready for production use when we're done (as indicated by the feature-test macros), but we can announce that its ABI will potentially change for some defined period of time

Nothing but hoping for your bosses' good sanity😎

**Comment by hatcat** [comment]
> We're in a novel situation: never before have we completed a Standard so rapidly.

I have high hopes for C++23...

**Comment by miscco** [comment]
> > We're in a novel situation: never before have we completed a Standard so rapidly.
> 
> I have high hopes for C++23...

Will be finished in 22

**Comment by Lectem** [comment]
If this can help take a decision or convince anybody:
Out of the 5 last clients I worked with, 4 said they stopped using some of STL types due to either runtime performance or compile time performance, that could be fixed by changing ABI such as is done in vNext. I'm thinking mainly about debug iterators and constexpr.
If `std::format` isn't fast enough (to compile or at runtime) compared to fmt::format, I'm afraid this will only keep fueling arguments against using the STL (and std library in general, whatever implementation it is).

While I am sympathetic to having some kind of ABI stability, I don't think "rushing" a release just to be able to put the "c++ latest compliant" stamp is a good idea if QoI improvements can't follow due to the same ABI stability. 
An upgrade path must be kept, or some rupture planned to finally take this opportunity to break ABI, just as was done in the past.

**Comment by MikeGitb** [comment]
Personally, I'm not even that concerned about performance,  exactly because there is fmt and the STL is rarely the best performing solution for a given problem anyway. 

What I do care about though is correctness and portability. Effectively locking down the ABI before having any significant user contact, real-world testing and (ideally) a second implementation to compare against seems a very risky choice for something so fundamental - especially when people are still trying to "fix" the standard itself.

**Comment by jovibor** [comment]
> Personally, I'm not even that concerned about performance, exactly because there is fmt and the STL is rarely the best performing solution for a given problem anyway.

By this logic, there is no value in using STL at all, because every piece of it has more performant counterpart somewhere anyway. The only reason would be that it's available out-of-the box.

If the performance question is not about years of researching or some rocket science, but only delaying ABI locking by month or so I would definitely consider it as the way to go.

**Comment by MikeGitb** [comment]
> By this logic, there is no value in using STL at all, because every piece of it has more performant counterpart somewhere anyway. The only reason would be that it's available out-of-the box.

That's pretty much the way it is. Yes. Except for

>there is no value in using STL at all

Just because there is something faster somewhere doesn't mean the STL doesn't have value. Using 3rd party dependencies comes with it's own costs and even in c++ code, performance is not the only relevant metric.

But that gets off topic.

**Comment by vitaut** [comment]
> Personally, I'm not even that concerned about performance, exactly because there is fmt and the STL is rarely the best performing solution for a given problem anyway.

It's more complicated in case of fmt/`std::format` compared to, say, containers because here we have the `formatter` extension point. It would be really unfortunate if we end up in the world with two sets of incompatible `formatter` specialization and resulting interoperability problems. I think it's worth taking time and addressing performance differences before ABI is frozen or at least making sure that they can be addressed in the future without ABI breakage.

**Comment by MikeGitb** [comment]
> It's more complicated in case of fmt/std::format compared to, say, containers because here we have the formatter extension point. It would be really unfortunate if we ended up in the world with two sets of incompatible formatter specializations and resulting interoperability problems. 

So far we have rarely been using a library provided `operator<<` for printing (except for printf debugging or quick prototyping), because most of the time we had our own format requirements anyway. In a similar fashoin, I'm not sure how much I'm going to use a 3rd party `fmt/std::formatter` specialization in a context, where performance matters. Also, performance aside, I expect fmt to stay ahead of std::format feature and compatibility wise for the forseable future, so we'll probably have to live with this duality for quite some time anyway.

Anyway, as I wrote previously: I'm also very much against locking down the ABI right away - just that performance isn't my primary reason for that.

**Comment by vitaut** [comment]
> far we have rarely been using a library provided operator<< for printing 

You maybe, others have been using them extensively.

> we'll probably have to live with this duality for quite some time anyway.

The important thing is the long term, not the next few year. In the long term I expect `fmt::formatter` to go away.

**Comment by MikeGitb** [comment]
> You maybe, others have been using them extensively.

Not sure what you are trying to convince me of. I never said, 3rd party overloads of `operator<<` isn't bein used by others. I said **we** didn't use it. I also didn't say whatever performance such an ABI freeze would leave on the table isn't a problem for anyone. I said **I** am not concerned about performance.

> The important thing is the long term, not the next few years. 

Long term, the current msvc ABI doesn't matter anyway (assuming plans to introduce an new ABI in the Dev17 timeframe come to fruitition). Also, I'd speculate sure that implementation divergence or unfixable bugs that slipped through will be a much bigger obstacle to the adoption of std::formatter than x% performance difference.

Anyway. I think we agree that we'd prefer ABI not to be frozen right away. Arguing which reason (potential performance difference vs potential divergence/correctness issues or even vetoing changes to the standard) is "more important" feels silly.

**Comment by barcharcraz** [comment]
I think std::format is a little less hamstrung by ABI than regex, but these sorts of things are _extremely_ difficult to analyze correctly.

**Comment by TautvydasZilys** [comment]
> This will have no effect for /std:c++14 and /std:c++17 users, and we can expect that, at least initially, the population of /std:c++20 users will be the most eager upgraders for whom rebuilding the world is the least onerous.

Does this mean that you will not be able to link `/std:c++14` code with `/std:c++20` code once it is properly? Or is this about mixing `/std:c++20` code compiled with VS 17.0-preview4 with `/std:c++20` code compiled with VS 17.6?

**Comment by sylveon** [comment]
The latter

**Comment by TheStormN** [comment]
I'm concerned about the VS 2022 blog post saying: "If you want to upgrade to Visual Studio 2022 but are worried about compatibility, binary compatibility with the C++ runtime will make it painless."

Which basically means that they are not going to break the ABI of the current runtime for C++11/14/17, which means that some old bugs and performance issues aren't going to be addressed. Not sure if different runtime will be used for the C++20 mode(where older standard features are used), but if it is, then things are getting really confusing.

@StephanTLavavej Could you shed some light on these matters?

**Comment by sylveon** [comment]
The ABI was not broken for VS 2022, as documented here: https://github.com/microsoft/STL/discussions/1725

And no, C++20 doesn't use a different runtime, so you can link code compiled for C++20 to code compiled for older standards without issue.

**Comment by TheStormN** [comment]
> The ABI was not broken for VS 2022, as documented here: [#1725 (reply in thread)](https://github.com/microsoft/STL/discussions/1725#discussioncomment-467070)
> 
> And no, C++20 doesn't use a different runtime, so you can link code compiled for C++20 to code compiled for older standards without issue.

I see, so unfortunate... Anyway, to be a bit more on the current topic, I also agree that the C++20 ABI should stay unstable a bit more time in order to properly fix issues from WG21.

**Comment by StephanTLavavej** [comment]
I've set up a meeting with our bosses and boss-like entities to reach a decision here. Thanks to everyone who's expressed interest in this issue; it is very helpful to be able to point to the number of upvotes :smile_cat:

**Comment by cor3ntin** [comment]
@StephanTLavavej Great to hear!

FYI, the next plenary is on June 7, the ranges papers should be approved then.
I also would like to point out this issue - having a few more weeks to resolve it would be greatly appreciated [LWG3547](https://cplusplus.github.io/LWG/issue3547).

As a matter of personal opinion (not reflective of anyone in WG21), it think giving WG21 until the next plenary to put out the fires and address known defect would be a lovely compromise, I understand that we cannot keep doing that forever.

At the same time, I like to think that it's in the benefit of everyone to address known issues, while we still can.
The long time costs of not doing it would otherwise be paid for many decades by all of C++ developers, or back both WG21 and implementers in an uncomfortable corner.

Mistakes were made, we were blindsided by some issues, and frankly WG21's output also suffers from self-imposed deadlines.
Maybe we should have course corrected sooner, but times are challenging.

I apologize for whatever part I had to play in that lack of reactivity.

We can only try our best. And hope there aren't to many unknown thinks that will pop up once C++20 is widely deployed.

Congrats on implementing the standard in record time in the mist of a pandemic,
and working with your organization on this issue.

Thanks!

**Comment by h-vetinari** [comment]
One other aspect that's novel and not mentioned explicitly in the OP, but came up in the reddit thread announcing STL's C++20 completeness (by, IIUC, the same author):

> > [someone](https://www.reddit.com/r/cpp/comments/mz8rkr/msvcs_stl_is_c20_feature_complete_for_vs_2019/gw10idf?utm_source=share&utm_medium=web2x&context=3): Did open sourcing the library help in any way?

> @StephanTLavavej: Yes, beyond our wildest dreams. Our amazing GitHub contributors were responsible for many large and difficult features, stressing both domain expertise and attention to detail. It took some time to migrate the STL to GitHub (an ongoing project) and it takes more time to perform detailed code reviews that communicate how to implement/maintain the STL (something that no book directly teaches; I learned it as an apprentice/minion), but ultimately it's saved a ton of time as our contributors have gone on to write way more (and better!) code than the maintainer team working in isolation ever could have in the old closed system. Without being open source, there's no way we'd have been complete now - probably it'd be calendar year 2022. [...]

It might be helpful for that meeting to point out how the community helped put the STL in a position where the option of declaring feature completeness & ABI stability is even on the table that early. It would be a wonderful way to acknowledge that contribution (on the level of the bosses and upwards) by listening when now many of the same people (not including myself...) are asking for STL's help in turn.

**Comment by StephanTLavavej** [comment]
@h-vetinari An excellent point, I'll make sure to bring it up!

**Comment by vrubleg** [comment]
![image](https://user-images.githubusercontent.com/2157439/116775097-a0bd9880-aa69-11eb-861d-004b8cd3cbcb.png)

**Comment by StephanTLavavej** [comment]
Ok, we've got a plan approved by our bosses and boss-like entities:

* VS 2019 16.10 will not have `/std:c++20`. (That compiler option, which was added in a Preview, will be removed before the production release.) Our C++20 implementation will remain available under `/std:c++latest`, with the STL's sources remaining unchanged. While the STL is still C++20 feature complete, `/std:c++latest` doesn't promise ABI stability.
* VS 2019 16.11, the last update in the VS 2019 release series, will add `/std:c++20`. We'll apply library changes so that almost all C++20 STL features will be available in `/std:c++20` mode. The exceptions are that `<format>`, `<ranges>`, and the formatting part of `<chrono>` will remain restricted to `/std:c++latest` due to WG21's upcoming changes.
* VS 2022 17.0 will receive the same `/std:c++20` changes as 16.11. Then, we'll begin applying ABI-breaking changes to the affected headers guarded by `/std:c++latest`. (Those ABI-breaking changes will *not* be backported to 16.11.)
* When WG21 is finished backporting changes to C++20, and we've implemented those changes in addition to any ABI-breaking performance improvements for `<format>`, we'll freeze the ABI and VS 2022 17.x will enable `<format>`, `<ranges>`, and the formatting part of `<chrono>` under `/std:c++20`.
  + I believe that this part of the timeline (i.e. exactly which 17.x release declares stability) is up to the STL maintainers; my tentative expectation is that WG21 and our implementation will be ready for stability by the end of calendar year 2021, whatever 17.x release that ends up flowing into.

@CaseyCarter is working on the library changes needed to make `<format>`, `<ranges>`, and the formatting part of `<chrono>` available under `/std:c++latest` only; we'll apply this to the microsoft/STL repo and VS 2022 17.0 simultaneously, then backport to the 16.11 branch internally.

Hope this makes sense! We can answer any questions you might have.

**Comment by Zingam** [comment]
Very well. How is that going to work in/with CMake?

**Comment by StephanTLavavej** [comment]
I am not very familiar with CMake, but I've seen our usage of `CMAKE_CXX_STANDARD`:

https://github.com/microsoft/STL/blob/68145cbc22f25fd9936a58d05b261c5c5767a38a/tools/CMakeLists.txt#L7

According to their documentation for [`CMAKE_CXX_STANDARD`](https://cmake.org/cmake/help/latest/variable/CMAKE_CXX_STANDARD.html) and [`CXX_STANDARD`](https://cmake.org/cmake/help/latest/prop_tgt/CXX_STANDARD.html), "Supported values are `98`, `11`, `14`, `17`, `20`, `23`."

I would expect that CMake should:
* Map `20` to `/std:c++latest` for MSVC up to and including 16.10,
* Map `20` to `/std:c++20` for MSVC 16.11, 17.0, and beyond
* Map `23` to `/std:c++latest` for all versions of MSVC (until years from now when C++23 is done).

I am not sure what the current behavior is.

**Comment by MikeGitb** [comment]
@thewavelength: stdc++20 with 16.11 and 17.x will provide the full c++20 feature set (at least that's the plan as far as I understand), so I don't get what you are concerned about.

**Comment by thewavelength** [comment]
@MikeGitb if that's the case I'm fine with it. But I understood it in a way that (probable) ABI incompatible features like format wouldn't be included in those versions in std:c++20 but only in std:latest until it is finalized by the committee.

**Comment by MikeGitb** [comment]
I think you are right - I overlooked

> - VS 2019 16.11, the last update in the VS 2019 release series, will add /std:c++20. We'll apply library changes so that almost all C++20 STL features will be available in /std:c++20 mode. **The exceptions are that <format>, <ranges>, and the formatting part of <chrono> will remain restricted to /std:c++latest due to WG21's upcoming changes.**

**Comment by bradking** [comment]
CMake's logic for mapping standards to MSVC flags is [here](https://gitlab.kitware.com/cmake/cmake/-/blob/v3.20.2/Modules/Compiler/MSVC-CXX.cmake#L21-33).  It will need an update for `/std:c++20` and C++23.  Please see our [CONTRIBUTING.rst](https://gitlab.kitware.com/cmake/cmake/-/blob/master/CONTRIBUTING.rst) file and open a merge request for that.

**Comment by bradking** [comment]
See [CMake MR 6174](https://gitlab.kitware.com/cmake/cmake/-/merge_requests/6174) for this update.

**Comment by StephanTLavavej** [comment]
@thewavelength Yeah, your point makes sense.

@bradking Please note that VS 2019 16.10 Preview 4 differs from the final production release - at the last moment, we *removed* `/std:c++20` (which is the subject of this very long thread). If I understand that CMake merge request correctly, it will attempt to use `/std:c++20` with 16.10 which will fail to compile with the production release (available right now).

Additionally, note that `/std:c++20` has not been removed from 16.11 Previews (we're going to port STL changes to modify which features it enables).

**Comment by Zingam** [comment]
@StephanTLavavej Why weren't these  'experimental/unstable' features hidden behind some temporary 'experimental' switch? If I get it correctly in the case of CMake and maybe other build systems as well: `<format>` etc. will be available in 16.10 with `cxx_std_20 `, then in 16.11 the won't but will appear under `cxx_std_23` and then sometime in 17.x again with `cxx_std_20`.
That's probably not a big issue but it will certainly confuse somebody.

**Comment by MikeGitb** [comment]
My understanding was that all features that require /std:c++latest should be considered unstable. Unfortunately (or maybe fortunately) Cmake doesn't distinguish between stable and unstable features belonging to the same standard version (not sure how useful it would be inpractice).

@StephanTLavavej , @bradking 
Assuming that it will not make a difference if /std:c++latest or /std:c++20 is used in 16.11 if I don't use the affected headers in the frist place and also assuming that there won't be c++23 features in under latest in 16.11, I think, my personal preference for cmake would be to not use /std:c++20 for the entire VS2019 series at all and just always map cxx_std_20 to /std:c++latest. That way, the behavior is more consistent and I would assume/hope (but could be wrong) that people requiring ABI stability will anyway take much more direct control over what flags are being used exactly instead of relying cmake to consistently select appropriate flags accross compiler and cmake versions.

Not sure what my preferences would be if those assumptions don't hold.

Would of course be great to get feedback from someone who actually relies on ABI stability for their product.

**Comment by StephanTLavavej** [comment]
I can confirm that we will not backport C++23 features to 16.11. We aren't planning to backport any STL changes aside from #1929 itself, and any fixes for critical bugs that we discover (they'd have to be pretty bad, beyond ordinary bugfixes). Because 16.11 is a permanent stabilization release, feature work is specifically not allowed (only with special exceptions).

**Comment by bradking** [comment]
> VS 2019 16.10 Preview 4 differs from the final production release

In CMake MR 6174, the `/std:c++20` flag will be used only for cl version `19.29.30129` or higher.  VS 16.10 has cl version `19.29.30037`, so we won't use `/std:c++20` until VS 16.11.

> Cmake doesn't distinguish between stable and unstable features belonging to the same standard version 

CMake's `cxx_std_##` meta-features only care about nominally putting the compiler in a mode aware of the corresponding language standard.  For unfinished modes, `/std:c++latest` is the best it can do.  Beyond that, it is up to project code to put appropriate preprocessor conditions around use of advanced language features.

**Comment by StephanTLavavej** [comment]
Ah, thanks! I didn't inspect the version number closely. :joy_cat:

**Comment by cor3ntin** [comment]
Here is the [list of papers approved as defects for C++20](https://github.com/cplusplus/papers/issues?q=is%3Aissue+sort%3Aupdated-desc+label%3Aplenary-approved+label%3Ac%2B%2B23+label%3Ac%2B%2B20)

**Comment by cor3ntin** [comment]
Note that the Chrono fix will not land officially before October as we were told rushing it would make no difference on your timeline

**Comment by takev** [comment]
Sadly the CI just broke for me on this.

CMake for some reason will not generate /std::c++latest anymore, not even when telling cmake to use c++23 as the language standard. Since I use std::format, I can no longer compile using the github images. I have not yet investigated on how to downgrade the cmake that is installed by default.

**Comment by takev** [comment]
The default github windows image installs:
- cmake version 3.32.1
- MSVC 19.29.30133.0

In this combination it is impossible for cmake to generate /std:c++latest. It will always do /std:c++20, even when configuring the project with: `target_compile_features(foo PUBLIC cxx_std_23)`. CMake also does not allow you to override this compile flag in any other way.

The only way around this is to downgrade cmake, wait until ABI stabilized, or write a wrapper around msvc that rewrites the argument.

**Comment by pagogc** [comment]
> Here is the [list of papers approved as defects for C++20](https://github.com/cplusplus/papers/issues?q=is%3Aissue+sort%3Aupdated-desc+label%3Aplenary-approved+label%3Ac%2B%2B23+label%3Ac%2B%2B20)

One little question:

With 16.11 and c++20 switch:
I get stable c++20 without <format> / <range> / <chrono>

With 16.11 and c++latest switch.
i get stable c++20 but unstable <format> / <range> / <chrono> (with unstable i mean only the Issues quoted above)

Is this right?

**Comment by h-vetinari** [comment]
4 more defect reports [approved](https://github.com/cplusplus/papers/issues?q=is%3Aissue+is%3Aopen+label%3Aplenary-approved+label%3AC%2B%2B20+label%3AC%2B%2B23) for C++2~0~1 🙃

**Comment by GF-Huang** [comment]
Why I can't use `std::format` in VS2022? Namespace `std` has no member `format`!!!

![image](https://user-images.githubusercontent.com/4510984/166585998-13084642-d765-4ac2-82d2-79b756f1f57f.png)

![image](https://user-images.githubusercontent.com/4510984/166586059-aa6e31ce-887d-4e68-a598-b39634ad6106.png)

**Comment by sylveon** [comment]
std::format under /std:c++20 is available in VS 17.2. For now, 17.2 is in preview. It should release to the stable branch at some point.

**Comment by JonSuper** [comment]
> Why I can't use `std::format` in VS2022? Namespace `std` has no member `format`!!!
> 
> ![image](https://user-images.githubusercontent.com/4510984/166585998-13084642-d765-4ac2-82d2-79b756f1f57f.png)
> 
> ![image](https://user-images.githubusercontent.com/4510984/166586059-aa6e31ce-887d-4e68-a598-b39634ad6106.png)

需要 VS  2019 16.11.14 or VS 2022 17.2 above

**Comment by StephanTLavavej** [comment]
@JonSuper It should be present in those versions. Are you sure you're looking at the properties for the configuration that you're actually building? I recommend looking at the build log and verifying whether `/std:c++20` is on the command line.

You can also inspect the STL's macros to check its version and Standard mode. Include `<version>` and test [`_MSVC_STL_UPDATE`](https://github.com/microsoft/STL/wiki/Macro-_MSVC_STL_UPDATE) - it should be exactly `202105L` for VS 2019 16.11.14 or any later patch, and it should be `202203L` or greater for VS 2022 17.2 or greater. Finally, after including `<version>`, you can inspect `_HAS_CXX20` which will be defined to `1` if the STL believes that it's in C++20 mode (otherwise it will be `0`).

Hopefully this should allow you to track down whether you're using an unexpected version or an unexpected compiler option.

**Comment by JonSuper** [comment]
> 



> @JonSuper It should be present in those versions. Are you sure you're looking at the properties for the configuration that you're actually building? I recommend looking at the build log and verifying whether `/std:c++20` is on the command line.
> 
> You can also inspect the STL's macros to check its version and Standard mode. Include `<version>` and test [`_MSVC_STL_UPDATE`](https://github.com/microsoft/STL/wiki/Macro-_MSVC_STL_UPDATE) - it should be exactly `202105L` for VS 2019 16.11.14 or any later patch, and it should be `202203L` or greater for VS 2022 17.2 or greater. Finally, after including `<version>`, you can inspect `_HAS_CXX20` which will be defined to `1` if the STL believes that it's in C++20 mode (otherwise it will be `0`).
> 
> Hopefully this should allow you to track down whether you're using an unexpected version or an unexpected compiler option.

![image](https://user-images.githubusercontent.com/19607102/170025561-2512ead5-abe0-4316-83e9-ec4a5a403f47.png)
@[StephanTLavavej](https://github.com/StephanTLavavej)
It will compiled fail while using VS 2022 17.2 with Visual Studio 2019 (v142) Toolset 
the yvals_core.h

**Comment by StephanTLavavej** [comment]
Ah, then the issue is that the VS 2022 IDE's selectable option of the VS 2019 v142 toolset hasn't been updated to the 16.11.14 or later bits. I believe this will happen at some point but I don't have an ETA.
