### ISSUE TITLE
<source_location>: Compilation is not stopped upon lack of compiler support

### ISSUE THREAD

**Issue by averetzi** [microsoft/STL#1935]
This is in tandem with [a Qt bug](https://bugreports.qt.io/browse/QTBUG-94038) I filed.

For whatever reason, `#include <source_location>` will simply call `#pragma message` if the compiler being used does not support `consteval`. Sadly, no version of Clang as far as I'm aware of supports `consteval`. Compilation should be stopped dead in its tracks if that's the case and not display informational warnings only (see below in commit `30ac4400e528e9837f2e8d9867da668b0de3f7eb`):

```cpp
#if _STL_COMPILER_PREPROCESSOR
#ifndef __cpp_consteval
#pragma message("The contents of <source_location> are available only with C++20 consteval support.")
#else // ^^^ !defined(__cpp_consteval) / defined(__cpp_consteval) vvv

#include <cstdint>
...
```

A simple test case really is just trying to use `std::source_location` whatsoever with Clang through Visual Studio. This will just yell at you saying  `"source_location" is not a member of namespace "std"`, instead of telling you the compiler can't do what you want.

I'm using Microsoft Visual Studio Community 2019, Version 16.10.0.

**Comment by CaseyCarter** [comment]
The code is structured like this to support the C++ feature-detection story that lets programs - especially header-only third-party libraries - determine independent of language version what features are available. The intended design is that if you want to use say `std::optional`, you can:
```c++
#if __has_include(<optional>)
// There's a header named <optional>, but it might not define `std::optional` in the current language mode
#include <optional>
#if __cpp_lib_optional >= 201606L
// Ok, the header claims to implement full C++17 optional (which could be supported in C++14 mode, or
// even in C++11 without some of the constexpr bits)
#define use_optional
#endif

[...]
#ifdef use_optional
std::optional<long> ol{42L};
#endif
```

If we were to change the headers to emit errors when included in a non-supported mode, we'd break that story.

Of course this suggests a way you can get that behavior if desired:
```c++
#include <source_location>

#if __cpp_lib_source_location < 201907L
#error source_location is not supported
#endif
```
(The various historical values of each feature-test macro are documented in [WG21's Standing Document 6](https://isocpp.org/std/standing-documents/sd-6-sg10-feature-test-recommendations).)

I hope this helps you, but as I said the behavior you observe is intentional and not a bug.

**Comment by StephanTLavavej** [comment]
You can also include `<version>` which provides all feature-test macros, and then use them to decide whether to include `<source_location>` etc.
