### ISSUE TITLE
`<ranges>`:Should I be able to a pipe a `const views::filter` into another view? (or why not?)

### ISSUE THREAD

**Issue by FreeApophis** [microsoft/STL#1942]
While playing around with the newest Compiler (16.10 and /std:c++latest) I ran into a bit of an unexpected behaviour in the filter_view, which I do not see documented in a way I could understand or find it.

I set up two views; one based on a filter one on a transformation, and I make them both [const](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rconst-immutable):
```cpp
const std::vector numbers = {1, 42, 100, 1337};

const auto filtered = numbers
    | std::views::filter([](const auto& n) { return n % 2 == 0; });

 const auto transformed = numbers
    | std::views::transform([](const auto& n) { return n * 3; });
```

When I try to pipe these const-views into another view, it works flawlessly with the transform view, but it fails with the filter view:

```cpp
auto ft = filtered
    | std::views::transform([](const auto& n) { return n / 2; });  // C2678

auto tt = transformed
    | std::views::transform([](const auto& n) { return n / 2; }); // OK
```

The first one does not compile with the following Error:

```
1>[...]: error C2678: binary '|': no operator found which takes a left-hand operand of type 'const std::ranges::filter_view<std::ranges::ref_view<std::vector<int,std::allocator<int>>>,_Ty>' (or there is no acceptable conversion)
1>        with
1>        [
1>            _Ty=main::<lambda_3>
1>        ]
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30037\include\xfilesystem_abi.h(229,1): message : could be '__std_fs_copy_options operator |(__std_fs_copy_options,__std_fs_copy_options) noexcept'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30037\include\xfilesystem_abi.h(204,1): message : or       '__std_fs_file_flags operator |(__std_fs_file_flags,__std_fs_file_flags) noexcept'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30037\include\xfilesystem_abi.h(196,1): message : or       '__std_access_rights operator |(__std_access_rights,__std_access_rights) noexcept'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30037\include\xfilesystem_abi.h(122,1): message : or       '__std_fs_stats_flags operator |(__std_fs_stats_flags,__std_fs_stats_flags) noexcept'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30037\include\xfilesystem_abi.h(79,1): message : or       '__std_fs_file_attr operator |(__std_fs_file_attr,__std_fs_file_attr) noexcept'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30037\include\cstddef(43,27): message : or       'std::byte std::operator |(const std::byte,const std::byte) noexcept' [found using argument-dependent lookup]
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30037\include\xcharconv.h(36,1): message : or       'std::chars_format std::operator |(std::chars_format,std::chars_format) noexcept' [found using argument-dependent lookup]
1>C:\Repositories\MoveExamples\MoveExamples\MoveExamples.cpp(89,73): message : while trying to match the argument list '(const std::ranges::filter_view<std::ranges::ref_view<std::vector<int,std::allocator<int>>>,_Ty>, std::ranges::views::_Transform_fn::_Partial<_Fn>)'
1>        with
1>        [
1>            _Ty=main::<lambda_3>
1>        ]
1>        and
1>        [
1>            _Fn=main::<lambda_5>
1>        ]
```

I am not sure if this intended behaviour for some reason (but what would be the reason?) or if this is a bug.

**Comment by cpplearner** [comment]
This is the intended behavior. A const `filter_view` is not a range because `filter_view` does not have a const `begin()`, because `filter_view::begin()` needs to cache the result, which modifies `*this`.

**Comment by CaseyCarter** [comment]
@cpplearner nailed this one. Note that the consequences are more far reaching than just "I can't compose a `const filter_view`", you can't even iterate over a `const filter_view`.

**Comment by FreeApophis** [comment]
OK, the "why not?" has be answered, caching. 

But I still have a hard time grasping that the standardization has decided on such a broken design which removes "range-ness" on a lazy filter_view when you declare it const. 

Naturally a functional programming view would be: there is no side-effect, the evaluation is lazy, nothing changes in the logical world view ergo this must easily be declarable as const. The naive implementation just iterates through the elements until it finds  the first matching element, so begin() can easily be declared const. So, caching is an implementation detail.

Caching is the perfect opportunity for "mutable" to seperate logical const-ness from implementation const-ness - since it does not change the percieved outside state, but is just an internal optimization. Why is this implementation-detail made public knowledge in that drastic manner?

What can I do with a `const filter_view`?

**Comment by MikeGitb** [comment]
For me the more questionable decision is that 

> filter_view::begin() needs to cache the result

as the usere could - usually - cache the resulting iterator just as well if necessary. But I'm speaking from pure ignorance.

**Comment by miscco** [comment]
Given that this would be a backward compatible change, you could always write an LWG issue or a full paper

**Comment by cpplearner** [comment]
> For me the more questionable decision is that
> 
> > filter_view::begin() needs to cache the result
> 
> as the usere could - usually - cache the resulting iterator just as well if necessary. But I'm speaking from pure ignorance and this is probably not the right forum to discuss committee decisions.

Well, I don't think normal users would realize that `for (auto&& elem : r | filter(f) | reverse) {}` calls `filter_view::begin` twice.

> EDIT:
> Btw.: according to https://en.cppreference.com/w/cpp/ranges/range
> 
> > both ranges::begin(E) and ranges::end(E) are amortized constant time **and non-modifying, and**
> 
> wouldn't that mean that a non-const `filter_view` isn't a range either, because begin does modify E?

The ranges library has a local definition of "modify" ([\[concepts.equality\]](http://eel.is/c++draft/concepts.equality#5.sentence-1)): "An expression that may alter the value of one or more of its inputs in a manner observable to equality-preserving expressions is said to modify those inputs." Since the expression does not alter the range in an observable manner, it is non-modifying.

The wording arguably can receive some improvement. I think this is an [editorial issue](https://github.com/cplusplus/draft/wiki/How-to-submit-an-editorial-issue).

**Comment by CaseyCarter** [comment]
> OK, the "why not?" has be answered, caching.
> 
> But I still have a hard time grasping that the standardization has decided on such a broken design which removes "range-ness" on a lazy filter_view when you declare it const.
> 
> Naturally a functional programming view would be: there is no side-effect, the evaluation is lazy, nothing changes in the logical world view ergo this must easily be declarable as const. The naive implementation just iterates through the elements until it finds the first matching element, so begin() can easily be declared const. So, caching is an implementation detail.
> 
> Caching is the perfect opportunity for "mutable" to seperate logical const-ness from implementation const-ness - since it does not change the percieved outside state, but is just an internal optimization. Why is this implementation-detail made public knowledge in that drastic manner?

Per [[res.on.data.races]/3](http://eel.is/c++draft/res.on.data.races#3):

> A C++ standard library function shall not directly or indirectly modify objects ([[intro.multithread]](http://eel.is/c++draft/intro.multithread)) accessible by threads other than the current thread unless the objects are accessed directly or indirectly via the function's non-`const` arguments, including `this`.

This is necessary to support the STL's thread-compatibility story, which is consistent with the core language's story. It's okay for multiple threads to access an object simultaneously as long as none of them modifies the object.

In order to memoize, we either must do so within a non-`const` function - so users know it's unsafe to call from multiple threads simultaneously - or we must synchronize to ensure that no other thread accesses the memoized value while it's being modified. Synchronization costs are not something you want to pay unnecessarily, so the final design chooses what WG21 believed to be the lesser of two evils.

> What can I do with a `const filter_view`?

You could:
* copy it or call `base()`, if the underlying range is copyable, or
* retrieve a copy of the `pred()`-icate.
Neither of these seems terribly useful.

> For me the more questionable decision is that
>
> > filter_view::begin() needs to cache the result
>
> as the usere could - usually - cache the resulting iterator just as well if necessary. But I'm speaking from pure ignorance and this is probably not the right forum to discuss committee decisions.

The `range` concept requires (and algorithms expect) that repeated calls to `begin` and `end` are O(1). Without those guarantees it would be challenging to impossible to reason about the performance of algorithms and view compositions.

> EDIT:
> Btw.: according to https://en.cppreference.com/w/cpp/ranges/range
>
> > both ranges::begin(E) and ranges::end(E) are amortized constant time and non-modifying, and
>
> wouldn't that mean that a non-const filter_view isn't a range either, because begin does modify E?

It's unfortunate that the Standard uses "modify" with two subtly different meanings, but here it means in the sense of [[concepts.equality]/5](http://eel.is/c++draft/concepts.equality#5), which could probably be better termed "observably modify". An operation _observably_ _modifies_ an operand if there exists some expression `x` which is required to be equality-preserving and `x` has observably different values when evaluated before and after application of the operation. Since `begin` on a `filter_view` always returns the same value - either the memoized value or a calculated value which is immediately memoized - it doesn't observably modify the `filter_view`.

**Comment by FreeApophis** [comment]
I had a deja vue when I watched a talk by Nico Josuttis on ACCU 2023, which goes into much detail on what was standardized. 

https://www.youtube.com/watch?v=qv29fo9sUjY
