### ISSUE TITLE
`<yvals_core.h>`: CUDA version check doesn't handle Clang-CUDA

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#1949]
After we merged #1544 which added a version check:

https://github.com/microsoft/STL/blob/3cafa97eecdbfde41ea5c09126f877a7eb97f9e9/stl/inc/yvals_core.h#L548-L553

@fodinabor [reported](https://github.com/microsoft/STL/pull/1544#issuecomment-851932884):

> This breaks CUDA with any Clang version that does not report CUDA > 10.1 (i.e. Clang from 11.0.0 to main can build with CUDA 10.1+ but always reports 10.1)
> And as the Clang version 11.0.0+ seems to be supported otherwise (implements `if constexpr`), it'd be great if we could just add a check whether clang is used or nvcc (or nvc++..)

I was unaware that Clang could compile CUDA code. This is detectable through predefined macros:

https://llvm.org/docs/CompileCudaWithLLVM.html#detecting-clang-vs-nvcc-from-code

We should consider:

1. Refining this version check (adding `!defined(__clang__)` to the last test might be correct)
2. Adding test coverage for this scenario (which should be possible as we have both Clang and the CUDA SDK installed on the CI machines)

**Comment by Artem-B** [comment]
Using compiler version (that's what `__CUDACC_VER_*`) only works with nvcc as the CUDA compiler as both CUDA SDK version and nvcc version are tightly coupled. Clang does not define any of the `__CUDACC_VER*` macros.

What we really need to check is `CUDA_VERSION`. Clang does pre-include `cuda.h` during CUDA compilation and should have that macro available.
So, something like `#if defined(__clang__) && defined(__CUDA__) && CUDA_VERSION > 10020` should do the trick.

Next question is -- what exactly does this version check enforce? Is that something that's specific to the CUDA SDK itself? Or does it have something to do with the features supported by nvcc? E.g. if the restriction is due to a C++ feature not supported by nvcc before 10.2, it may work fine when we use clang.

**Comment by mojca** [comment]
@Artem-B: a patch has already been proposed in #2075 that only blocks the old `nvcc` and doesn't care about the CUDA SDK version.

I'm blindly guessing, but judging from #189 and #1544 I suspect that the guard has primarily been added to block an old compiler that's no longer capable of coping with C++ features from the new STL version. (I'm pretty sure there's some SDK version that's too old to work even with clang, and some clang version that won't even compile CUDA, but there's probably no reason to do any more rigorous tests.)

**Comment by Artem-B** [comment]
SGTM. The patch in #2075 should work then.  Clang has been supporting `constexpr-if` since 3.9 and that's a pretty old version (https://clang.llvm.org/cxx_status.html)

**Comment by StephanTLavavej** [comment]
@mojca Yep, that guard was added to block CUDA 10.1 RTM and Update 1, which didn't support `if constexpr` (added in 10.1 Update 2).

I haven't been able to review the PR yet due to being busy with other work (and the holidays, etc.) but will try to get to it in the next week. I took a quick glance just now and the approach seems to be correct, but I need to think more deeply about any potential issues.

**Comment by Artem-B** [comment]
In that case, we should use something like this:

```c++
#if defined(__CUDACC__) && !defined(__clang__)
//... proceed checking NVCC's version via __CUDACC_VER_...
#error STL1002: Unexpected NVCC version, expected CUDA 10.1 Update 2 or newer. 
```

Clang does not need this check and should work with older CUDA versions.
