### ISSUE TITLE
Third STL Contributors Meetup

### ISSUE THREAD

**Issue by MahmoudGSaleh** [microsoft/STL#1999]
> Thanks to everyone who participated in the previous STL Contributors Meetups, #921 and #1443 . The meetups have proven to be quite valuable in clarifying our shared project goals.
> As we are getting ready for the third meetup, we would like to change the process a little bit. While the meetup is planned this summer, we do not have a specific date for it yet. We would like to collect some topics to be discussed first. Once there are enough relevant topics, we will go ahead and schedule the meetup. So, please comment on this issue proposing any agenda items.
> There are couple of items that have been proposed so far, ABI-stability timeline for C++20, #1814, and C++23 contributions.

### Update

The Third  STL Contributors Meetup is now scheduled for _Wednesday, September 15th, 2021 from 9am to 10am Pacific Time (PT)_
Please register at https://aka.ms/stl-meetup.
Agenda and more details can be found [below](#issuecomment-897127095).

#### Update (9/14)
_Reminder_: This meeting is taking place tomorrow at 9am PST. Last week, I've sent out the meeting invites to everyone who's registered. If you haven't received it, please let me know asap.

**Comment by miscco** [comment]
Thanks a lot for bringing this up and organizing the last meetups. I really enjoy chatting with the team and found them quite valuable.

I would like to raise a not so pressing first world issue. The STL is currently in the favorable situation that it "lives at head" and looking at the current pace I hope it will stay there.

Now C++20 taught us that despite the official mantra of "Ship it when its ready" there may be new features coming in that have  surprising implementation issues.

Right now there is no process in place how to provide reference implementations and exchange early implementation experiences. I believe with the ever increasing pace of new features it would be highly beneficial to shorten the feedback cycle and provide the committee with implementers directions.

It is clear that just adding issues / PRs is not a viable strategy and I do not really have a better idea so that might be something to brainstorm / discuss

**Comment by sam20908** [comment]
It'd be nice to have a contributor code review session (mirroring maintainers code review). I think this is where people will learn how to code review the best.

**Comment by jovibor** [comment]
> It'd be nice to have a contributor code review session

There is now [MSVC STL Code Review](https://www.youtube.com/playlist?list=PLReL099Y5nRffygixwNJhENbYxhuJL6Ei) videos on youtube.

**Comment by mnatsuhara** [comment]
> There is now MSVC STL Code Review videos on youtube.

Exactly!  I think what @sam20908 is suggesting is to have a similarly-structured review where a contributor is reviewing a PR, rather than a maintainer!  I think this would be a great topic of conversation at the next Contributors Meetup.

**Comment by sam20908** [comment]
I think it's also valuable to hear inputs from the maintainers towards contributors: how can we as contributors help with your work in general? I know that there are a lot of contributions from contributors, and contributor code reviews are starting to happen, but what would the maintainers like to see more?

I think this allows both sides to see the expectations from each other more clearly.

**Comment by mnatsuhara** [comment]
Below are a few ideas for improvements we can make to the repo.  We don't necessarily need to talk about _all_ of them at the meetup, but I'd love to get some feedback from contributors on which ideas you would really like to see!  

- A page on the wiki (or elsewhere, probably not the README for the sake of length) with recommendations for getting started.  This page could potentially include things like 
   - Links to tutorials, videos, presentations, on the STL, C++, etc. 
   - General workflow (fork, branch, commit, PR, etc.) 
   - Suggestions on how to interpret the Standard / how the Standard is organized 
   - ...
- Meta-documentation: A significant issue with documentation is, by the time the documentation is in place, the code / process / * that it describes has changed!  Rather than spending cycles writing explanations for things, perhaps we should write some guidance on _how to find_ explanations for things (e.g., pinging in the discord, looking it up in the Standard, trusted sources for language questions, how to get the attention of maintainers, etc.)
- Some form of a "Contribution ladder" (example [here](https://github.com/getporter/porter/blob/main/CONTRIBUTION_LADDER.md)) to recognize experience and contributions from contributors.  While a contribution ladder for the STL repo may look different, this is an interesting idea!  
   - Potential template here: https://github.com/cncf/project-template/blob/main/CONTRIBUTOR_LADDER.md

In addition, I would love to get some other thoughts from contributors on _what resources would have been helpful when you first started looking at the STL repo_?  That "first-timer experience" only happens once, and I think we can make it better and attract more new contributors.

**Comment by jovibor** [comment]
> In addition, I would love to get some other thoughts from contributors on _what resources would have been helpful when you first started looking at the STL repo_?

For the sake of clarity (especially for newcomers and PR reviews) it would be nice to have some sort of ***Maintainer*** bage. At the moment we can only see github nicknames (like **mnatsuhara**).

**Comment by StephanTLavavej** [comment]
@jovibor Is there a way to do that in GitHub's UI - something similar to reddit's user flair? (Aside from, I suppose, directly editing profile pictures.) The only way I currently know of to find out whether someone is a maintainer is to hover over their username and look for "Member of microsoft/vclibs", which is definitely not very clear.

**Comment by jovibor** [comment]
> Is there a way to do that in GitHub's UI - something similar to reddit's user flair?

I don't know for sure. But Github is a Microsoft's beast now, so I believe it can be done one way or another😎.

> The only way I currently know of to find out whether someone is a maintainer is to hover over their username and look for "Member of microsoft/vclibs"

I can see it on your name but not on **mnatsuhara**'s (I believe she's from Microsoft as well?)

> which is definitely not very clear.

Yes, it's not.
It'd better be seen on a nickname itself (e.g. **StephanTLavavej [Maintainer]**), but it will need some support from Github's backend for sure.

**Comment by mnatsuhara** [comment]
@jovibar - thanks for pointing this out!  I've adjusted the settings for my Microsoft org membership so you should hopefully be able to see my Microsoft affiliation upon hover!

**Comment by MahmoudGSaleh** [comment]
Thanks all for your input. These are great topics to discuss. We have a date for the next meetup: Wednesday, September 15th, 2021 from 9am to 10am Pacific Time (PT). We would like to invite all contributors to attend . Similar to the previous meetings, the next one will take place on Microsoft Teams. To participate, we ask you to register first for the event using this link: https://aka.ms/stl-meetup

Based on the feedback so far, here are the proposed topics for the discussion:
* Clarifying current priorities and focus areas for the repo
* ABI-stability timeline for C++20 in Dev16 and Dev17 (issue #1814)
* Where are we with v.next plans
* Process for providing reference and early implementations for C++ features in the repo
* How to improve process/resources for first-timer contribution experience
* Contributors' code review sessions
* Other areas where contributors can help

**Comment by AlexGuteniev** [comment]
I want to recall about two oldest not closed PRs:
 * Optimize random
 * <tuple>: tuple_cat for tuple-like types

Don't look good abandoned, shoulda close or finish. The second one probably needs to be closed with some excuse, but the random one apparently makes sense.

**Comment by AlexGuteniev** [comment]
> https://aka.ms/stl-meetup

The link doesn't appear to work for me

**Comment by miscco** [comment]
> > https://aka.ms/stl-meetup
> 
> The link doesn't appear to work for me

Same here

**Comment by MahmoudGSaleh** [comment]
> > > https://aka.ms/stl-meetup
> > 
> > 
> > The link doesn't appear to work for me
> 
> Same here

Sorry about this. I've just fixed it. Can you please try it again?

**Comment by AlexGuteniev** [comment]
It works now

**Comment by AlexGuteniev** [comment]
There are some performance PRs where contributors themselves cannot test them due to hardware unavailability. Mostly ARM, but one is AVX512. What to do with these PRs?

**Comment by mnatsuhara** [comment]
The notes from the meetup have been posted on the [wiki](https://github.com/microsoft/STL/wiki/MSVC-STL-Contributors-Meeting-Notes#meetup-3-2021-09-15-900am-1000am-pacific-time).  Thank you to all who attended and participated, we're looking forward to the next one!
