### ISSUE TITLE
P0019R8 atomic_ref

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#2]
[P0019R8](https://wg21.link/P0019R8) `atomic_ref`
[P1960R0](https://wg21.link/P1960R0) `atomic_ref` Cleanup (note: this paper made minor changes to other wording)

LWG-3160 `atomic_ref() = delete;` should be deleted

Feature-test macro as of WG21-N4842, added by WG21-P1902:
`#define __cpp_lib_atomic_ref 201806L`

**Comment by AlexGuteniev** [comment]
I have a question on this one.

It appears that `atomic_ref` is "the same as `atomic`, but reference". So easy way of implementing it could be adding support for references in `_Atomic_storage` and other classes.  But on the other hand, ABI should be preserved, to avoid making this vNext.

So I guess the best way to implement `atomic_ref` is to re-use existing  `_Atomic_storage` so that it is both extended to support `atomic_ref` and ABI-unchanged for `atomic`.

Want you to confirm that.

**Comment by AlexGuteniev** [comment]
Also I believe that #694 should be merged prior to starting work on this, as they change overlapping parts.

**Comment by AlexGuteniev** [comment]
I think simple change (the way which I put it in draft PR) is possible.

Standard defines:
```
T* ptr; // exposition only
```

But as it defines no way to reassign the pointer:
```
atomic_ref& operator = (const atomic_ref&) = delete
```

So it may be implemented as reference:
```
T& ptr; // exposition only
```

This replacement of value with reference allows for transparent reuse `atomic` machinery for `atomic_ref`.
