### ISSUE TITLE
static_assert on constexpr std::string fails on high bytes

### ISSUE THREAD

**Issue by maharmstone** [microsoft/STL#2050]
MSVC is currently the only compiler that supports constexpr std::string, so I'm not certain whether this is a bug or some arcane bit of the specification...

In the below code, both asserts pass, as you'd expect, but the second static_assert fails. This seems to be the case for every value >= 0x80.

```cpp
#include <string>
#include <cassert>

static constexpr std::string test(char c) {
    return std::string(1, c);
}

int main() {
    static_assert(test(0x7f) == "\x7f");
    static_assert(test(0x80) == "\x80");
    assert(test(0x7f) == "\x7f");
    assert(test(0x80) == "\x80");

    return 0;
}
```

**Comment by maharmstone** [comment]
If you try it with `std::u8string` instead, both the second static_assert and the second assert fail - but I'm not sure this means anything, as "\x80" isn't a valid UTF-8 string. If you try it with  `std::u16string` and 0x7fff and 0x8000, everything works fine.

**Comment by miscco** [comment]
This is a funny little bug in your code. Note that for MSVC the maximal value a char can take is 127 or `0x7f` (See `CHAR_MAX`

That means you are truncating your input when you are passing in 128 as a value,  which is what I am getting when I run that code:
```
C:\STL\tests\std\tests\P0980R1_constexpr_strings\test.cpp(1817): error C2220: the following warning is treated as an error
C:\STL\tests\std\tests\P0980R1_constexpr_strings\test.cpp(1817): warning C4309: 'argument': truncation of constant value
C:\STL\tests\std\tests\P0980R1_constexpr_strings\test.cpp(1817): error C2607: static assertion failed
C:\STL\tests\std\tests\P0980R1_constexpr_strings\test.cpp(1819): warning C4309: 'argument': truncation of constant value
```

Note that the code works fine with `std::wstring` so it is indeed the truncation

Why the compiler creates a different result during constant evaluation I cannot say, but this is definitely a bug on your side.

**Comment by StephanTLavavej** [comment]
This is a compiler bug that was filed in our internal database as VSO-714703 "Sign extension(?) shenanigans when evaluating constexpr string literals" with the repro:

---

Steps to reproduce:

Compile the following with `/std:c++17`.

```cpp
constexpr const char* kStr1 = "\xff";
constexpr const char kStr2[] = {'\xff', '\0'};
static_assert(__builtin_memcmp(kStr1, kStr2, 1) == 0); // error
```

Expected result: It compiles.

Actual result: The static assertion fails.

The `constexpr` evaluator does something funny with characters in string literals (see the inexplicable bitwise arithmetic in  `Constexpr::get_char<T>()`) so that `'\xff'` (which should evaluate to the decimal value of `-1` given that `char` is signed) somehow evaluates to `255` when it's in a string literal, but not when it's in an array literal.

---

I'll ping the compiler dev that this is assigned to. As this isn't a library issue, I'll go ahead and close this bug - thanks for reporting it.

**Comment by maharmstone** [comment]
Thanks!
