### ISSUE TITLE
`<iterator>`: The implementation of `common_iterator::operator==` seems to be wrong

### ISSUE THREAD

**Issue by hewillk** [microsoft/STL#2065]
MSVC-STL's implementation of `common_iterator` is similar to [libstdc++](https://github.com/gcc-mirror/gcc/blob/trunk/libstdc%2B%2B-v3/include/bits/stl_iterator.h#L1680), it defines `operator==` inside the class:
https://github.com/microsoft/STL/blob/bd7adb4a932725f60ba096580c415616486ab64c/stl/inc/iterator#L930-L940

and declares template `common_iterator` class as a friend:
https://github.com/microsoft/STL/blob/bd7adb4a932725f60ba096580c415616486ab64c/stl/inc/iterator#L1008-L1010

But according to the description of [[class.friend#10]](https://timsong-cpp.github.io/cppwp/n4868/class.friend#10): "Friendship is neither inherited nor transitive."
This will cause the following valid code to be rejected [(godbolt)](https://godbolt.org/z/15ao981Wb):

  ```
#include <iterator>

int main() {
    std::common_iterator<int*, std::unreachable_sentinel_t> it1;
    std::common_iterator<const int*, std::unreachable_sentinel_t> it2;
    return it1 == it2;
}
```

**Comment by miscco** [comment]
Urgh, we have worked around this in most of the other views. I believe the best way forward is to add `_Get_value()` and replace `_Right._Val` with `_Right._Get_value()`

Otherwise we would have to stop using hidden friends and that might be user observable as far as I can tell. On the other hand we can still break a few things with ranges. Thoughts @CaseyCarter?

**Comment by fsb4000** [comment]
@hewillk Did you create a bug report at libstdc++'s bugzilla? If not then I could do it...
