### ISSUE TITLE
<format>: Hex float precision is capped

### ISSUE THREAD

**Issue by vasama** [microsoft/STL#2156]
**Describe the bug**
`std::format` has a hard limit on the precision of hexadecimal floating point output.

**Command-line test case**
```
C:\Users\Untelo\sandbox
λ  cat test.cpp
#include <format>
#include <cassert>
using namespace std;
int main()
{
        char buffer[2048];
        auto r = to_chars(buffer, buffer + sizeof(buffer), 1.0f, chars_format::hex, 2000);
        assert(r.ec == errc{});
        assert( string_view(buffer, r.ptr - buffer) == format("{:.2000a}", 1.0f) );
}
​C:\Users\Untelo\sandbox
λ  cl /EHsc /W4 /WX /std:c++latest test.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30133 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

/std:c++latest is provided as a preview of language features from the latest C++
working draft, and we're eager to hear about bugs and suggestions for improvements.
However, note that these features are provided as-is without support, and subject
to changes or removal as the working draft evolves. See
https://go.microsoft.com/fwlink/?linkid=2045807 for details.

test.cpp
Microsoft (R) Incremental Linker Version 14.29.30133.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:test.exe
test.obj
​C:\Users\Untelo\sandbox
λ  ./test
Assertion failed: string_view(buffer, r.ptr - buffer) == format("{:.2000a}", 1.0f), file test.cpp, line 9
```

**Expected behavior**
http://eel.is/c++draft/format.string.std#22
> 
<html>
<body>

a | If precision is specified, equivalent to to_chars(first, last, value, chars_format::hex, precision) where precision is the specified formatting precision; equivalent to to_chars(first, last, value, chars_format::hex) otherwise.
-- | --

</body>
</html>

**STL version**
Version 16.11.1

**Comment by miscco** [comment]
I believe this is indeed a bug. 

The issue is that the requested precision is beyond those number of digits that could possibly have an effect on the outcome (https://github.com/microsoft/STL/blob/f75c7f596c7b491168fefb5eff5164ab7ae36867/stl/inc/format#L2310-L2325)

So we optimize that case by appending zeroes until we reach the requested precision. 

However, here https://github.com/microsoft/STL/blob/f75c7f596c7b491168fefb5eff5164ab7ae36867/stl/inc/format#L2418-L2420 we only check for the type specifiers `f` and `F` and not `a`.

this seems like a simple oversight

We only append zeros beyond you max

**Comment by vasama** [comment]
I believe `_Is_finite && _Format != chars_format::general` would be the appropriate condition here.

**Comment by miscco** [comment]
Turns out the bug is elsewhere. We currently only traceback the position of the exponent when `if (_Specs._Alt || _Specs._Localized` is true.

That means that later in the code we think the exponent starts at the end of the buffer and we happily append the zeros before the exponent, which in reality is the end of the exponent.

**Comment by miscco** [comment]
I provided a fix for hexadecimal and scientific Notation.

I could not say whether it will land in 16.11 though. That is something a maintainer could answer

**Comment by vasama** [comment]
That's fine for me, it's not blocking me. I was just reimplementing format and came across it while testing against Microsoft's implementation.
