### ISSUE TITLE
Why creating empty vector requires an allocation?

### ISSUE THREAD

**Issue by fraillt** [microsoft/STL#2170]
So here is an example:

```cpp
#include <iostream>
#include <vector>
#include <typeinfo>

template <class T>
class MyAlloc
{
public:
    using value_type = T;

    explicit MyAlloc() noexcept = default;
    template <class U>
    explicit MyAlloc(MyAlloc<U> const&) noexcept {}

    value_type*
        allocate(std::size_t n)
    {
        std::cout << "allocate: " << n << "*" << sizeof(T) << " - " << typeid(T).name() << std::endl;
        return static_cast<value_type*>(::operator new (n * sizeof(value_type)));
    }

    void
        deallocate(value_type* p, std::size_t n) noexcept
    {
        std::cout << "deallocate: " << n << "*" << sizeof(T) << " - " << typeid(T).name() << std::endl;
        ::operator delete(p);
    }
};

template <class T, class U>
bool
operator==(MyAlloc<T> const&, MyAlloc<U> const&) noexcept
{
    return true;
}

template <class T, class U>
bool
operator!=(MyAlloc<T> const& x, MyAlloc<U> const& y) noexcept
{
    return !(x == y);
}


int main() {
    std::vector<int, MyAlloc<int>> vec{ MyAlloc<int>{} };
    std::cout << "push_back" << std::endl;
    vec.push_back(3);
    return 0;
}
```

I would expect that the first line in the console output would be `push_back`, but the actual console output is this:
```
allocate: 1*16 - struct std::_Container_proxy
push_back
allocate: 1*4 - int
deallocate: 1*4 - int
deallocate: 1*16 - struct std::_Container_proxy
```

Question: why `allocate: 1*16 - struct std::_Container_proxy` is necessary, when creating an empty vector? 
I don't know of any other major compiler that does this. This behaviour complicates things unnecessarily, as I would like to pass a pool allocator, but I need to handle this special case only for MSVC.

**Comment by MikeGitb** [comment]
Was this unser release or Debug? I think it is realated to the iterator debug machinery, but just a guess.

**Comment by miscco** [comment]
This is indeed the proxy for the debug iterators. 

You could disable it by setting _CONTAINER_DEBUG_LEVEL and ITERATOR_DEBUG_LEVEL to 0

It is not recommended though as it does find nasty Bugs

**Comment by StephanTLavavej** [comment]
@miscco is correct although `_CONTAINER_DEBUG_LEVEL` doesn't interact with the proxy. Defining `_ITERATOR_DEBUG_LEVEL` to `0` project-wide will disable the iterator debugging machinery, including the proxy allocations. (It will not disable our dynamically allocated sentinel nodes in `list` and the associative containers; also `deque` always uses a proxy in its current representation.)

However, you should be aware that because this affects the representation of containers and iterators (i.e. it affects ABI), all object files and static libraries linked into a single binary (EXE/DLL) must agree on their `_ITERATOR_DEBUG_LEVEL` setting, and this applies across DLLs/EXEs if they pass STL objects around. (Also note the defaults: debug mode defaults to IDL=2, release mode defaults to IDL=0 and cannot select IDL=2 ever. Nobody uses IDL=1 which is a historical relic.)

The `_Container_proxy` object is used to allow "parent" containers and "children" iterators to communicate with each other. When a container is fully or partially invalidated (e.g. mid-erasure in a `vector` will partially invalidate iterators), the container must inspect all of its outstanding iterators and invalidate any that point to erased/destroyed/etc. elements. Thus the container maintains an intrusive singly-linked list of iterators. Iterators also need to be able to find their parent container - e.g. comparing iterators is valid only when they have the same parent. If iterators had a direct pointer to their parent, then swapping containers would break those direct pointers. So, the proxy objects introduce a layer of indirection. Every container owns a dynamically allocated proxy object (including after default construction), iterators store a pointer to the proxy, and the proxy stores a pointer to the container. This allows us to swap containers in constant wall-clock time by swapping their proxy objects, which automatically updates all of their iterators.

For the vNext ABI-breaking release (no ETA yet), I have a mostly-completed refactoring of this scheme (stranded in our ancient Team Foundation Version Control branch, not yet available on GitHub). This upgrades the intrusive singly-linked list to circular doubly-linked (allowing iterators to remove themselves in constant time), and replaces the dynamically allocated proxy object with simply locking and updating all iterators (which is *technically* conformant even though it's no longer constant wall-clock time for swapping). We expect that this should be less disruptive although not all scenarios will see a performance benefit.
