### ISSUE TITLE
<filesystem>: copy_file(a, b, update_existing) fails when b is locked even if no copy is needed

### ISSUE THREAD

**Issue by sylveon** [microsoft/STL#2185]
**Describe the bug**
Consider a case where the target file is newer (or the same date) as the source file, but the target file has a lock being held somewhere. copy_file will complain about the lock being present on the target file, despite not having to copy the file.

**Command-line test case**
```
C:\Temp>type repro.cpp
#include <filesystem>
#include <fstream>
#include <iostream>
#include <string_view>
#include <Windows.h>

void write_to_file(const std::filesystem::path& file, std::string_view contents)
{
    std::ofstream stream(file);
    stream << contents;
}

int main()
{
    write_to_file(L"old.txt", "old contents");
    Sleep(10); // make sure the timestamps differ.
    write_to_file(L"new.txt", "new contents");

    // hold an exclusive handle to the file. in real world a third party program may do that.
    CreateFileW(L"new.txt", GENERIC_READ, 0, nullptr, OPEN_EXISTING, 0, nullptr);
    try
    {
        std::filesystem::copy_file("old.txt", "new.txt", std::filesystem::copy_options::update_existing);
    }
    catch (const std::filesystem::filesystem_error& err)
    {
        std::cout << err.what();
    }
}

C:\Temp>cl /EHsc /std:c++17 .\repro.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.30.30423 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

repro.cpp
Microsoft (R) Incremental Linker Version 14.30.30423.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:repro.exe
repro.obj

C:\Temp>.\repro.exe
copy_file: The process cannot access the file because it is being used by another process.: "old.txt", "new.txt"
```

**Expected behavior**
Since a copy isn't needed here, there should be no failure.

**STL version**
```
Microsoft Visual Studio Community 2022 Preview (64-bit)
Version 17.0.0 Preview 3.1
```

**Additional context**
This happens because `__std_fs_copy_file` opens a handle with exclusive access (no sharing), to check the last write time. Instead of opening an handle, `GetFileAttributesEx` can be used. It won't open an handle and will give the last write time.

**Comment by strega-nil-ms** [comment]
There are two separate bugs here that I've noticed from the original bug - assume `a` and `b` exist, and `options = skip_existing || options = update_existing`.

- If `a` is opened for reading, we should be able to still copy from `a`, and my understanding of the code is that this will fail with an error.
- If `b` is opened for reading (but not writing), we could in theory read the attributes on it without opening it for writing; then, if `options = update_existing` but `b` is younger than `a`, we could succeed. Else, we'd have to reopen `b` for writing.

The first of these is very clearly a bug; `copy_file(a, b, skip_existing)` and `copy_file(a, b, update_existing)` both fail if `a` is opened for reading, which is just wrong. The only thing we actually care about is if `a` is opened for writing. We must know that `a` is not opened for writing, however, because otherwise we'd have a TOCTOU issue:

- Assume `a` was last written less recently than `b`
- Set `aTime` = `a`'s last write time
- Set `bTime` = `b`'s last write time
- Another process opens and writes to `a`, then closes the file
- Now, `aTime` < `bTime` but `a`'s last write time > `b`'s last write time
- So, we don't copy even though we should.

The second issue is also very solvable with `ReOpenFile`, added in Vista (so we can use it!)

**Comment by strega-nil-ms** [comment]
Given that we don't care about TOCTOU in this function, I'm going to implement a solution as follows:

* Get metadata on both files with `status()` equivalent
* Check the last write time
* allow `CopyFile` to fail if `equivalent(a, b)`

**Comment by sylveon** [comment]
I don't think it has a TOCTOU right now. Opening the files with exclusive access (like is done currently) means that nobody else can write to it, so the last change time is frozen until we close it.

**Comment by strega-nil-ms** [comment]
@sylveon Currently, it does:

- CopyFile(a, b, don't overwrite)
- open a
- open b
- close b
- close a
- CopyFile(a, b, overwrite)

**Comment by sylveon** [comment]
Ah, I missed the first CopyFile, my bad.
