### ISSUE TITLE
Possibly default `_HAS_EXCEPTIONS` to `__cpp_exceptions`?

### ISSUE THREAD

**Issue by NekkoDroid** [microsoft/STL#2216]
Currently if exceptions are disable on the compiler side (at least with CMake by modifying CMAKE_CXX_FLAGS) the STL still compiles with exceptions enabled unless manually specifying `_HAS_EXCEPTIONS`. This causes warnings in headers that use exceptions even if not explicitly using throwing methods.

Since I assume a lot of devs rely on manually enabling/disabling exceptions with `_HAS_EXCEPTIONS` regardless of compiler exception support, I would assume replacing all  `_HAS_EXCEPTIONS` with `__cpp_exceptions` would be a unneeded breaking change. So I was wondering if defaulting `_HAS_EXCEPTIONS` if not already define to whether or not `__cpp_exceptions` is enabled would be possible?

**Comment by StephanTLavavej** [comment]
Thanks for the suggestion. Because `_HAS_EXCEPTIONS=0` is largely untested, undocumented, and unsupported, and because (we believe) it affects ABI, automatically enabling it for projects that are compiling without `/EH` would be a breaking change. Changing the default behavior here would be something to consider if and when we develop a robust no-exceptions mode for the STL (likely in the vNext binary-breaking release).
