### ISSUE TITLE
P1072R10 `basic_string::resize_and_overwrite`

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#2244]
[P1072R10](https://wg21.link/P1072R10) `basic_string::resize_and_overwrite`

Feature-test macro:
`__cpp_lib_string_resize_and_overwrite`

**Comment by AlexGuteniev** [comment]
> Remarks: If op throws the behavior is undefined.

ouch. this makes the new method way less useful. why don't we have basic exception guarantee when it is easy to have it?

**Comment by AlexGuteniev** [comment]
> The authors further recommend UB if op were to throw. `resize_and_overwrite` is motivated by measured performance improvements that are small individually but significant at scale. Providing exception guarantees would incur overhead that is in tension with the original motivation.

I disagree, It cost almost nothing to apply a null terminator in destructor or apply it before calling `op` for one extra time.

However, not being exception safe makes `resize_and_overwrite` not useful for scenarios when you call some API that fills `char*`. Because APIs either throw by themselves, or would have error code check in lambda that would throw.

I think the behavior when `op` throws should be leaving the string in unspecified but valid state.

And I agree if `op` returns a value out of range that's UB.

**Comment by hewillk** [comment]
In [[string.capacity]](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2021/p1072r10.html#string.capacity), I don't quite understand why we need `std::move(op)(p, n)` to operate `buf` instead of just `op(p, n)`, which seems a bit strange.

**Comment by AlexGuteniev** [comment]
@hewillk, probably `op` could be
```C++
struct op {
   size_t operator()(const char* p, size_t n) &&;
}
```
