### ISSUE TITLE
<mutex> : std::mutex::mutex is not constexpr

### ISSUE THREAD

**Issue by tiagomacarios** [microsoft/STL#2285]
This is mentioned in other issues, but I wanted a bug report tracking this explicitly. For the curious see #946.

`std::mutex::mutex` is `constexpr` as of c++11, but even in c++17 MSVC will not support it.
Minimal repro:
https://godbolt.org/z/5Yc56hEG7
```c++
#include <mutex>

struct S {
    constexpr S() noexcept = default;
    std::mutex m_mutex;
};

static constexpr S s{};
```

**Comment by AdamBucior** [comment]
Could we make `shared_mutex` constructor `constexpr` so that people who need it can have an alternative?

**Comment by StephanTLavavej** [comment]
Perhaps an LWG issue should be submitted to allow `shared_mutex`'s constructor to be `constexpr`, as static initialization is preferable to dynamic initialization. As we just store `nullptr`, we would easily be able to implement such a resolution.

**Comment by AlexGuteniev** [comment]
I've tried to look into it. So we need to implement `Concurrency::details::stl_critical_section_win7` and `_Mtx_internal_imp_t` which contains it in a header. These are not _Ugly. Should we:
 * Implement _Ugly version that does not match existing names?
 * Make non-_Ugly names visible in headers?

**Comment by BillyONeal** [comment]
> Per the discussion in #2286, we believe `mutex`'s default constructor can feasibly be made `constexpr` absent the need to support Vista. We'll need to figure out precisely how to wiggle the class definition so the in-memory representation of a default-constructed `mutex` looks exactly like the current result of dynamic-initialization on a Windows-7-or-later box.

I don't believe this is true, at least for std::mutex's current guarantees, because the vtbl must live in the STL's DLL. Otherwise, mutexes created by a user DLL become radioactive if that user DLL is unloaded. (There's a similar problem in `system_error` for `generic_category` and `system_category`, but `error_code`s tend not to be super long-lived objects likely to trigger the problem vs. mutexes)

**Comment by AlexGuteniev** [comment]
@BillyONeal suggested a possible workaround for his concern: use `__builtin_isconstant_evaluated()` and do constant initialization to a new implementation only in `constexpr` context, while keeping old initialization for runtime.

Still there are problems in getting vtable class into mutex:
 * mutex subobjects can't contain a vtable directly due to `is_standard_layout` requirement
 * vtable cannot be copied via `__builtin_bit_cast` due to requirement of `trivially_copyable`
 * fake vtable could have worked, but
   * the mutex subobject uses methods, that take `this`
   * these methods use `__thiscall` calling convention, that isn't similar to any non-method calling convention
   * specifically, `bool try_lock_for(unsigned int)` will take on x86 one parameter via a register, and one via stack

Maybe it can be done using fake vtable + using assembly when needed in impl, but it seems to be going too far risky way.

**Comment by Fedr** [comment]
There is a [question](https://stackoverflow.com/q/68970111/7325599) on Stackoverflow about this issue.

**Comment by pdimov** [comment]
FWIW, I just got a bug report against Boost.System caused by `std::mutex`'s default constructor not using static initialization: https://github.com/boostorg/system/issues/102.

**Comment by frederick-vs-ja** [comment]
I think this can definitely be fixed for `/MT` and `/MTd` - I've successfully tried the way that forward-declares a dummy variable and then let the linker alias it with `Concurrency::details::stl_critical_section_win7`'s vtable. The address is a constant expression and works for `constexpr` constructor.

But it didn't work for `/MD` or `/MDd` to merely do so. Perhaps we need to export the vtable.

**Comment by frederick-vs-ja** [comment]
Possible approches (IMO) for `/MD` & `/MDd`:
1. (suggested by @AlexGuteniev on Discord) Move `Concurrency::details::stl_critical_section_win7`'s vtable to an import lib. I don't know how to do this, should we move `_Mtx_init_in_situ` to import lib?
2. Additionally export `??_7stl_critical_section_win7@details@Concurrency@@6B@` (the mangled name of `Concurrency::details::stl_critical_section_win7`'s vtable) for DLL.
3. Use a fake vtable for static initialization, and use `_Mtx_init_in_situ` for dynamic initialization. Presumably all statically initialized mutexes that are created within a user DLL are destroyed when the DLL is unloaded. I think I've made a successful attempt by "scary" emulation with `__fastcall`.
