### ISSUE TITLE
<filesystem>: `directory_entry(const path& p, error_code& ec)` does not return error code

### ISSUE THREAD

**Issue by e4lam** [microsoft/STL#232]
https://github.com/microsoft/STL/blob/d736fe46b950860a29d420da44da40c0df62b8cb/stl/inc/filesystem#L2106-L2109

Notice the `_Ec` is cleared but never assigned the return value of `_Refresh()`. Compare this with:

https://github.com/microsoft/STL/blob/d736fe46b950860a29d420da44da40c0df62b8cb/stl/inc/filesystem#L2147-L2149

This is at best inconsistent with calling `std::directory_entry::refresh( std::error_code& ec)` but I would argue that it's the constructor that's wrong.

This can be easily tested by giving these two methods the same non-existent file path. The expected behaviour is that both of these methods return the same `error_code` value. i.e. NOT having the constructor form return success for an error code, but then calling `refresh()` returns a failure error code.

**Sample test code**
```
// compile with: cl /std:c++17 /permissive- /EHsc /Od /Zi symlink.cpp
// run: .\symlink does_not_exist
//
#include <filesystem>
#include <iostream>
namespace fs = std::filesystem;

int main(int argc, const char* argv[])
{
  if (argc < 2)
  {
    std::cerr << "Missing file path argument\n";
    return -1;
  }
  fs::path dst(argv[1]);

  std::error_code err1;
  fs::directory_entry src(dst, err1);
  std::cout << "directory_entry(" << dst << ") = " << err1 << " " << err1.message() << "\n";

  std::error_code err2;
  src.refresh(err2);
  std::cout << "refresh(" << dst << ") = " << err2 << " " << err2.message() << "\n";

  return 0;
}
```

Also tracked by Microsoft-internal VSO-1012326 / [AB#1012326](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1012326).

**Comment by StephanTLavavej** [comment]
I read WG21-N4835 [fs.dir.entry.cons]/1 "*Effects:* Constructs an object of type `directory_entry`, then `refresh()` or `refresh(ec)`, respectively." as saying that this is clearly a bug.

**Comment by e4lam** [comment]
A possibly separate issue is whether calling these with a non-existent path should return a failing error_code failure given that there is `directory_entry::exists()` is supposed to be able to return true/false.

**Comment by StephanTLavavej** [comment]
Please file a separate issue if you believe that’s another bug.

**Comment by Arzaghi** [comment]
> I read [WG21-N4835](https://wg21.link/N4835) [fs.dir.entry.cons]/1 "_Effects:_ Constructs an object of type `directory_entry`, then `refresh()` or `refresh(ec)`, respectively." as saying that this is clearly a bug.

I'm investigating and trying to solve the issue. However, I'm wondering calling `refresh()` means most of the member functions mentioned under `[fs.dir.entry.cons]` and `[fs.dir.entry.mods]` should throw on error. Although this is on the contrary to lots of test cases in `P0218R1_filesystem`, Furthermore other implementations [do not throw on bad inputs](https://godbolt.org/z/oYqKzT).
Am I right or I did miss something here?

**Comment by StephanTLavavej** [comment]
(Apologies for the delayed reply, I have been unable to keep up with my notifications)

I observe that directly calling `src.refresh();` in your example still doesn't emit an exception - I am unsure exactly what situation is needed to trigger an exception. It does seem that many member functions should be calling `refresh()` and I'll add a comment in my review of your PR.

**Comment by BillyONeal** [comment]
> I observe that directly calling `src.refresh();` in your example still doesn't emit an exception - I am unsure exactly what situation is needed to trigger an exception. It does seem that many member functions should be calling `refresh()` and I'll add a comment in my review of your PR.

That is not permitted. The data can be cached or not, and the only operation allowed to affect cache status is a call to refresh on the part of the user. See http://eel.is/c++draft/fs.class.directory.entry

**Comment by BillyONeal** [comment]
This behavior is by design; we changed directory_iterator's constructors to always be non-failing. Atttempting to access any of the actual data when the directory_entry has been put into this state will try to access the data then.

Note that for portable behavior, callers must check for errors in those places too, because implementations might not cache in their directory_entry.

@StephanTLavavej This behavior was changed before GitHub: 

* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/660628/ "<filesystem> directory_entry(nonexistent) should not fail"
* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/msvc/commit/90ad42af5b9bac66319e745e1b730fc3d7030989?path=%2Fsrc%2Fvctools%2Fcrt%2Fcrtw32%2Fstdhpp%2Ffilesystem&_a=contents

**Comment by BillyONeal** [comment]
Also note that we explicitly changelogged this in https://devblogs.microsoft.com/cppblog/cpp17-20-features-and-fixes-in-vs-2019/

> std::filesystem::directory_entry‘s constructor was changed to store a failed result, rather than throwing an exception, when supplied a nonexistent target path.

**Comment by e4lam** [comment]
@BillyONeal Sorry, I'm not following your comments here but I'm probably just being dense.

> This behavior is by design; we changed directory_iterator's constructors to always be non-failing. Atttempting to access any of the actual data when the directory_entry has been put into this state will try to access the data then.
>
> Note that for portable behavior, callers must check for errors in those places too, because implementations might not cache in their directory_entry.

How does `directory_iterator` specifically relate to `directory_entry(const filesystem::path& p, error_code& ec)` with regards to this bug? Probably because I don't understand this part, the next "portable behaviour" comment does not compute. If one is calling a function that returns an error code, then of course it is the callers responsibility to check it.


> Also note that we explicitly changelogged this in https://devblogs.microsoft.com/cppblog/cpp17-20-features-and-fixes-in-vs-2019/
> 
> > std::filesystem::directory_entry‘s constructor was changed to store a failed result, rather than throwing an exception, when supplied a nonexistent target path.

When you say "store a failed result", where is it being stored? I would expect it to be stored in the `ec` out parameter of `directory_entry(const filesystem::path& p, error_code& ec)`.

**Comment by BillyONeal** [comment]
> @BillyONeal Sorry, I'm not following your comments here but I'm probably just being dense.

I'm probably just not explaining well :)

> > This behavior is by design; we changed directory_iterator's constructors to always be non-failing. Atttempting to access any of the actual data when the directory_entry has been put into this state will try to access the data then.
> > Note that for portable behavior, callers must check for errors in those places too, because implementations might not cache in their directory_entry.
> 
> How does `directory_iterator` specifically relate to `directory_entry(const filesystem::path& p, error_code& ec)` with regards to this bug?

`directory_iterator` generally fills in the cached contents itself, it never calls this constructor.

https://github.com/microsoft/STL/blob/bd7adb4a932725f60ba096580c415616486ab64c/stl/inc/filesystem#L2554

The whole reason that directory_entry caches anything (and why the standard was changed to permit such caching) is that the underlying enumeration API on Windows, `FindFirstFileW`/`FindNextFileW`/`FindClose`, returns a bunch of this information as part of the enumeration process, and we wanted to avoid performance penalties of reopening every file again to get the information. This was http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0317r1.html . In that sense, it's related to directory_iterator because that's why the behavior exists.

Back when we initially implemented filesystem, we aggressively tried to cache information when a `directory_entry` was constructed, to make it indistinguishable from one generated by `directory_iterator`. Unfortunately, this caused problems for people upgrading experimental filesystem (N4100) code, where a common pattern was something like:

```
for (directory_entry&& e : directory_iterator("something")) {
    auto source = e;
    e.replace_filename("something-nonexistent"); // always safe in N4100, throws in initial MSVC filesystem implementation
    copy_file(source, e); // note implicit conversion to path
}
```

... which threw an exception in the new implementation because the result after replace_filename was nonexistent. After LEWG indicated that they did not like this outcome, meaning this "directory_iterator is not bound to an actual file" state could appear as part of normal operation, we changed the constructors to be non-failing in the same way replace_filename was changed to be non-failing. Eric Fiselier (of libc++ at the time) was supposed to write the paper to codify this change into the standard, but we implemented it early because the new behavior was permitted by the old wording.

>Probably because I don't understand this part, the next "portable behaviour" comment does not compute. If one is calling a function that returns an error code, then of course it is the callers responsibility to check it.

It sounds like from your report that you expected the error to reported by the constructor but not from the actual data access function (`status`). My point is that the standard allows implementations to make either one, or both, or neither, failing. (And in fact, on most POSIX implementations, they don't cache anything in directory_entry so the constructor is non-failing for them)

> > Also note that we explicitly changelogged this in https://devblogs.microsoft.com/cppblog/cpp17-20-features-and-fixes-in-vs-2019/
> > > std::filesystem::directory_entry‘s constructor was changed to store a failed result, rather than throwing an exception, when supplied a nonexistent target path.
> 
> When you say "store a failed result", where is it being stored? I would expect it to be stored in the `ec` out parameter of `directory_entry(const filesystem::path& p, error_code& ec)`.

directory_entry has a "there is nothing in the cache because last time we tried to refresh() failed" state (resulting from the aforementioned behavior of replace_filename and the constructor changing). We intentionally don't report the failure to get the information there, and instead just try again when the user asks for file_size or status or ...

**Comment by BillyONeal** [comment]
> @StephanTLavavej This behavior was changed before GitHub:
> 
> * https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/660628/ " directory_entry(nonexistent) should not fail"

Here's a screenshot of that internal bug with the intended behavior we implemented:
![image](https://user-images.githubusercontent.com/1544943/127057553-f848b165-7959-4af1-94da-b00bae5a91c0.png)

**Comment by e4lam** [comment]
> Back when we initially implemented filesystem, we aggressively tried to cache information when a `directory_entry` was constructed, to make it indistinguishable from one generated by `directory_iterator`. Unfortunately, this caused problems for people upgrading experimental filesystem (N4100) code, where a common pattern was something like:
> 
> ```
> for (directory_entry&& e : directory_iterator("something")) {
>     auto source = e;
>     e.replace_filename("something-nonexistent"); // always safe in N4100, throws in initial MSVC filesystem implementation
>     copy_file(source, e); // note implicit conversion to path
> }
> ```
> 
> ... which threw an exception in the new implementation because the result after replace_filename was nonexistent. After LEWG indicated that they did not like this outcome, meaning this "directory_iterator is not bound to an actual file" state could appear as part of normal operation, we changed the constructors to be non-failing in the same way replace_filename was changed to be non-failing. Eric Fiselier (of libc++ at the time) was supposed to write the paper to codify this change into the standard, but we implemented it early because the new behavior was permitted by the old wording.

PR #1343 changed it so that "file not found" is never reported as an error condition. So then this approach would also work for this code snippet right? `e.replace_filename("something-nonexistent")` will not error out *AND* we also get consistent error handling between the constructor and `refresh()`.

There are other error conditions here that might happen of course. For example, the filename might have invalid file system characters. So it's still reasonable for the `refresh()` (and any method that has the "effect of `refresh()`")to trigger error conditions.

> It sounds like from your report that you expected the error to reported by the constructor but not from the actual data access function (`status`). My point is that the standard allows implementations to make either one, or both, or neither, failing. (And in fact, on most POSIX implementations, they don't cache anything in directory_entry so the constructor is non-failing for them)

Yes, I expected the constructor to do a file operation because the spec specifically said that the constructor [calls refresh() or refresh(ec), respectively.](http://eel.is/c++draft/fs.class.directory.entry#fs.dir.entry.cons-1). And clearly `refresh()` is a file operation meant to cache values. 

I agree that the post-condition of the constructor to clear its internal path doesn't make sense in the first place. However, I'm missing the reasoning why any of this should force us into a world where `directory_entry(const filesystem::path& p, error_code& ec)` returns a different error code from calling `void refresh(error_code& ec) noexcept`. And that is really the crux of the problem here.

**Comment by BillyONeal** [comment]
> PR #1343 changed it so that "file not found" is never reported as an error condition. So then this approach would also work for this code snippet right? `e.replace_filename("something-nonexistent")` will not error out _AND_ we also get consistent error handling between the constructor and `refresh()`.

That indeed may resolve the LEWG concern. However, it  creates a divergence between handling of some of the cached values (like file_size) and the file type / status. I'm not sure that's desirable, and filesystem has been shipping for long enough that we need to be very careful about introducing subtle cases that can emit more errors now.

I will defer to the current maintainers, but if I were still an STL maintainer I would be wanting a real world example where adopting such a change would fix a bug in end user code before going there.

>However, I'm missing the reasoning why any of this should force us into a world where directory_entry(const filesystem::path& p, error_code& ec) returns a different error code from calling void refresh(error_code& ec) noexcept. And that is really the crux of the problem here.

I'm not sure I view those always returning the same error code as desirable here; I think the current invariant that creating directory_entries never hits the disk is a useful one. The interface in the standard from P0317 was added because at the last minute we needed to do something to make `directory_iterator` not dead-on-arrival on Windows, not something validated through careful usage experience. In particular, I think it was thought that attributes being cached would be an invariant, that a cache cleared state would be entirely unrepresentable, but it turned out we needed such a state anyway. The other 2 major implementations aren't likely to discover such things because targeting `readdir`, they don't cache anything.

**Comment by e4lam** [comment]
> I will defer to the current maintainers, but if I were still an STL maintainer I would be wanting a real world example where adopting such a change would fix a bug in end user code before going there.

I certainly encountered this problem in real life but this was 2 years ago now and so I'd need to go find the code that spawned this bug and then review commit logs to figure out what was the code before I worked around this bug.

> I'm not sure I view those always returning the same error code as desirable here; I think the current invariant that creating directory_entries never hits the disk is a useful one. would be entirely unrepresentable, but it turned out we needed such a state anyway. The other 2 major implementations aren't likely to discover such things because targeting `readdir`, they don't cache anything.

**Comment by e4lam** [comment]
> However, it creates a divergence between handling of some of the cached values (like file_size) and the file type / status.

Where/how does this divergence arise and why it is bad? When `directory_entry` is created from `directory_iterator`, it can be filled in with the results of FindFirst and so it then becomes cached data without incurring extra filesystem access. The rest of the accessors for cached values have clear semantics that an error is only returned if the requested data was uncached. (eg http://eel.is/c++draft/fs.class.directory.entry#fs.dir.entry.obs-21 ). This caching behaviour sounds quite expected to me but I get the sense that you're referring to something else that I'm not seeing.

> I will defer to the current maintainers, but if I were still an STL maintainer I would be wanting a real world example where adopting such a change would fix a bug in end user code before going there.

I certainly encountered this problem in real life but this was 2 years ago now and so I'd need to go find the code that spawned this bug and then review commit logs to figure out what was the code before I worked around this bug and if this code was moved, etc. (@Arzaghi , I don't know the circumstances as to what led you to this issue?)

> I'm not sure I view those always returning the same error code as desirable here; I think the current invariant that creating directory_entries never hits the disk is a useful one. 

Again, I'm missing something that you're seeing. `directory_entry(const filesystem::path& p, error_code& ec)`  hits the disk regardless of PR #1343, it hits the disk as much (or not) as before. Previously, it was calling `_Refresh(_Cached_data, _Path);` and now it's effectively doing `_Ec = _Make_ec(_Refresh(_Cached_data, _Path));` except with a check to suppress file not found. 

Perhaps I'm missing something on the reading of the PR, but there has been no changes to the refresh calls here. Now if you're to argue that perhaps PR #1371 is causing more cases where an exception might be thrown more than it did previously, then that's something for @Arzaghi to defend. I'm also fine with not clearing the path when an error is encountered in the constructor.

However, in all the code paths where an error code can be returned, I strongly believe that we should be returning them and not throwing it away. Otherwise, we've lost that information permanently, incurring EXTRA disk access to recover that and assuming that the filesystem hasn't changed in the mean time as well.

> The other 2 major implementations aren't likely to discover such things because targeting `readdir`, they don't cache anything.

AFAIR, I think I ran into this bug only on Windows and not on Linux/OSX where I was using the libc++'s implementation.

**Comment by e4lam** [comment]
@BillyONeal I'm trying to reread your comments and just plain getting confused. For example, your comment that

> (And in fact, on most POSIX implementations, they don't cache anything in directory_entry so the constructor is non-failing for them)

already doesn't make sense to me. The fact that they don't cache anything means that they're hitting the filesystem and therefore may in fact fail. And to take a concrete implementation, we have https://github.com/llvm/llvm-project/blob/c6b0b16c0f55c34f4eaa05184815bbbe97f4b750/libcxx/include/filesystem#L2331

```  directory_entry(_Path const& __p, error_code& __ec) : __p_(__p) {
    __refresh(&__ec);
  }```

**Comment by BillyONeal** [comment]
> > However, it creates a divergence between handling of some of the cached values (like file_size) and the file type / status.
> 
> Where/how does this divergence arise and why it is bad? When `directory_entry` is created from `directory_iterator`, it can be filled in with the results of FindFirst and so it then becomes cached data without incurring extra filesystem access. The rest of the accessors for cached values have clear semantics that an error is only returned if the requested data was uncached. (eg http://eel.is/c++draft/fs.class.directory.entry#fs.dir.entry.obs-21 ). This caching behaviour sounds quite expected to me but I get the sense that you're referring to something else that I'm not seeing.

That's true, but whether the data is cached or not is not supposed to be a salient property of the values, because implementations exist that are never cached ever.

> Perhaps I'm missing something on the reading of the PR, but there has been no changes to the refresh calls here. Now if you're to argue that perhaps PR #1371 is causing more cases where an exception might be thrown more than it did previously, then that's something for @Arzaghi to defend. I'm also fine with not clearing the path when an error is encountered in the constructor.

That's indeed what I meant.

> AFAIR, I think I ran into this bug only on Windows and not on Linux/OSX where I was using the libc++'s implementation.
> And to take a concrete implementation, we have https://github.com/llvm/llvm-project/blob/c6b0b16c0f55c34f4eaa05184815bbbe97f4b750/libcxx/include/filesystem#L2331

Interesting, they must have changed course on that one; they told me at the time they intended to cache nothing. I believe libstdc++ does cache nothing.
