### ISSUE TITLE
<format>: Wide and multibyte versions different behavior for char arg.

### ISSUE THREAD

**Issue by jovibor** [microsoft/STL#2320]
```cpp
#include <iostream>
#include <format>

int main()
{
	char ch = -1;
	std::cout << std::format("cout: {:d}\r\n", ch);
	std::wcout << std::format(L"wcout: {:d}\r\n", ch);
}
```
The output:
![image](https://user-images.githubusercontent.com/5625787/139983869-7274b96f-c16d-44a6-a20e-da151b7cf510.png)

Shouldn't the result be the same?
`VS 16.11.5`
Unfortunately I can't test in VS 17 at the moment.

**Comment by CaseyCarter** [comment]
This is by design, but it seems like a defect to me. Per [format.arg]/5, initializing a `basic_format_arg` with a `char`  `c` when `char_type` is `wchar_t` results in initializing the `basic_format_arg`'s stored value with `static_cast<wchar_t>(c)`. On our supported platforms, `char` is signed and `wchar_t` is unsigned and has 16-bit width, so `static_cast<wchar_t>(char(-1))` is in fact `wchar_t{65535}`. Our behavior is what the Standard specifies. I observe that the specified would be reasonable (1) if the type character in the format string were `c` instead of `d`, or (2) if `char` were unsigned (whether plain `char` is signed or unsigned is implementation-defined in C++).

I _think _ the fix is to use a different storage type that is properly value-preserving regardless of the signed-ness of `char` (e.g., `int`), which will then do the right thing whether formatted with `d` or `c`. We need to validate this suggestion, implement it, and submit an LWG issue.

**Comment by jovibor** [comment]
The wording is [here](https://eel.is/c++draft/format#arg-5.2), but for me this is definitely wrong, blindly convert from signed to unsigned type.
`Fmt` library, btw, in both cases returns same result `-1`.

**Comment by jovibor** [comment]
Is there any news on the subject, or where to track it?
Or it's gonna be another ABI-locked-C++ quirk, etched in the stone of time😌?

**Comment by frederick-vs-ja** [comment]
This may be fixable without ABI breakage. Perhaps there're still 2 spares (`1 << 4 - 14`) for additional type indicating tags. I.e. we might be able to add `_SChar_type` or `_Narrow_char_type` to the end of the enumerator list.
https://github.com/microsoft/STL/blob/a62109595b6d89e08172fdf4beb75a2670fe0cc9/stl/inc/format#L100-L115
Then we should be able to tell `char` from `wchar_t` when `char_type` is `wchar_t`.

**Comment by frederick-vs-ja** [comment]
WG21-P2909R1 will make the `char` value stored as the promoted type of `unsigned char` (`int` on most platforms) in this case, which, IIUC, will resolve the problem posted here.

But I don't know whether `std::format(L"{:?}", static_char<char>(-1))` will still work...

**Comment by cpplearner** [comment]
Why `int`? Is it because `basic_format_arg` behaves as-if it contains a `variant`, and the `variant` won't hold an `unsigned char`?

@vitaut, does [P2909R1](https://wg21.link/P2909R1) intentionally make `basic_format_arg` hold an `int` in this case?

**Comment by frederick-vs-ja** [comment]
> Why `int`? Is it because `basic_format_arg` behaves as-if it contains a `variant`, and the `variant` won't hold an `unsigned char`?
> 
> @vitaut, does [P2909R1](https://wg21.link/P2909R1) intentionally make `basic_format_arg` hold an `int` when `TD` is `char` and `char_type` is `wchar_t`?

Oh, I found that was a mistake. In [P2909R2](https://wg21.link/p2909r2) the stored value is changed to `static_cast<wchar_t>(static_cast<unsigned char>(v))`, so the `char` value won't be handled as an `int`.
