### ISSUE TITLE
<memory>: Add nullptr check in std::allocator

### ISSUE THREAD

**Issue by hannes-harnisch** [microsoft/STL#2362]
**Describe the bug**
As discussed with @StephanTLavavej on the STL Discord server, it might be a good idea to add a debug-only nullptr assertion inside `std::allocator<T>::deallocate`, checking the pointer parameter. Passing nullptr to this member function is undefined behavior when the passed size is non-zero, however users not aware of this fact might pass nullptr expecting behavior similar to passing nullptr to `operator delete`, given that they are closely related.

Although many nullptr assertions have been removed from the STL because it is normally obvious in the debugger when a nullptr dereference occurs, this case is a bit different. At least in the latest VS2022 preview version of the STL, this UB may only become noticeable after a pointer subtraction in a certain branch somewhere within `deallocate` causes the pointer to underflow to `0xFFFF...` followed by a dereference of the underflowed pointer, making a misuse of this member function not only rarely noticeable and if it does get noticed, it is rather non-obvious what went wrong.

**Command-line test case**
```
C:\Temp>type repro.cpp
#include <memory>

int main() {
	std::allocator<char> al;
	al.deallocate(nullptr, 4117);
}

C:\Temp>cl /EHsc /W4 /WX .\repro.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.23.28019.1 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

repro.cpp
Microsoft (R) Incremental Linker Version 14.23.28019.1
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:repro.exe
repro.obj

C:\Temp>.\repro.exe
Exception thrown: read access violation.
**_Ptr_user** was 0xFFFFFFFFFFFFFFFF.
```

**Expected behavior**
```
Debug Assertion Failed!

Expression: Pointer passed to deallocate() must be obtained from allocate() or allocate_at_least().
```

Or a similar message.

**STL version**
Microsoft Visual Studio Community 2022 (64-bit) - Preview
Version 17.1.0 Preview 1.1

**Comment by hannes-harnisch** [comment]
P.S.: This nullptr check must be of the form `if(_Count && !_Ptr)` as nullptr might be a valid value for the deallocate parameter, such as if it is obtained by a call to allocate with a size of zero. Therefore nullptr is only an invalid argument if the deallocation size is positive.

**Comment by StephanTLavavej** [comment]
Yep - @CaseyCarter notes that `deallocate` must handle all return values of `allocate`, so if `allocate(0)` can return `nullptr`, then `deallocate(nullptr, 0)` must work.

Additionally, the maintainers agree that adding a debug check for `nullptr` with non-zero element numbers is reasonable, given the cost of deallocation and the debugging headaches that this could avoid.

**Comment by AlexGuteniev** [comment]
Do you mean the check should be always present, rather than depending on `_DEBUG` or `_CONTAINER_DEBUG_LEVEL` ?

**Comment by AlexGuteniev** [comment]
This looks like a good first issue.

**Comment by CaseyCarter** [comment]
> Do you mean the check should be always present, rather than depending on `_DEBUG` or `_CONTAINER_DEBUG_LEVEL` ?

There are two related concerns here:
1. `allocate(0)` can return `nullptr`, so `deallocate(nullptr, 0)` must be valid.
2. The STL manually overaligns "large" allocations to help autovectorization by storing a pointer to the "real" beginning of the allocated lock in memory before the beginning of the aligned value it returns to the user. As a result, `deallocate(nullptr, large)` subtracts a bit from the `0` address to find that stored pointer and consequently AVs due to accessing an enormous memory address. We think users will find their bug quicker if the AV was the result of dereferencing `0`, or if we simply `_STL_ASSERT(meow != nullptr || size == 0, "You can't deallocate a bunch of memory at nullptr, bonehead!")`.

(1) needs to be addressed in all modes, (2) only in `_DEBUG`. `_CONTAINER_DEBUG_LEVEL` is really only for things that might result in silent misbehavior, which isn't the case here, so I think plain `_DEBUG` is fine. We may not need a check in all modes if (1) works today absent checking. I'm not sure if it does, but we want to make sure that (2) doesn't break it if so.

**Comment by AlexGuteniev** [comment]
I'm afraid of deliberately accessing null pointer. Clang is tricky and may optiomize it away or optimize it into another UB manifestation. I'm for `_STL_ASSERT`
