### ISSUE TITLE
<yvals_core.h>: "acknowledge this warning" vs. "suppress this deprecation"

### ISSUE THREAD

**Issue by CaseyCarter** [microsoft/STL#237]
In `<yvals_core.h>`, we define deprecation messages of the form "You can define MEOW to suppress this warning" and messages of the form "You can define MEOW to acknowledge this warning." The former form should be used consistently for all deprecation warnings, and the latter for all non-deprecation warnings.

**Comment by StephanTLavavej** [comment]
Various examples:

https://github.com/microsoft/STL/blob/d736fe46b950860a29d420da44da40c0df62b8cb/stl/inc/yvals_core.h#L501-L504

https://github.com/microsoft/STL/blob/d736fe46b950860a29d420da44da40c0df62b8cb/stl/inc/yvals_core.h#L515-L519

https://github.com/microsoft/STL/blob/d736fe46b950860a29d420da44da40c0df62b8cb/stl/inc/yvals_core.h#L712-L715

https://github.com/microsoft/STL/blob/d736fe46b950860a29d420da44da40c0df62b8cb/stl/inc/yvals_core.h#L788-L793

I really like "X is deprecated [...] You can define Y to acknowledge that you have received this warning." and not just because I wrote it. I believe that it discourages people from reacting with "yeah yeah, be quiet", because it says that defining the escape hatch is an (active) acknowledgement.

In contrast, telling people that they can suppress a deprecation makes it sound like doing so is cost-free - after you suppress it, you can get on with your life.

I would like to uniformly avoid saying "suppress".
