### ISSUE TITLE
memory_order about implementation of weak_ptr::lock

### ISSUE THREAD

**Issue by TousakaRin** [microsoft/STL#2413]
I recently tried to implement an atomic reference counter in C, so I referred to the implementation of std::shared_ptr in STL, and I am very confused about the implementation of weak_ptr::lock.
When executing compared_and_exchange,  clang specified memory_order_seq_cst,   g++ specified memory_order_acq_rel, and MSVC specified memory_order_relaxed. 
I think relaxed has been enough, since there is no data needed to synchronize if use_count is non-zero. 
I am not an expert in this area, can anyone provide some advice？

Following are code snippets:

[MSVC](https://github.com/microsoft/STL/blob/main/stl/inc/memory#L1084)
```
    bool _Incref_nz() noexcept { // increment use count if not zero, return true if successful
        auto& _Volatile_uses = reinterpret_cast<volatile long&>(_Uses);
#ifdef _M_CEE_PURE
        long _Count = *_Atomic_address_as<const long>(&_Volatile_uses);
#else
        long _Count = __iso_volatile_load32(reinterpret_cast<volatile int*>(&_Volatile_uses));
#endif
        while (_Count != 0) {
            const long _Old_value = _INTRIN_RELAXED(_InterlockedCompareExchange)(&_Volatile_uses, _Count + 1, _Count);
            if (_Old_value == _Count) {
                return true;
            }

            _Count = _Old_value;
        }

        return false;
    }
```

[clang/libcxx](https://github.com/llvm/llvm-project/blob/main/libcxx/src/memory.cpp#L119)
```
__shared_weak_count*
__shared_weak_count::lock() noexcept
{
    long object_owners = __libcpp_atomic_load(&__shared_owners_);
    while (object_owners != -1)
    {
        if (__libcpp_atomic_compare_exchange(&__shared_owners_,
                                             &object_owners,
                                             object_owners+1))
            return this;
    }
    return nullptr;
}
```

[gcc/libstdc++](https://github.com/gcc-mirror/gcc/blob/master/libstdc%2B%2B-v3/include/bits/shared_ptr_base.h#L277)
```
 template<>
    inline bool
    _Sp_counted_base<_S_atomic>::
    _M_add_ref_lock_nothrow() noexcept
    {
      // Perform lock-free add-if-not-zero operation.
      _Atomic_word __count = _M_get_use_count();
      do
	{
	  if (__count == 0)
	    return false;
	  // Replace the current counter value with the old value + 1, as
	  // long as it's not changed meanwhile.
	}
      while (!__atomic_compare_exchange_n(&_M_use_count, &__count, __count + 1,
					  true, __ATOMIC_ACQ_REL,
					  __ATOMIC_RELAXED));
      return true;
    }
```

**Comment by StephanTLavavej** [comment]
We believe that relaxed ordering for "incref if nonzero" is correct, because this operation has no side effects that could be harmed by code being reordered above or below the operation. (If the refcount is zero, it remains unchanged; if the refcount is nonzero, it increases, but that doesn't result in any objects being destroyed or memory being deallocated.)

We believe that the critical operation to protect is the decref, which needs acquire-release ordering, because it "communicates with itself".

https://github.com/microsoft/STL/blob/2f9f567ffe1087353ecacc5a03f81c395a1922e1/stl/inc/memory#L1103-L1108
https://github.com/microsoft/STL/blob/2f9f567ffe1087353ecacc5a03f81c395a1922e1/stl/inc/xatomic.h#L51
