### ISSUE TITLE
Sporadic failure of P0645R10_text_formatting_formatting

### ISSUE THREAD

**Issue by AlexGuteniev** [microsoft/STL#2449]
This run:
https://dev.azure.com/vclibs/STL/_build/results?buildId=9974&view=logs&j=e5928d94-6045-5a4b-1479-6369daf1c6e1&t=e774f207-3822-5f8e-5e8b-2cdb9d7ebe0b

The subsequent run succeeded, though the change between the runs was in unrelated area, and except of one variable un-shadowing that does not affect anything, it was whitespace/comments change: https://github.com/microsoft/STL/pull/2447/commits/2b43c89aae41bdb185864669590ce86586d3bf9d

**Comment by StephanTLavavej** [comment]
The error was:

```
Assertion failed: format("{:.2000a}", 1.0) == expected, file C:\a\1\s\tests\std\tests\P0645R10_text_formatting_formatting\test.cpp, line 836
```

I don't understand what happened here. Perhaps we should update the test with additional logging, to print the result of `format()` when it's unexpected here?

**Comment by StephanTLavavej** [comment]
Happened again in: https://dev.azure.com/vclibs/STL/_build/results?buildId=10119&view=ms.vss-test-web.build-test-results-tab&runId=1184952&resultId=102554&paneView=debug

**Comment by StephanTLavavej** [comment]
#2494 fortunately printed the actual string before the expected string (the latter was lost due to log truncation, #2557), @statementreply in https://github.com/microsoft/STL/pull/2499#issuecomment-1038078938 noticed what was wrong with that string indicating a bug in the "huge precision, clamp it and then append zeros later" codepath, I was able to repro it locally and find the root cause in
https://github.com/microsoft/STL/blob/afe0800cd6bf0d163bf678ad4e1feb3c130d1ec5/stl/inc/format#L2510-L2546
where `while (*_Exponent_start != _Exponent)` initially reads `_Result.ptr` (this is past-the-end of what `to_chars()` wrote), and @barcharcraz has a fix. :tada:

This sporadically failed because the garbage character being read is almost always not the exponent character (`'p'` for `hex`, `'e'` for `scientific`), but if it is, the code gets confused about where the exponent starts, leading to catastrophe shortly afterwards.
