### ISSUE TITLE
`<iterator>`: `std::distance` result should be discardable

### ISSUE THREAD

**Issue by fsb4000** [microsoft/STL#2521]
**Describe the bug**
The following code, to skip all pending short numbers in the input stream, triggers warning C4834.

This warning is unsubstantiated, as the [istream_iterator](https://docs.microsoft.com/en-us/cpp/standard-library/istream-iterator-class) has important side effects.

Workaround: cast the result to (void).

**Command-line test case**
```
C:\Temp>type main.cpp
#include <iterator>
#include <iostream>
typedef std::istream_iterator < short, char > input_short;
void skip_shorts() {
	distance(input_short(std::cin), input_short());
}

C:\Temp>cl /EHsc /W4 /WX /c main.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.31.31104 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

main.cpp
main.cpp(5): error C2220: the following warning is treated as an error
main.cpp(5): warning C4834: discarding return value of function with 'nodiscard' attribute
```

**Expected behavior**
The code should compile without warnings.

**STL version**
    Microsoft Visual Studio Community 2022 Preview
    Version 17.1.0 Preview 5.0
    
**Additional context**
the bug report was copied from DevCom-1654844

**Comment by miscco** [comment]
Imho that is exactly one of those cases where casting to video and adding a comment is appropriate

**Comment by fsb4000** [comment]
@miscco , Personally, I like the nodiscard warning too :)

But I decided to copy the bug report as it is related to the repo.

**Comment by AdamBucior** [comment]
I think this example abuses `distance`. IMO `nodiscard` should stay.

**Comment by miscco** [comment]
Yeah, it is the prime example of "I have broken code, but rather than fixing it or adding a sing localized workaround, I want the whole ecosystem pay the cost for my laziness"

**Comment by CaseyCarter** [comment]
I have a deep, abiding, _passionate_ hatred for false positives - I'm the 1 in 10 who thinks `unique_ptr.release()` shouldn't be `[[nodiscard]]`. I nevertheless find this report hard to agree with.

**Comment by frederick-vs-ja** [comment]
Eliminating the false positives seems not trivial.

We have no native "conditional `[[nodiscard]]`", although we can use SFINAE to separate `std::distance` into different overloads, and at least mark theoretically pure ones (overloads for forward or better iterators) `[[nodiscard]]`.
However, not all input iterators have the "consuming increment" semantics. A special tag may be needed to indicate such semantics, and iterator/range adaptors should propagate the tag.

**Comment by StephanTLavavej** [comment]
We talked about this at the weekly maintainer meeting and concluded that this is by design - the example is sufficiently unusual and adding a `(void)` cast is a reasonably non-intrusive way to both suppress the warning in a targeted manner, and to mark that this code is intentionally doing something unusual. (The contrast with `unique_ptr::release()` is also illuminating - in those scenarios, `release()` is the only way to get a `unique_ptr` to relinquish ownership without deleting, so users who have structured their code to have an ownership guarantee aren't doing something *unusual* by calling `release()`. Here, calling `distance()` for its side effects is not forced - the same behavior could be achieved with a bit more code and a manual loop.)
