### ISSUE TITLE
P0627R6 `unreachable()`

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#2531]
[P0627R6](https://wg21.link/P0627R6) `unreachable()`

Feature-test macro:
```cpp
#define __cpp_lib_unreachable 202202L // need to confirm official value
```

**Comment by fredemmott** [comment]
FYI, a compiler issue means that `__assume(false)` is still preferable over `std::unreachable()` in codebases with non-default warnings enabled due to C4702 - "unreachable code" - understanding `__assume(false)` but not `std::unreachable()`. Not filing an issue here as it's not an STL bug, but felt worth mentioning.

https://developercommunity.visualstudio.com/t/std::unreachable-causes-warning-4702-un/10720390
