### ISSUE TITLE
LWG-3657 `std::hash<std::filesystem::path>` is not enabled

### ISSUE THREAD

**Issue by CaseyCarter** [microsoft/STL#2556]
LWG-3657 `std::hash<std::filesystem::path>` is not enabled

**Comment by crackedmind** [comment]
If you didn't mind i started implementation.

**Comment by frederick-vs-ja** [comment]
I believe this is a DR against C++17 and hence needs to be work under C++17, and member typedefs `result_type`/`argument_type` should be kept but deprecated in C++17 mode, like this.

```C++
template <>
struct hash<filesystem::path> {
    _CXX17_DEPRECATE_ADAPTOR_TYPEDEFS typedef filesystem::path _ARGUMENT_TYPE_NAME;
    _CXX17_DEPRECATE_ADAPTOR_TYPEDEFS typedef size_t _RESULT_TYPE_NAME;
    _NODISCARD size_t operator()(const filesystem::path& _Path) const noexcept {
        return _STD filesystem::hash_value(_Path);
    }
};
```

This issue was submitted by me, and I was going to implement the resolution myself. But I'm just a bit too busy to implement it as soon as possible. @crackedmind I'll be very glad if you start implement it now.

**Comment by frederick-vs-ja** [comment]
@crackedmind Oh... I finally decide to implement it myself. Thanks for looking into this issue!

**Comment by jdoubleu** [comment]
Unfortunately, this didn't make it into Visual Studio 16.11 2019, yet: https://godbolt.org/z/6rMTedqMj

**Comment by frederick-vs-ja** [comment]
> Unfortunately, this didn't make it into Visual Studio 16.11 2019, yet: https://godbolt.org/z/6rMTedqMj

I once wished every DR or bug fix for C++20 and former modes would be backported. But the STL team seemly decided only to backport `ranges`- and `chrono`-related ones.

**Comment by jdoubleu** [comment]
Well, I just noticed, that it's working with `/std:c++17` but not `/std:c++20` (for VS 16.11). 

So it's not an issue of backporting the fix, but also enabling it for C++20 mode in VS 16.11.
