### ISSUE TITLE
`<system_error>`: `WAIT_TIMEOUT` is not matched against by `std::errc::timed_out`

### ISSUE THREAD

**Issue by DaanDeMeyer** [microsoft/STL#2572]
**Describe the bug**

If we look at https://github.com/microsoft/STL/blob/afe0800cd6bf0d163bf678ad4e1feb3c130d1ec5/stl/src/syserror.cpp#L104, we can see that errc::timed_out only matches against WSAETIMEDOUT and not against WAIT_TIMEOUT which is another common error code to indicate a timeout on Windows.

**Command-line test case**

repro.cpp

```
std::errc::timed_out == std::error_code { WAIT_TIMEOUT, std::system_category() };     // false
std::errc::timed_out == std::error_code { WAIT_TIMEOUT, std::generic_category() };     // false

std::make_error_condition(std::errc::timed_out) == std::error_code { WAIT_TIMEOUT, std::system_category() };     // false
std::make_error_condition(std::errc::timed_out) == std::error_code { WAIT_TIMEOUT, std::generic_category() };     // false
```

**Expected behavior**

`std::errc::timed_out` matches against WAIT_TIMEOUT when stored with the system category in an error code.

**STL version**

Latest commit on the main branch exhibits this behavior.

**Comment by StephanTLavavej** [comment]
I agree that this would be entirely reasonable to add, as the table is already a many-to-one mapping. Marking this as `affects redist` because this would change the behavior of the STL's separately compiled DLL; right now we're avoiding changing the redist due to the new [VC Redist Lockdown](https://github.com/microsoft/STL/wiki/Changelog#vc-redist-lockdown) policy. We're planning to add internal test coverage for the locked-down redist in the near future; after that happens, we'll be able to accept *limited* changes that affect redist behavior without synchronized changes to the headers. Resolving this issue will merely add an entry to the lookup table but not require any header changes, so it'll be safe to merge at that time.

**Comment by AlexGuteniev** [comment]
Seems that `ERROR_TIMEOUT` and possibly `ERROR_SEM_TIMEOUT` are also suitable.
