### ISSUE TITLE
<memory>: weak_ptr's converting constructors could sometimes avoid locking

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#258]
`weak_ptr`'s converting copy/move constructors have a subtle bit of code:

https://github.com/microsoft/STL/blob/d0d724fb916c59f1c4f2830330ed967a72d2d2b8/stl/inc/memory#L1622-L1625

https://github.com/microsoft/STL/blob/d0d724fb916c59f1c4f2830330ed967a72d2d2b8/stl/inc/memory#L1631-L1635

They `lock()` to get a (possibly empty) `shared_ptr` before performing the converting construction. This means that we're paying an expensive "increment refcount if nonzero" and a decrement.

We're doing this for a real reason (not commented in the source code, but covered by tests). These ctors are performing a raw pointer conversion from `Y *` to `T *`. That might perform a pointer adjustment to traverse an inheritance hierarchy. But because this is `weak_ptr`, the pointed-to object might have expired. Usually that doesn't matter - the offset for the pointer adjustment is known statically. But for **virtual inheritance**, the offset depends on the most derived type, and that requires the object to be alive! (The wording for the Core Language says this in a more obscure way.) So we lock to ensure that either the object remains alive during the conversion, or it's expired and we'll get an empty `weak_ptr`.

That's great, except that it's too aggressive. It locks when converting from `X *` to `const X *` which never requires a pointer adjustment (and is easy to detect). It also locks when the conversion doesn't involve a virtual base, but I don't know whether we can detect that via type traits (and it's unlikely to matter in practice).

Now that we have `if constexpr`, we could easily optimize this.

**Comment by cpplearner** [comment]
Since a pointer to virtual base cannot be cast to pointer to derived type, it seems to be possible to check whether type `Y` is a virtual base of type `T` by testing whether `(T*)(Y*)nullptr` is a valid expression. This technique is used by [`boost::is_virtual_base_of`](https://github.com/boostorg/type_traits/blob/master/include/boost/type_traits/is_virtual_base_of.hpp).

**Comment by CaseyCarter** [comment]
> Since a pointer to virtual base cannot be cast to pointer to derived type, it seems to be possible to check whether type `Y` is a virtual base of type `T` by testing whether `(T*)(Y*)nullptr` is a valid expression. This technique is used by [`boost::is_virtual_base_of`](https://github.com/boostorg/type_traits/blob/master/include/boost/type_traits/is_virtual_base_of.hpp).

Very nice! From [expr.static.cast]/2: "If `B` is a virtual base class of `D` or a base class of a virtual base class of `D`, or if no valid standard conversion from “pointer to `D`” to “pointer to `B`” exists ([[conv.ptr]](http://eel.is/c++draft/conv.ptr)), the program is ill-formed." And we can use `static_cast`s directly - rather than C-style casts - because we don't need to punch through accessibility as does `boost::is_virtual_base_of`.

**Comment by AlexGuteniev** [comment]
> This technique is used by [`boost::is_virtual_base_of`](https://github.com/boostorg/type_traits/blob/master/include/boost/type_traits/is_virtual_base_of.hpp).

This is black magic. Can we just request an intrinsic `__is_virtual_base_of` instead?
