### ISSUE TITLE
`<iterator>`: `std::contiguous_iterator<const volatile int*> == false` because of `volatile`?

### ISSUE THREAD

**Issue by pc125** [microsoft/STL#2581]
`static_assert(std::contiguous_iterator<const volatile int*>)` fails with this STL, while it works with lib(std)c++. Without the `volatile` it works everywhere. Who is correct?
I can't see why a pointer to `volatile` data shouldn't be a valid iterator.

**Comment by miscco** [comment]
This is a known issue with MSVCs handling of the ternary operator https://developercommunity.visualstudio.com/t/conditional-operator-errors/876860

**Comment by frederick-vs-ja** [comment]
I think this bug happens in the following case:
When `I` is a cv-unqualified arithmetic or enumeration type, `LRef` is _`cv`_`I&`, `RRef` is _`cv`_`I&&` except for `I&&`, MSVC erroneously computes `decltype(false ? std::declval<LRef>(), std::declval<RRef>())` as `I&`, while the right result is `I`.

`std::contiguous_iterator<const volatile int*>` eventually tests `std::common_reference_t<const volatile int&&, const int&>` (which is `int` if correctly computed; but MSVC answers `int&`), and requires that both `const volatile int&&` and `const int&` can be converted to that type. Although the implementation of `std::common_reference_t` in uses something similar (`_Returns_exactly` in MSVC STL) rather than `std::declval`.

I guess workaround is available.
