### ISSUE TITLE
`<complex>`: `exp()` on a `complex` returns wrong sign

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#2617]
Originally reported as DevCom-1674503 and internal VSO-1488519 / AB#1488519 as a regression between VS 2022 17.0 and 17.1:

```
C:\Temp>type meow.cpp
```
```cpp
#include <cfloat>
#include <complex>
#include <iostream>
using namespace std;

int main() {
    cout << "                      Expected for all: (inf,inf)" << endl;
    cout << "       exp(complex<float>(1000, 1000)): " << exp(complex<float>(1000, 1000)) << endl;
    cout << " exp(complex<float>(FLT_MAX, FLT_MAX)): " << exp(complex<float>(FLT_MAX, FLT_MAX)) << endl;
    cout << "      exp(complex<double>(1000, 1000)): " << exp(complex<double>(1000, 1000)) << endl;
    cout << "exp(complex<double>(DBL_MAX, DBL_MAX)): " << exp(complex<double>(DBL_MAX, DBL_MAX)) << endl;
}
```
```
C:\Temp>cl /EHsc /nologo /W4 /MTd meow.cpp && meow
meow.cpp
                      Expected for all: (inf,inf)
       exp(complex<float>(1000, 1000)): (inf,inf)
 exp(complex<float>(FLT_MAX, FLT_MAX)): (inf,-inf)
      exp(complex<double>(1000, 1000)): (inf,inf)
exp(complex<double>(DBL_MAX, DBL_MAX)): (-inf,inf)
```

I observe that our new behavior now **matches** GCC 11.2's, see: https://godbolt.org/z/Mrsrf3K3x

I believe that this is due to #1584. While the user expected our old behavior of `(inf,inf)`, our new behavior may be correct - I'm not sure.

**Comment by muellerj2** [comment]
I think the new behavior is correct.

The output of the exponential function for complex number `x + iy` is defined as `exp(x)*(cos(y)+isin(y))`. That is, the signs are generally determined by the imaginary part only, and importantly the signs keep oscillating (with period 2pi) even for huge imaginary parts.

In the given test cases, the situation is as follows according to my analysis:
* FLT_MAX is `(2 − 2^−23) * 2^127` and the remainder of dividing it by 2pi seems to be about 5.73. `cos(5.73)` is about 0.85 and `sin(5.73)` is about -0.52, so the real part has positive and the imaginary part negative sign. Thus, the result `(inf, -inf)` appears correct to me.
* DBL_MAX is `(2 − 2^-52) × 2^1023` and the remainder modulo 2pi is about 3.13. Since this number is a bit less than pi, `cos(3.13)` is about -1, and `sin(3.13)` is slightly greater than 0. Thus, the real part has negative and the imaginary part positive sign, and the result `(-inf, inf)` appears correct.

**Comment by CaseyCarter** [comment]
Thanks @muellerj2 for the analysis, which I also agree is correct. Our results for the program in the OP are consistent with both libstdc++ and libc++ (https://godbolt.org/z/66c19WTc4). This change in our behavior is clearly bugfix and not a regression.
