### ISSUE TITLE
Add `WARN` status to test runner

### ISSUE THREAD

**Issue by CaseyCarter** [microsoft/STL#2625]
(See https://github.com/microsoft/STL/pull/2621#discussion_r837974929.) Ideally, we could tag tests as `WARN` to indicate that the test passes when run normally (with the headers found via `INCLUDE`), but fails with warning-promoted-to-error when run non-system headers found via `/I`.

**Comment by StephanTLavavej** [comment]
We talked about this at the weekly maintainer meeting and concluded that this isn't worth spending time on. Only a couple of tests were ever affected in this way (and they may have been changed due to later libcxx updates; haven't checked). We already have a lot of custom logic on top of LLVM lit that has been expensive to keep maintained; we should try to have less of it over time, not more.
