### ISSUE TITLE
`<algorithm>`: Should we furtherly move some algorithms elsewhere?

### ISSUE THREAD

**Issue by frederick-vs-ja** [microsoft/STL#2642]
`<algorithm>` is inherently a huge header and its size has dramatically bloated in C++20. So IMO we should avoid including it as a whole in other headers.

Currently MSVC STL places several common algorithms into `<xutility>` etc., and provides parallel algorithms in `<execution>`. However, there are still some headers directly including `<algorithm>`, because:
- `<filesystem>` needs `find_if_not`, `mismatch`, `replace`, `replace_copy`, `replace_copy_if`;
- `<queue>` needs `make_heap`, `pop_heap`, `push_heap`;
- `<regex>` needs `mismatch`;
- `<random>` needs `lower_bound`;
- `<chrono>` needs `upper_bound`.

It seems that `find_if_not` and `mismatch` should be moved to `<xutility>` (as the `ranges::` variants are already there). Should we create one or more internal header to place other mentioned algorithms?

**Comment by AlexGuteniev** [comment]
A counter argument could be that many users that intensely use the STL would include `<algorithm>` anyway. And that we will ne using modules soon. Still these are towards "not very useful", but not "harmful".

**Comment by StephanTLavavej** [comment]
This is an interesting question. Moving machinery to `<xutility>` can be nearly a pure win if the machinery is very small - but the larger it is, the more costs we're asking the majority of the STL to pay. Adding new internal headers isn't especially costly (there are some costs - it makes building Standard Library Header Units take longer) and doesn't really create maintenance burdens, although I don't think we'd want to pursue a strategy of "one internal header per algorithm".

Mostly, I wonder whether it's worth it when the headers in question are already very large:

* `<filesystem>` drags in a ton of machinery besides `<algorithm>`: https://github.com/microsoft/STL/blob/52505b9d3249c50b33eb22152a1f18f208ea2959/stl/inc/filesystem#L15-L31
* `<queue>` is probably the best candidate since it is otherwise very small: https://github.com/microsoft/STL/blob/52505b9d3249c50b33eb22152a1f18f208ea2959/stl/inc/queue#L11-L13
* `<regex>` has a moderate amount of dependencies (in addition to being inherently moderate-large): https://github.com/microsoft/STL/blob/52505b9d3249c50b33eb22152a1f18f208ea2959/stl/inc/regex#L12-L28
* For `<random>`, `lower_bound()` is already in `<xutility>`, so I think we can already try dropping `<algorithm>`: https://github.com/microsoft/STL/blob/52505b9d3249c50b33eb22152a1f18f208ea2959/stl/inc/xutility#L6073-L6099
* `<chrono>` has a ton of dependencies (if the full C++20 version is included, instead of the new `<__msvc_chrono.hpp>`), but `upper_bound()` is lightweight and extremely similar to `lower_bound()`: https://github.com/microsoft/STL/blob/52505b9d3249c50b33eb22152a1f18f208ea2959/stl/inc/chrono#L11-L37

Haven't talked about this at the maintainer meeting yet, but my personal recommendations would be:

* `<random>`: Attempt to remove `<algorithm>` now.
* `<chrono>`: Move `upper_bound()` to `<xutility>`.
* `<filesystem>`, `<regex>`, `<queue>`: Explore adding a single internal header for these algorithms (I think there would be severely diminishing returns if we added three internal headers), and see how much it affects (A) preprocessed size, (B) compiler memory consumption as reported by `/d1reportMemorySummary`:

```
C:\Temp>type meow.cpp
```
```cpp
#ifdef INCLUDE_ALGORITHM
#include <algorithm>
#endif
#include <iostream>
int main() {
    std::cout << "Hello, world!\n";
}
```
```
C:\Temp>cl /EHsc /nologo /W4 /std:c++latest /c /d1reportMemorySummary meow.cpp
meow.cpp
Persistent heap 1 size: 55377352
Persistent heap 2 size: 4072824
Peak working set size: 76873728

C:\Temp>cl /EHsc /nologo /W4 /std:c++latest /c /d1reportMemorySummary /DINCLUDE_ALGORITHM meow.cpp
meow.cpp
Persistent heap 1 size: 67134184
Persistent heap 2 size: 3922760
Peak working set size: 88543232
```

Here, the totally unnecessary include of `<algorithm>` increases peak working set size by 15.2%.

**Comment by StephanTLavavej** [comment]
Thanks again for the suggestion. After talking about this at the weekly maintainer meeting, we believe that while further throughput improvements could be made here, we don't expect that they would have effects dramatic enough to justify the time needed for reviewing and the larger amount of time needed to investigate/report/fix projects that are broken by dragging in fewer algorithms (as we validate a large number of open-source projects, in addition to Windows).

@barcharcraz notes that due to how templates work (especially in the older permissive mode), there can be "stealth build breaks" in a third-party library that are only observed when a programmer-user instantiates those third-party templates. Again, this isn't a reason to avoid all such refactorings, they just need to have corresponding benefits.
