### ISSUE TITLE
STL: `std::iter_swap` can be inlined into callers

### ISSUE THREAD

**Issue by CaseyCarter** [microsoft/STL#2692]
After merging P0551R3 "Thou Shalt Not Specialize std Function Templates!" users are now forbidden to explicitly specialize `std::iter_swap`. Consequently, we can expand calls inline into callsites for a bit of throughput and improved debug codegen / UX under as-if. Should the expansion be `_Swap_adl(*a, *b);`, or should we inline that as well and use `swap(*a, *b); // intentional ADL`? `_Swap_adl` is conventional, but perhaps its time to update that convention for another tiny bit of throughput?

We should see what other maintainers think about inlining `_Swap_adl` before wasting any effort on doing so - I'll label this [decision needed] for now.

**Comment by frederick-vs-ja** [comment]
I think we can do this even without the strengthened requirement in P0551R3.

The old wording said...

N4140 [namespace.std]/1:
> A program may add a template specialization for any standard library template to namespace `std` only if the declaration depends on a user-defined type and the specialization meets the standard library requirements for the original template and is not explicitly prohibited.

N4140 [alg.swap]/5:
> _Effects:_ `swap(*a, *b)`.

According to the old wording, IIUC the previously allowed program-defined specializations of `std::iter_swap` were already disallowed to do something inequivalent.

**Comment by StephanTLavavej** [comment]
We talked about this at the weekly maintainer meeting, and everyone likes `swap(*a, *b); // intentional ADL`. (Let's make sure to consistently comment this - also IIRC there is at least one uncommented occurrence already somewhere in the STL.)

Rationale: This probably doesn't matter a whole bunch for throughput (either compile time or object file size) since the number of swap calls is fairly low, but it will improve the debugging experience to have to step through only one swap function instead of 2 extra layers.
