### ISSUE TITLE
Improve parameter naming to be more user friendly (with IDE inlay parameter hints)

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/STL#2813]
The VS 2022 and VS Code C/C++ editors have both added inlay parameter hints to help users with parameter, but the STL library could have better parameter names without "_" and better named (e.g. "Offset" instead of "Off") to give a better user experience to users of the library.

![image](https://user-images.githubusercontent.com/19859882/174901519-b0f137bf-1cdc-4b91-81e5-4353a1577932.png)

**Comment by CaseyCarter** [comment]
There's nothing we can do about the ugly `_Capital` style: we have to use identifiers in the space reserved for implementors since users are allowed to `#define` general identifiers like `Offset`. We could use more completely-documenting parameter names like `_Offset` instead of `_Off`, but I'm not enthusiastic about (1) lengthening identifiers, which reduces code density, (2) spending lots of time reviewing cosmetic changes that rename parameters, or (3) mixing documentation into code in general.

Other folks: feel free to express your thoughts and opinions here, we'll take it into consideration and discuss this issue at the weekly implementer meeting.

**Comment by sean-mcmanus** [comment]
Okay -- our language provider is considering auto-removing the leading underscores for inlay parameter hints (or having a setting to enable that): https://github.com/microsoft/vscode-cpptools/issues/9485 .

I don't fully understand points 1-3 though.

**Comment by StephanTLavavej** [comment]
I agree with @CaseyCarter's points:

1. The STL implementation is primarily read by STL implementers, and verbose names do have a cost, especially when they're repeated. For example, here we mention `_Off` twice: https://github.com/microsoft/STL/blob/7f04137880e1c3df5125c1baf808f16f399dee2e/stl/inc/deque#L310-L317
This expression is already hard to read because of `_Mycont->_Myoff` and `this->_Myoff` being lengthy (and different!). Saying "offset" instead of "off" would just make such lines even longer.
   + This is the same rationale for iterating with `i` instead of `index` or `index_into_vector`. When a variable has a simple purpose (and especially a small scope), it can have a short name. Complicated variables with larger scopes typically deserve larger names.
     * In many cases we would use `i`, `n`, `T`, etc. if we could, but our ugliness requirements/conventions require at least `_Ix`, `_Nx`, `_Ty`, etc.
   + Of course, there are limits. We recently expanded some names saying "cor" to say "correction", since that was a previously unknown abbreviation in the STL.
   + There is a bonus consideration here - the STL in particular is an internationally Standardized library with excellent documentation (Microsoft Docs, cppreference, books). Thus it is less important for the STL's source code to provide "parameter help" than for any other library.
2. We are busy. Reviewing renames would indeed be time-consuming for low value compared to all of the other work that we need to do.
   + We do perform a reasonable number of code cleanups over time, but they are generally not just variable renames.
3. Bloating code as viewed in the editor with interleaved documentation is something that I am extremely strongly opposed to. ConcRT/PPL code did this with large XML comments and it makes that code incredibly difficult to read and understand.
   + We do have large comments in the STL's headers, but only on rare occasions, when we need to document something that is far from obvious, even after assuming knowledge of the Standard.
   + The STL's sources (which are older and are generally worse at following our preferred conventions) do contain a few bloaty comments, e.g. `_toupper.cpp` - we should deal with that someday.

I would not be opposed to a small number of targeted renames for parameters that have unusually confusing names, but I don't think that a large-scale rename project would be a valuable use of time.

**Comment by Colengms** [comment]
I think the issue is that this new 'inlay hints' feature results in a large number of people seeing these argument names, in their face, throughout their own code bases.  Making STL parameter names more readable would essentially make a whole lot of peoples' code more readable.

**Comment by AlexGuteniev** [comment]
I'm not sure if the number of feature users is large. Personally I find it more distracting than helpful. After unintentionally truning the feature on few times, I just disabled it.

**Comment by AlexGuteniev** [comment]
If this is indeed very useful for some users, I would suggest attribute like: `[[msvc::param_hint(value, count)]]`

**Comment by MikeGitb** [comment]
Personally I like the feature when dealing with multi parameter functions. Of course I can just open e.g. cppreference.com if I'm unsure, but that's much more effort (and mental Kontext switch) than just hitting the hotkey to activate the inlay hints (I don't have it on by default). 

Obviously the STL can't de-uglify the parameter names, but as suggested, that could be automatically be done by the tool. W.r.t. using longer parameter names, I find it hard to believe  that in the specific example of _Off vs. _Offset, the additional three letters would harm readability in the STL code, but of course there are probably more problematic examples.  However, the way that the inline hints are currently displayed,  I find longer parameter names are a much bigger problem on the calling site anyway, so I happen to prefer short names too.

**Comment by StephanTLavavej** [comment]
We talked about this at the weekly maintainer meeting. We recommend the view-transformation of removing underscores from `_Ugly` and `__ugly` names, but we don't plan to undergo a large-scale audit of our parameter names. We remain willing to consider individual renamings for especially incomprehensible names..
