### ISSUE TITLE
Can one mix code code compiled with /std:c++17 and /std:c++20 in the same binary

### ISSUE THREAD

**Issue by AndrewJD79** [microsoft/STL#2887]
Hi,

Is it safe to link code two object files which havily use MSSTL into single binary? One object file is compiled with  /std:c++17 and second one with /std:c++20. Does such usage break ODR?

Thank you.

**Comment by fsb4000** [comment]
> Is it safe to link code two object files which havily use MSSTL into single binary? One object file is compiled with /std:c++17 and second one with /std:c++20

I believe this is safe.
You can't link Release and Debug object files but different standards should be fine.

**Comment by StephanTLavavej** [comment]
Correct - we support mixing-and-matching Standard modes, and this is ABI-safe. This is usually achieved "for free" because new Standard modes just enable (or rarely, remove) machinery like classes and functions - and mixing "nonexistent" with "existent" is totally fine. In a few cases, the Standard mode affects the definition of existing machinery, like changing the return type of `vector<T>::emplace_back()` from `void` to `T&`, but this doesn't pose ABI problems.

However, it is important to note that this compatibility guarantee extends only to the compiler and STL. Third-party libraries could introduce ABI-mismatch problems (e.g. by conditionally changing typedefs, base classes, or data member layout depending on the Standard mode). As long as third-party libraries don't do that, they will generally be automatically compatible across Standard modes just like the STL.
