### ISSUE TITLE
P0655R1 visit<R>()

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#31]
[P0655R1](https://wg21.link/P0655R1) `visit<R>()`

**Comment by NathanSWard** [comment]
I was looking through this paper and the implementation of `std::variant` and initially assumed that you could simply implement it via the following:
```
template<class _Ret, class _Callable, class... _Variants, class = void_t<_As_variant<_Variants>...>>
constexpr _Ret visit(_Callable&& _Obj, _Variants&&... _Args) {
    // same boiler plate as current visit implementation

    return static_cast<_Ret>(_Visit_strategy<_Strategy>::template _Visit<_ListOfIndexVectors>(
        _Variant_visit_index1(0, static_cast<_As_variant<_Variants>&>(_Args)...), static_cast<_Callable&&>(_Obj),
        static_cast<_As_variant<_Variants>&&>(_Args)...));
}
```
However, I presume that this doesn't quite fit the bill (or does it)?
In the case where simply `static_cast()`ing the return type to the desired return type doesn't function as intended, in order to implement this, I'll have to directly change the current `_Visit_strategy::_Visit()` function. My best guess would be to rely on the provided return type rather than the `_Variant_visit_result_t`.

If this issue is open to tackle, and my comments appear to be leading my down the right track, I'd like to implement this, if possible.

**Comment by CaseyCarter** [comment]
There are a couple of wrinkles:
* The conversion to the result type must be implicit rather than explicit per the definition of `INVOKE<R>` in [[func.require]/2](http://eel.is/c++draft/func.require#2) when the result type is not cv-`void`.
* The conversion to the result type will need to happen "deeper" in the visitation machinery than directly in `visit<R>` itself since otherwise the lower-level functions won't compile since e.g. `std::visit<double>(std::variant<int, double, float>(3.14), std::identity)` will produce a function that wants to return three different types.

I *think* what we want to do is pass the desired result type into the lower-level machinery from both `visit` and `visit<R>`, and "lower-level machinery" will need to detect when the desired result type `is_void` and behave appropriately.

**Comment by NathanSWard** [comment]
@CaseyCarter that makes sense!

In this case, would something of the sorts work?

This could be done by having `_Visit_strategy::_Visit()` taking another template parameter, and then using SFINAE with two `_Visit()` overloads which check's a if the new template type is a certain tag type.

For example:
```
struct _Visit_implicit_return_tag {}

template <>
struct _Visit_strategy<1> {
    template <class _Ret, class, class _Callable, enable_if_t<is_same_v<_Ret_tag, _Variant_implicit_return_tag>, int> = 0>
    static constexpr _Variant_visit_result_t<_Callable> _Visit(
        //...
    }

    template <class _Ret, class, class _Callable, enable_if_t<!is_same_v<_Ret_tag, _Variant_implicit_return_tag>, int> = 0>
    static constexpr _Ret _Visit(
        //...
    }
};
```
`std::visit` without provided return type
```
template<class _Callable, class... _Variants, class = void_t<_As_variant<_Variants>...>>
constexpr _Variant_visit_result_t<_Callable, _As_variant<_Variants>...> visit(_Callable&& _Obj, _Variants&&... _Args) {
    // boiler plate

    return _Visit_strategy<_Strategy>::template _Visit<_Visit_implicit_return_tag, _ListOfIndexVectors>(
        _Variant_visit_index1(0, static_cast<_As_variant<_Variants>&>(_Args)...), static_cast<_Callable&&>(_Obj),
        static_cast<_As_variant<_Variants>&&>(_Args)...);
```

`std::visit` with provided return type
```
template<class _Ret, class _Callable, class... _Variants, class = void_t<_As_variant<_Variants>...>>
constexpr _Ret visit(_Callable&& _Obj, _Variants&&... _Args) {
    // boiler plate

    return _Visit_strategy<_Strategy>::template _Visit<_Ret, _ListOfIndexVectors>(
        _Variant_visit_index1(0, static_cast<_As_variant<_Variants>&>(_Args)...), static_cast<_Callable&&>(_Obj),
        static_cast<_As_variant<_Variants>&&>(_Args)...);
```

**Comment by CaseyCarter** [comment]
> In this case, would something of the sorts work?

I think the non-`<R>` overload of `visit` should simply pass `_Variant_visit_result_t<_Callable>` in the place where the `<R>` overload would pass `R`. The significant difference to the lower layers seems to be whether they should implicitly convert to the result type or explicitly convert to `void`; the distinction of whether the result type was user-provided or calculated seems immaterial.

**Comment by NathanSWard** [comment]
> I think the non-<R> overload of visit should simply pass `_Variant_visit_result_t<_Callable>`

That is a much cleaner solution, thanks!

Just to make sure we're on the same page it would work something like this:
```
template<class R, class Callable, class... Variants>
constexpr R visit( /* params */ ) {
    // relay the return type further down in the machinery
}

template<class Callable, class... Variants>
constexpr _Variant_visit_result_t<Callable, Variants...> visit( /* params */ ) {
    return visit<_Variant_visit_result_t<Callable, Variants...> visit(/* forward params */);
}
```

**Comment by CaseyCarter** [comment]
> Just to make sure we're on the same page it would work something like this:

Yes, in the sense that both would use the same lower-level machinery, but I would probably "inline" the call to `visit<R>` into the body of vanilla `visit` to avoid a layer of instantiations.

**Comment by NathanSWard** [comment]
@CaseyCarter One more question, sorry!
> will need to detect when the desired result type `is_void` and behave appropriately.
Are these cases legal?
```
std::visit<const void>(visitor{}, my_variant);
std::visit<volatile void>(visitor{}, my_variant);
std::visit<const volatile void>(visitor{}, my_variant);
```
I'm just checking because this will determine if I need to `std::remove_cvref_t` the return type when checking if it is void.

**Comment by CaseyCarter** [comment]
> Are these cases legal?

Yes they are, and they should all behave identically to `std::visit<void>(visitor{}, my_variant);` per [[func.require]/2](http://eel.is/c++draft/func.require#2) . `std::is_void_v<T>` is `true` for cv-`void`, so you should be able to use it and not bother with `remove_cv_t`. (The code font `is_void` in https://github.com/microsoft/STL/issues/31#issuecomment-544326400 hints at this but is *way* too subtle.)
