### ISSUE TITLE
`<system_error>`: Can we add `constexpr` to the default constructor of `error_category` without ABI breakage?

### ISSUE THREAD

**Issue by frederick-vs-ja** [microsoft/STL#3119]
Currently the default constructor of `error_category` lacks `constexpr` in MSVC STL, which is non-conforming and expected to be fixed in vNext (see #1116).

https://github.com/microsoft/STL/blob/2f03bdf361f7f153b4216c60a0d9491c0be13a73/stl/inc/system_error#L70-L72

However, it seems that we can implement `_Addr` as a union so that it can be constant during constant evaluation like this:
```C++
class ErrorCategoryLike {
private:
    union AddrStorage {
    private:
        uintptr_t          num;
        ErrorCategoryLike* ptr;

    public:
        constexpr explicit AddrStorage(uintptr_t addr_num) noexcept : num(addr_num) {}
        constexpr explicit AddrStorage(ErrorCategoryLike* addr_ptr) noexcept : ptr(addr_ptr) {}
    };
    static_assert(sizeof(AddrStorage) == sizeof(uintptr_t) && alignof(AddrStorage) == alignof(uintptr_t),
        "Unsupported platform");

    AddrStorage addr;

protected:
    constexpr explicit ErrorCategoryLike(uintptr_t addr_num) noexcept : addr(addr_num) {}

public:
    constexpr ErrorCategoryLike() noexcept : addr(this) {}

    bool operator==(const ErrorCategoryLike& rhs) const noexcept {
        return _STD _Bit_cast<uintptr_t>(addr) == _STD _Bit_cast<uintptr_t>(rhs.addr);
    }

    virtual ~ErrorCategoryLike() = default;
};
```

See also [the test on godbolt](https://godbolt.org/z/3jecaWbnf).

Such technique requires that
- the union has the same size and alignment of `uintptr_t`, and
- `reinterpret_cast` between `uintptr_t` and pointers is equivalent to `bit_cast`.

I think both conditions hold on Windows (at least for MSVC, clang-cl, etc.) although they are not guaranteed by the standard.

So I guess we can add the `constexpr` without ABI breakge. Is it right?

----
https://github.com/microsoft/STL/blob/2f03bdf361f7f153b4216c60a0d9491c0be13a73/stl/inc/system_error#L112

BTW, this protected constructor is probably also non-conforming as it is probably observable by a conforming program (that defines a class derived from `error_category` and tests the non-existence of this constructor). Changing its access control or signature seemly breaks ABI.

**Comment by frederick-vs-ja** [comment]
> @frederick-vs-ja
> 
> What is your nickname in MS discord (https://discord.gg/XWanNww) ?

I haven't joined yet. I'll try soon.

**Comment by jwakely** [comment]
> BTW, this protected constructor is probably also non-conforming as it is probably observable by a conforming program (that defines a class derived from `error_category` and tests the non-existence of this constructor).

I think it's debatable whether that's non-conforming, and if it matters.

A correct program will not rely on the existence of that constructor, so won't notice it exists. The derived type cannot notice it exists by using `is_constructible` because that checks in an unrelated context, so doesn't have any special access to protected members. If the derived type does `using std::error_category::error_category;` then any attempt to use the protected constructor from outside the derived type would be ill-formed (and `is_constructible<derived, uintptr_t>` is false).

I can think of two ways the derived type can detect the protected member:

1)

```c++
#include <system_error>
#include <cstdint>

struct Cat : std::error_category {
    using std::error_category::error_category;
    void f()
    {
        Cat c(1); // XXX
    }
    std::string message(int) const override;
    const char* name() const noexcept override;
};
```
The XXX line should be ill-formed, but isn't for MSVC.

2) The derived class can use the protected constructor in a _mem-initializer_ for a base class:
```c++
#include <system_error>
#include <cstdint>

struct Cat : std::error_category {
    Cat() : std::error_category(1) { } // XXX
    std::string message(int) const override;
    const char* name() const noexcept override;
};
```
But that's the derived class' fault, it shouldn't be calling an API not specified in the standard.

In both these cases, the derived type has to intentionally rely on an API not provided by the standard. I think [member.functions] p2 makes that OK.

N.B. this is also possible:

```c++
struct Annoying {
  operator const std::error_category&() const;
  operator std::uintptr_t() const;
};
struct Cat : std::error_category {
  Cat(Annoying a) : std::error_category(a) { }
};
```
But that's attempting to use a deleted copy constructor, which the standard says should be ill-formed, and it is still ill-formed due to the ambiguous conversion. (Although MSVC seems to select the deleted copy ctor instead of an ambiguous conversion ... but the end result is the same ... it's ill-formed, as required by the standard).
