### ISSUE TITLE
`<tuple>`: `operator==(tuple<T>, tuple<U>)` can call overloaded `operator&&`

### ISSUE THREAD

**Issue by strega-nil-ms** [microsoft/STL#3131]
**Describe the bug**

If the return type of a custom `operator==` has an `operator&&(bool)` member, then `tuple<T>::_Equals(tuple<U>)` will call that `operator&&` instead of using the built-in `operator&&(bool, bool)`.

**Command-line test case**
```
C:\Temp>type repro.cpp
#include <tuple>

struct Boolish {
    operator bool() {
        return true;
    }

    void operator&&(bool) const {} // EVILLLL
};

struct Meow {
    Boolish operator==(const Meow& rhs) const {
        return {};
    }
};

using namespace std;
int main() {
    tuple<Meow> m;
    return m == m;
}

C:\Temp>cl /EHsc /W4 /WX .\repro.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.34.31823.3 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

repro.cpp
C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.34.31823\include\tuple(602): error C2440: 'return': cannot convert from 'void' to 'bool'
C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.34.31823\include\tuple(602): note: Expressions of type void cannot be converted to other types
C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.34.31823\include\tuple(673): note: see reference to function template instantiation 'bool std::tuple<Meow>::_Equals<Meow>(const std::tuple<Meow> &) const' being compiled
C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.34.31823\include\tuple(673): note: see reference to function template instantiation 'bool std::tuple<Meow>::_Equals<Meow>(const std::tuple<Meow> &) const' being compiled
repro.cpp(20): note: see reference to function template instantiation 'bool std::operator ==<Meow,Meow>(const std::tuple<Meow> &,const std::tuple<Meow> &)' being compiled
```

**Expected behavior**

The code compiles and returns `1`.

**Comment by frederick-vs-ja** [comment]
It seems that the `_Less` member function (present in C++14/17 mode) is similarly buggy.

**Comment by CaseyCarter** [comment]
WG21-P2167 "Improved Proposed Wording for LWG-2114 (contextually convertible to `bool`)" will address this issue (among a host of similar issues in the Standard Library). LWG reviewed the paper on 2022-09-21, and chose the "Option B" presented in the paper for `tuple` which requires the result of comparisons for field types to model _`boolean-testable`_ (although the requirement will be a precondition rather than a mandate as depicted in the paper, since the mandate would be unimplementable). (Thanks to @tcanens for bringing this to our attention in Discord!)

Given that the proposal isn't really a change to the Standard's intent so much as a more clear expression of that intent, and that users have never reported this issue as problematic, I think we should avoid defending against "weird" operators even in older language modes. Doing so would make it possible for new code in old modes to use such weird operators that would work correctly only to break when moving to more recent language modes. In effect, defending would make it possible for users to introduce latent bugs in their programs.

**Comment by CaseyCarter** [comment]
@frederick-vs-ja discusses this issue in https://github.com/microsoft/STL/pull/3132#discussion_r981881770.

**Comment by CaseyCarter** [comment]
@strega-nil-ms comments in https://github.com/microsoft/STL/pull/3132#issuecomment-1261157138:

> Given [P2167](https://wg21.link/p2167), we don't have to do this in C++20 mode; however, I don't believe that we can say this for pre-C++20 modes, and it doesn't harm compatibility with C++20 and up. Therefore, I like this change. I will add the required copyright notice.

**Comment by CaseyCarter** [comment]
We discussed this during the weekly maintainer meeting, and decided (1) we don't want to defend against "weird" operators inconsistently - that is, only some operators or only in some language modes - and (2) always defending against all operators is problematic due to the use of _`synth-three-way`_ to implement `tuple`'s `<=>` operator. Consequently, it's best not to defend at all, which is consistent with the intent of WG21-P2167.

**Comment by frederick-vs-ja** [comment]
> (although the requirement will be a precondition rather than a mandate as depicted in the paper, since the mandate would be unimplementable)

I think it's implementable to mandate the diagnostic-requiring portion (in C++20 and old modes), and the resolution can become
> _Mandates_: ... satisfies _`boolean-testable`_.
> _Preconditions_: ... models _`boolean-testable`_.

But this is not sufficient to reject the evil `operator&&`, and such rejection seems unimplementable.
