### ISSUE TITLE
Why is `std::hash<T>::operator()` not `constexpr`?

### ISSUE THREAD

**Issue by oberrich** [microsoft/STL#3185]
I think it's very annoying that the hash functions provided by the STL are not marked constexpr eventhough I can't think of a single reason for it to be that way, `std::hash` deserves a `constexpr` too.

Looking through the standard I can only find the following relevant statements about the `hash` class:

- [22.10.2 Header `<functional>` synopsis \[functional.syn\]](https://eel.is/c++draft/functional.syn)
<img src="https://i.imgur.com/FJhlqH2.png">

- [22.10.19 Class template `hash` \[unord.hash\]](https://eel.is/c++draft/unord.hash)
<img src="https://i.imgur.com/SD2F44U.png">

- [16.4.4.5 `Cpp17Hash` requirements \[hash.requirements\]](https://eel.is/c++draft/hash.requirements)
<img src="https://i.imgur.com/lyvWLsJ.png">

As far as I understand none of those are stopping us from just making `operator()` and the constructor `constexpr`. Is there reason behind it not being `constexpr` or has this just not been considered by the maintainers yet?

**Comment by frederick-vs-ja** [comment]
MSVC STL is currently heavily using `reinterpret_cast` to inspect bit patterns of scalar values, so `constexpr` is unsuitable. I can image how to make the algorithm constexpr-compatible (except for pointer values) without ABI breakage, that is, using `bit_cast` (or `__built_in` one) to read bytes during constant evaluation.

I'm not sure whether it is an improvement to add `constexpr`, because this (perhaps not heavily) damages compiler througput and may encourage some non-portable codes. And I believe it's intented not to make `std::hash<T>::operator()` constant evaluated, because if `constexpr std::size_t hash_val = std::hash<T>{}(t);` compiles some `T` and `t`, the hash value for `t` becomes unchangeable between different executions, while it is intended to allow such strategy (although not the case of MSVC STL) in LWG-2291.

As for constructors, although not being mandatory in the standard, MSVC STL's `std::hash` specializations already have `constexpr` constructors - actually, they are trivial types.

**Comment by sylveon** [comment]
Adding constexpr to functions is forbidden by the standard iirc, plus I believe the STL has plans to use a hash algorithm which has different results per execution of the program in ABI vNext.

**Comment by oberrich** [comment]
> ...

But one specializations of `std::hash<T>` could have a constexpr call operator while another doesn't, [see this example on godbolt](https://godbolt.org/z/e3j6MbnaE). The constexpr will only visible in the particular specialization, right?

> Adding constexpr to functions is forbidden by the standard iirc

Do you know where in the language roughly? I'm not a languag lawyer but maybe we can get around it, constexpr `std::hash` for integral types straight from the STL would be such a treat.
Isn't the STL allowed to make certain optimizations that are "illegal" according to the standard as long as the result is "equivalent"? I think I heard something along these lines in a talk.

> I believe the STL has plans to use a hash algorithm which has different results per execution of the program in ABI vNext.

Even for integral and floating_point types?

**Comment by frederick-vs-ja** [comment]
> Do you know where in the language roughly?

[[constexpr.functions]](https://eel.is/c++draft/constexpr.functions)
> This document explicitly requires that certain standard library functions are `constexpr` ([dcl.constexpr]). An implementation shall not declare any standard library function signature as `constexpr` except for those where it is explicitly required. Within any header that provides any non-defining declarations of constexpr functions or constructors an implementation shall provide corresponding definitions.

**Comment by oberrich** [comment]
Thanks, guess I'll have to stick to shipping my own for `constexpr` stuff.
After reading through the vNext changes related to the hashing algorithms I've realized this has been discussed previously in  https://github.com/microsoft/STL/pull/686#issuecomment-609261700 and following.
