### ISSUE TITLE
`<algorithm>`: `find` and `count` could vectorize in more cases

### ISSUE THREAD

**Issue by strega-nil-ms** [microsoft/STL#3249]
There are two cases which are currently not covered by `_Vector_alg_in_find_is_safe` and `_Could_compare_equal_to_value_type`/`_Within_limits`:

* `is_pointer_v<_Elem> && is_null_pointer_v<_ValueType>`
* `is_pointer_v<_Elem> && is_pointer_v<_ValueType> && is_object_v<remove_pointer_t<_Elem>> && is_void_v<remove_pointer_t<_ValueType>>`

**Comment by AlexGuteniev** [comment]
What is the 3rd case anyway?

**Comment by StephanTLavavej** [comment]
A couple of observations:

* This is symmetric, so in addition to searching for `void*` in a range of `U*`, the case of searching for `U*` in a range of `void*` could equally be optimized.
  + (There's no point in having symmetry for the `nullptr_t` case, of course :joy_cat:)
* Also, very much like the `copy` optimizations that we have, `cv1 U*` is guaranteed bit-identical to `cv2 U*`, so searching for one in a range of the other could be optimized. (That is, instead of insisting that the pointer types be absolutely identical, we could verify that they point to the same type after removing cv-qualifiers.)

There's definitely a complexity cost to adding additional metaprogramming and test coverage for such scenarios, so we need to draw the line at some point we consider reasonable - just some ideas for potential future work.

**Comment by strega-nil-ms** [comment]
@AlexGuteniev mix up on my part :P
