### ISSUE TITLE
<stacktrace>: SYMOPT_FAIL_CRITICAL_ERRORS has incorrect value

### ISSUE THREAD

**Issue by peterlauro** [microsoft/STL#3283]
**Describe the bug**
there is an inconsistency between documented added symbol-option and actually used value of symbol

https://github.com/microsoft/STL/blob/4483e87f6e5aa5c4598404fc01eecb7e547dd439/stl/src/stacktrace.cpp#L112

based on the microsoft documentation 
https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/symbol-options
the SYMOPT_FAIL_CRITICAL_ERRORS has a value 0x200U

**Command-line test case**
- no test case provided, the issue discovered in the code:

**Expected behavior**
- instead of value 0x100, the value 0x200 shall be used

**Comment by CaseyCarter** [comment]
@AlexGuteniev do you recall any reason we don't include `DbgHelp.h` or `ImageHlp.h` to get the symbolic names for the constants?

**Comment by AlexGuteniev** [comment]
I wanted to avoid mixing `<DbgEng.h>` with `<DbgHelp.h>` and including `<DbgHelp.h>` in general, as we decided against `<DbgHelp.h>` due to thread safety concerns.

**Comment by StephanTLavavej** [comment]
Thanks for the bug report! I've updated it to directly cite the relevant line in `stacktrace.cpp`. This is more accessible than an image of code, inherently shows the affected git commit, and lets us navigate to the full context.

This is a GitHub feature that works in any repo. Simply navigate to a file like https://github.com/microsoft/STL/blob/main/stl/src/stacktrace.cpp and then click on a line, which will highlight it and update your URL to https://github.com/microsoft/STL/blob/main/stl/src/stacktrace.cpp#L112 . Notice that if this is pasted into an issue (as I've done here), it is *not* displayed as a preview, because this is linking to line 112 of `main` and the `main` branch will be updated over time. What you need to do is either (1) click on the "..." to the left of the highlighted line and select "Copy permalink" or (2) use GitHub's keyboard shortcut and type `y` (with the body of the webpage focused) to change the URL to the permalink version. Then you can paste `https://github.com/microsoft/STL/blob/4483e87f6e5aa5c4598404fc01eecb7e547dd439/stl/src/stacktrace.cpp#L112` into an issue and it will be displayed as a syntax highlighted, clickable preview: https://github.com/microsoft/STL/blob/4483e87f6e5aa5c4598404fc01eecb7e547dd439/stl/src/stacktrace.cpp#L112

By shift-clicking, you can select and display a range of lines, which is very useful when discussing larger chunks of code!

(GitHub enforces one limitation - it will not preview permalinks into other repos, only within the same repo.)
