### ISSUE TITLE
<chrono>: building with -J emits C4365

### ISSUE THREAD

**Issue by tiagomacarios** [microsoft/STL#3294]
Building with [-J](https://learn.microsoft.com/en-us/cpp/build/reference/j-default-char-type-is-unsigned?view=msvc-170) will trigger [C4365](https://learn.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-4-c4365?view=msvc-170).

https://godbolt.org/z/dxbj64q36
```
#include <chrono>
```

output:
```
example.cpp
C:/data/msvc/14.34.31931-Pre/include\xcharconv_ryu.h(907): error C2220: the following warning is treated as an error
C:/data/msvc/14.34.31931-Pre/include\xcharconv_ryu.h(907): warning C4365: '=': conversion from 'int' to 'char', signed/unsigned mismatch
Compiler returned: 2
```

**Comment by strega-nil-ms** [comment]
We do not support building with `/Wall`, and I believe that this warning is off by default. I do not believe that we should change code due to this warning, since `c = c + 1;` is completely reasonable code and it's perfectly well defined in this case no matter what `c` is.

**Comment by tiagomacarios** [comment]
Office compiles with Wall. We can fix our fork of the STL, but we would prefer to have fixes upstreamed and reduce our maintenance surface.

**Comment by strega-nil-ms** [comment]
Alright, we'll discuss it; I'm personally very against changing anything here, since this warning is (imo) quite silly.

**Comment by CaseyCarter** [comment]
C4365 is one of very few warnings in our supported off-by-default warning set; we enable it in our "std" test suite, but in neither tr1 nor libcxx:

https://github.com/microsoft/STL/blob/8ddf4da23939b5c65587ed05f783ff39b8801e0f/tests/std/tests/prefix.lst#L6

I'm perfectly happy to disable it in `<xcharconv_ryu.h>` just as we do in several other places. (IMO the real issue here is `/J`, which IIRC we support but probably shouldn't since we obviously have no test coverage.)
