### ISSUE TITLE
Optimize `string_view::operator==` when comparing 2 empty `string_view`s

### ISSUE THREAD

**Issue by Thomas1664** [microsoft/STL#3310]
I discovered room for optimization when comparing 2 empty std::string_view s in GCC. However, Clang already seems to be optimized for this use case. See this quick bench run: https://quick-bench.com/q/FZc2abFbpI5Q_lEHXF7sNGC_Jn4 . Looking at this implementation of the STL, it seems like there is room for improvement as well: if both std:string_view s have the same size, something like memcmp is called. I couldn't verify this because quick bench doesn't support MSVC (yet).

I originally discovered this optimization here: https://github.com/microsoft/vcpkg-tool/pull/843

**Comment by CaseyCarter** [comment]
This is probably worth investigating, since `memcmp` is almost certainly not inlined. We'll want to see a benchmark demonstrating (1) the speedup comparing two empty `string_view`s, and (2) the slowdown comparing at-least-one non-empty `string_view`.

**Comment by tylerbrawl** [comment]
I've tried looking into this recently with benchmarks, and I've created a small repository consisting of these benchmarks at https://github.com/tylerbrawl/OptimizedStringViewComparisonsTest. As a disclaimer, I'm no expert at benchmarking (the knights of Stack Overflow make it clear how painstaking that process truly is), but running the tests naively shows some promising results.

Benchmarking is done by iteratively comparing `std::string_view`-like object instances in both a `std::array` and a `std::list`. The legendary cache unfriendliness of the latter container makes its benchmark results more appealing, since it probably makes for a better representation of actual programs. The output from the benchmarks is usually not too dissimilar from the following on my system:

```
****Array Tests*****
Time Taken for 50,000 Empty std::string_view Comparisons: 178921ns
Time Taken for 50,000 Empty Brawler::OptimizedStringView Comparisons: 45442ns
Empty String Speed-Up: 3.9x

Time Taken for 50,000 Non-Empty std::string_view Comparisons: 386025ns
Time Taken for 50,000 Non-Empty Brawler::OptimizedStringView Comparisons: 435159ns
Non-Empty String Speed-Up: 0.89x

*****List Tests*****
Time Taken for 50,000 Empty std::string_view Comparisons: 287864ns
Time Taken for 50,000 Empty Brawler::OptimizedStringView Comparisons: 225524ns
Empty String Speed-Up: 1.3x

Time Taken for 50,000 Non-Empty std::string_view Comparisons: 477472ns
Time Taken for 50,000 Non-Empty Brawler::OptimizedStringView Comparisons: 568042ns
Non-Empty String Speed-Up: 0.84x
```

The comparison optimization is implemented somewhat differently than what @Thomas1664 initially proposed, but it should produce equivalent results and allow for an early exit in the comparison in more scenarios. Basically, rather than checking if both strings are empty, we first check if *either* string is empty; the result of the `operator==` comparison is then equivalent to whether or not both strings are empty.

If you choose to run the benchmarks provided in the aforementioned repository, make sure to compile the program without whole program optimization (i.e., exclude compiler option `/GL`) and without link-time code generation (i.e., exclude linker option `/LTCG`). That way, the compiler doesn't remove the string comparison loop for not having any side effects. (The default Release build configuration for the solution disables these settings.)

**Comment by YexuanXiao** [comment]
I have written a [benchmark](https://github.com/YexuanXiao/STL/commit/c4b2e0f01b3e6c72baf85829cf844b2f9dcb0d54) for this. If anyone is satisfied with it, I will initiate a PR to merge it into the mainline.
I chose a very short string for testing because comparison of long strings would erase any differences.
Below is the output from running it three times:

```powershell
2024-08-21T02:24:07+08:00
Running D:\benchmark-sv_equal.exe
Run on (8 X 3302 MHz CPU s)
CPU Caches:
  L1 Data 48 KiB (x4)
  L1 Instruction 32 KiB (x4)
  L2 Unified 1280 KiB (x4)
  L3 Unified 12288 KiB (x1)
-----------------------------------------------------
Benchmark           Time             CPU   Iterations
-----------------------------------------------------
curr_empty       44.7 ns         43.9 ns     16000000
czl_empty        37.5 ns         37.7 ns     18666667
curr_short       46.9 ns         46.3 ns     16185806
czl_short        49.0 ns         49.7 ns     14451613

2024-08-21T02:24:16+08:00
Running D:\benchmark-sv_equal.exe
Run on (8 X 3302 MHz CPU s)
CPU Caches:
  L1 Data 48 KiB (x4)
  L1 Instruction 32 KiB (x4)
  L2 Unified 1280 KiB (x4)
  L3 Unified 12288 KiB (x1)
-----------------------------------------------------
Benchmark           Time             CPU   Iterations
-----------------------------------------------------
curr_empty       45.9 ns         44.6 ns     11200000
czl_empty        37.2 ns         37.7 ns     18666667
curr_short       46.3 ns         46.5 ns     15448276
czl_short        48.9 ns         48.8 ns     11200000

2024-08-21T02:24:23+08:00
Running D:\benchmark-sv_equal.exe
Run on (8 X 3302 MHz CPU s)
CPU Caches:
  L1 Data 48 KiB (x4)
  L1 Instruction 32 KiB (x4)
  L2 Unified 1280 KiB (x4)
  L3 Unified 12288 KiB (x1)
-----------------------------------------------------
Benchmark           Time             CPU   Iterations
-----------------------------------------------------
curr_empty       45.1 ns         45.5 ns     15448276
czl_empty        37.7 ns         37.7 ns     19478261
curr_short       47.1 ns         47.5 ns     15448276
czl_short        49.7 ns         47.4 ns     11200000
```

@CaseyCarter @AlexGuteniev @StephanTLavavej

**Comment by AlexGuteniev** [comment]
To me it looks generally good.

The code would still need minor code convention tweaks (at least some missing and some extra newlines), but this can be better addressed within a PR.

Also one major thing regarding the benchmark -- it should test the STL directly, rather than recreate similar situation. To compare the PR and `main`, can run the benchmark with unmodified code. (To avoid the benchmark using stale STL, build STL and build then benchmark with `--clean-first` when jumping between branches or revisions).

Note: I'm not a maintainer, maintainers' view may differ.
