### ISSUE TITLE
<ios>: std::ios_base::openmode is not a bitmask type

### ISSUE THREAD

**Issue by neilstephens** [microsoft/STL#3401]
**Describe the bug**
std::ios_base::openmode is not implemented as a bitmask type, therefore, for example, |= operator usage fails to compile.

**Command-line test case**
```
C:\Temp>type example.cpp
#include <ios>

int main()
{
    auto open_flags = std::ios::binary;
    open_flags |= std::ios::app;

    return 0;
}

C:\Temp>cl -std:c++17 .\example.cpp

example.cpp
<source>(6): error C2678: binary '|=': no operator found which takes a left-hand operand of type 'std::_Iosb<int>::_Openmode' (or there is no acceptable conversion)
C:/data/msvc/14.21.27702.2/include\cstddef(70): note: could be 'std::byte &std::operator |=(std::byte &,const std::byte) noexcept' [found using argument-dependent lookup]
<source>(6): note: while trying to match the argument list '(std::_Iosb<int>::_Openmode, const std::_Iosb<int>::_Openmode)'
Compiler returned: 2

```

**Expected behavior**
compile successfully 

**STL version**
    ```
    Microsoft (R) C/C++ Optimizing Compiler Version 19.21.27702.2 for x64
    ```

**Comment by neilstephens** [comment]
https://godbolt.org/z/999fffPEx

**Comment by frederick-vs-ja** [comment]
MSVC STL's `std::ios_base::openmode` is `int`, and thus a bitmask type, which is perhaps unchanged for over 10 years.

https://github.com/microsoft/STL/blob/9ae1b3f1faada15feff9f0a0a9fa55c9dce532f5/stl/inc/xiosbase#L101

The actual bug is that type type of `std::ios_base::binary` (and its friends) is _not_ `std::ios_base::openmode` in MSVC STL.
https://github.com/microsoft/STL/blob/9ae1b3f1faada15feff9f0a0a9fa55c9dce532f5/stl/inc/xiosbase#L64-L78
