### ISSUE TITLE
<vector>: some questions about vector::insert(position, first ,last) behaviors

### ISSUE THREAD

**Issue by Kami-chanw** [microsoft/STL#3491]
I have two questions about insert(_Where, _First, _Last)(https://github.com/microsoft/STL/blob/e7f52446c6f41fddbed31904f594a1f711f85601/stl/inc/vector#L1223-L1252) and _Insert_x(_Where, _Count) (https://github.com/microsoft/STL/blob/e7f52446c6f41fddbed31904f594a1f711f85601/stl/inc/vector#L3465-L3492).
**In function** `insert(_Where, _First, _Last)`:
```
if constexpr (_Is_cpp17_fwd_iter_v<_Iter>) {
            const auto _Length = static_cast<size_t>(_STD distance(_UFirst, _ULast));
            const auto _Count  = _Convert_size<size_type>(_Length);
            const auto _Off    = static_cast<difference_type>(_Insert_x(_Where, _Count));
            _Copy_unchecked(_UFirst, _ULast, begin() + _Off);
#ifdef __cpp_lib_concepts
} else if constexpr (forward_iterator<_Iter>) {
            const auto _Length = _To_unsigned_like(_RANGES distance(_UFirst, _ULast));
            const auto _Count  = _Convert_size<size_type>(_Length);
            const auto _Off    = static_cast<difference_type>(_Insert_x(_Where, _Count));
            _Copy_unchecked(_UFirst, _ULast, begin() + _Off);
#endif // __cpp_lib_concepts
} else {
            const auto _Old_size = this->_Mysize;
            for (; _UFirst != _ULast; ++_UFirst) {
                emplace_back(*_UFirst);
            }
            // other code...
            _STD rotate(begin() + _Saved_offset, begin() + static_cast<difference_type>(_Old_size), end());
}
```
In the first two if statements, why not expand capacity and then emplace_back & rotate asyou do when encountered non-forward iterator? In my opinion, emplace_back & rotate can provide better exception safety guarantee.
**In function** `Insert_x(_Where, _Count)`:
```
this->_Myvec.resize(this->_Nw(size() + _Count), 0);
if (empty()) {
        this->_Mysize += _Count;
} else { // make room and copy down suffix
        iterator _Oldend = end();
        this->_Mysize += _Count;
        _STD copy_backward(begin() + _Off, _Oldend, end());
}
```
Why not use resize & copy strategy instead of reserve & move? At the very least, move_backward should be used instead of copy_backward.

**Comment by CaseyCarter** [comment]
For clarity: the `insert(_Where, _First, _Last)` you first linked is from the primary template of `vector`, but the code you ask about later is `insert(_Where, _First, _Last)` from the `vector<bool>` partial specialization.

> In the first two if statements, why not expand capacity and then emplace_back & rotate asyou do when encountered non-forward iterator? In my opinion, emplace_back & rotate can provide better exception safety guarantee.

A _stronger_ exception guarantee isn't always a _better_ exception guarantee. Stronger exception guarantees generally come at the cost of performance, and this would be such a case: the rotate needed to provide the strong guarantee is an additional O(N) operation. The Standard doesn't require is to provide the strong guarantee here, so we choose performance. (In general, it's easier for a user to provide a strong guarantee themselves by wrapping an operation that provides the basic guarantee than it is  to implement a more performant operation given one that provides the strong guarantee.

> Why not use resize & copy strategy instead of reserve & move? At the very least, move_backward should be used instead of copy_backward.

This _is_ "resize and copy", AFAICS: we resize the underlying vector (`this->_Myvec`) of `uint32_t`, then make a "hole" for the values to be inserted by copying the existing elements to the end.  `move_backward` vs. `copy_backward` makes no difference here since this is `vector<bool>` - moving vs. copying `bool` is the same operation.

**Comment by frederick-vs-ja** [comment]
> In the first two if statements, why not expand capacity and then emplace_back & rotate asyou do when encountered non-forward iterator? In my opinion, emplace_back & rotate can provide better exception safety guarantee.

IMO whenever reallocation happens, `rotate` can be avoided because we can directly construct the newly inserted elements at the final location, expected that if the range is non-forward and non-sized, we may need to reallocate the storage and relocate the inserted elements more than once.

I think we can restrict the use of `emplace_back` & `rotate` to the situations where reallocation doesn't happen. For non-forward non-sized ranges, we may append them at first, and adjust their offsets on reallocation, if any.

**Comment by Kami-chanw** [comment]
> I think we can restrict the use of emplace_back & rotate to the situations where reallocation doesn't happen. For non-forward non-sized ranges, we may append them at first, and adjust their offsets on reallocation, if any.

I think this is a good idea so that we can more easily rollback if value construct fails before rotation.

**Comment by StephanTLavavej** [comment]
I agree with what @CaseyCarter said, and this was my guiding principle when I rewrote `vector<T>` ages ago (unfortunately I didn't get around to overhauling `vector<bool>`):

> The Standard doesn't require us to provide the strong guarantee here, so we choose performance.

**Comment by Kami-chanw** [comment]
The last one question, where should I find the fine print about the exception guarantees for each function?

**Comment by Kami-chanw** [comment]
The last quesiton, where should I find the fine print about the exception guarantees for each function?
