### ISSUE TITLE
`<filesystem>`: change the implementation of `path` and/or `path::iterator` to make it reversible

### ISSUE THREAD

**Issue by fsb4000** [microsoft/STL#3498]
As @frederick-vs-ja wrote the standard doesn't strictly require path::iterator to meet Cpp17BidirectionalIteraror ([[fs.path.itr]/2](https://eel.is/c++draft/fs.path.itr#2)) but libc++ and libstdc++ allow path to be reversed: https://godbolt.org/z/K8jPW1r5x

```c++
#include <filesystem>
#include <ranges>
using namespace std;
using namespace std::filesystem;
namespace vw = std::views;
void f() {
    for (const auto& c : vw::reverse(path {})) // it works with libstdc++ and libc++ but not with Microsoft STL
      (void)c.stem();
}
```

Consider change the current implementation to make that code works.

More info: https://github.com/microsoft/STL/issues/3474

**vNext note**:  Resolving this issue will require breaking binary compatibility. We won't be able to accept pull requests for this issue until the vNext branch is available. See #169 for more information.

**Comment by StephanTLavavej** [comment]
In my opinion, this doesn't merit providing a guarantee beyond the Standard.

**Comment by StephanTLavavej** [comment]
We talked about this at the weekly maintainer meeting; @strega-nil-ms was of the opinion that this is definitely not a bidirectional iterator (because it's a stashing iterator, and therefore not even a forward iterator) and that we should make no attempt to support this use case. @barcharcraz concurred. Thanks for filing this issue but we're going to close it as "not planned".
