### ISSUE TITLE
if (this != &rhs) in unique ptr

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [microsoft/STL#3538]
Hi

This this != _STD addressof(_Right) seems redundant 
https://github.com/microsoft/STL/blob/994f94199c561a38a4a8e15584030160095bc25a/stl/inc/memory#L3264

I can't say I understand what are you trying to enable if away, tbh though - but this seems like a less specialized version of the previous assignment.

Here is libc++ - no check
https://github.com/llvm/llvm-project/blob/93a2feccbc909230b6a091f5836b92739bd12941/libcxx/include/__memory/unique_ptr.h#L231

Can you maybe delete it?

**Comment by CaseyCarter** [comment]
This self-assignment guard is both unnecessary and observably non-conforming. We should absolutely get rid of it.

**Comment by MikeGitb** [comment]
Why is it non-conforming?

**Comment by CaseyCarter** [comment]
> Why is it non-conforming?

The deleter and/or pointer types could be user-provided, and could therefore observe the absence of the "`release`-and-`reset`" or "deleter self-assignment" effects that the Standard mandates we must implement. In fairness, nobody has ever complained about this so it's very likely nobody cares. The real issue is the cost of the unnecessary branch.

**Comment by Osyotr** [comment]
@CaseyCarter I think the question was about `enable_if` one line above the linked line. (Haha off-by-one error)

**Comment by CaseyCarter** [comment]
> @CaseyCarter I think the question was about `enable_if` one line above the linked line. (Haha off-by-one error)

My impression is that the question is stating "this conditional seems pointless, but I can't be certain since I don't know what the `enable_if` is doing". I addressed the conditional, but didn't point out that the `enable_if` is there to make this assignment operator "disappear" when the `unique_ptr`'s deleter type isn't move assignable, i.e., it's implementing [this constraint](https://eel.is/c++draft/unique.ptr.single.asgn#1).

**Comment by DenisYaroshevskiy** [comment]
The `enable_if` question is about having two copies of move assignment, one with check, one without

**Comment by CaseyCarter** [comment]
This function handles move assignments:

https://github.com/microsoft/STL/blob/994f94199c561a38a4a8e15584030160095bc25a/stl/inc/memory#L3262-L3269

and this one handles rvalue converting assignments:

https://github.com/microsoft/STL/blob/994f94199c561a38a4a8e15584030160095bc25a/stl/inc/memory#L3252-L3260

They're both specified by https://eel.is/c++draft/unique.ptr.single.asgn. Comparing the specifications, we see the latter overload has a few extra constraints resulting in a more complicated `enable_if` with a `conjunction` of terms. Oddly enough the bodies of both overloads could be identical. In both cases, the `enable_if` requires that the deleter of the right-hand-side of the assignment (the argument to the assignment operator) is assignable to the deleter of the left-hand-side (`*this`).
