### ISSUE TITLE
`<iostream>`: `cout` cannot print thousands separator from its own locale

### ISSUE THREAD

**Issue by JMazurkiewicz** [microsoft/STL#3562]
Repro:
```c++
#include <iostream>
#include <locale>

using namespace std;

int main() {
  try {
    locale pl{"pl"};
    cout.imbue(pl);
    cout.exceptions(ios_base::failbit | ios_base::badbit);

    // 'sep' is U+00A0 (NBSP) for polish locale (which is already weird, I
    // expected U+0020)
    const char sep = use_facet<numpunct<char>>(pl).thousands_sep();

    cout << sep << '\n';
  } catch (const exception &e) {
    cerr << e.what() << '\n';
  }
}
```

When the global code page is 65001 (UTF-8) we will get an error:
```console
PS D:\stl-playground> chcp 65001
Active code page: 65001
PS D:\stl-playground> cl /EHsc /nologo .\cout.cpp
cout.cpp
PS D:\stl-playground> .\cout.exe
ios_base::badbit set: iostream stream error
```

But when we set global code page to 1250 (Central European) everything will be ok (which is expected):
```console
PS D:\stl-playground> chcp 1250 
Active code page: 1250
PS D:\stl-playground> cl /EHsc /nologo .\cout.cpp
cout.cpp
PS D:\stl-playground> .\cout.exe
 
^ NBSP is here
```

The question is: **Should `cout` be able to print character from its own locale without changing the global code page?**

Also, if we use `locale::global(pl)` before `cout.imbue(pl)` then this program will print NBSP correctly (the code page won't matter).

**Comment by StephanTLavavej** [comment]
We talked about this at the weekly maintainer meeting and we believe that this is (unfortunately) by design. `cout` (and `stdout`, it isn't specific to C++) are famously/notoriously unable to handle UTF-8 without either C++23 `<print>` or the `_O_U16TEXT` incantations (see https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/setmode?view=msvc-170#example-use-_setmode-to-change-stdout ). Merely setting the console codepage to UTF-8 is insufficient.

Arguably, MSVC could have been designed to handle UTF-8 better here by default, but it seems way too late (decades) to change this without breaking back-compat. (`<locale>` doesn't help by expecting a single `char` to be able to describe a separator, as @strega-nil-ms notes.) `<print>` providing a new path that handles Unicode correctly seems like the most that can be done.
