### ISSUE TITLE
P0784R7 Library Support For More constexpr Containers

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#37]
[P0784R7](https://wg21.link/P0784R7) Library Support For More `constexpr` Containers

LWG-3303 Bad `constexpr` marker for `destroy/destroy_n`

Feature-test macro as of WG21-N4842:
`#define __cpp_lib_constexpr_dynamic_alloc 201907L`

Needed for #43 and #45.

**Comment by miscco** [comment]
@MichaelRizkalla, I had a look at this because MSVC seems to now support `__cpp_constexpr_dynamic_alloc` and it is quite difficult to get it right with the huge machinery that std::vector uses

I fixed the merge conflicts and also some broken machinery / test code. You can find the fixes in my P0784R7 branch here https://github.com/miscco/STL/tree/P0784R7

**Comment by MichaelRizkalla** [comment]
@miscco, I am still trying to wrap my head around the entire code base and was expecting my PR to be simple to deal with 😿 . Is there any recommendation you see fit to handle this PR given the same content is implemented in your P0784R7 branch?

**Comment by miscco** [comment]
"My" branch is your branch with merge conflicts resolved and some fixes for MSVC, so you should be able to either cherry-pick, or rebase or reset on that.

Note that i did not fix anything else
