### ISSUE TITLE
`<barrier>`: Some `_STL_VERIFY`s are not working well

### ISSUE THREAD

**Issue by achabense** [microsoft/STL#3748]
The following piece of code will not trigger any diagnosis.
```
#include<barrier>

int main() {
	std::barrier bar{PTRDIFF_MIN};//0b1000...0 << 1 ~> 0

	std::barrier bar2{100};
	(void) bar2.arrive(PTRDIFF_MIN + 1);//0b1000....1 << 1 ~> 2
}
```
A fixed check for the ctor would be `_STL_VERIFY(_Expected >= 0 and _Expected <= max(), ...);`. Also please considering adding a static_assert to guarantee that `max() << _Barrier_value_shift` will keep positive and not lose any bit.
https://github.com/microsoft/STL/blob/c8d1efb6d504f6392acf8f6d01fd703f7c8826c0/stl/inc/barrier#L81-L86
A fixed check for `arrive` would be `_STL_VERIFY(_Update > 0 && _Update <= max(), ...)`, before shifting. (The second half of check is to avoid large positive values like `PTRDIFF_MAX - 1`.)
https://github.com/microsoft/STL/blob/c8d1efb6d504f6392acf8f6d01fd703f7c8826c0/stl/inc/barrier#L95-L98

**Comment by frederick-vs-ja** [comment]
Checking of `_Expected` was weakend in 84f5ac68caac35a12e51df87493443f3fb349635 which said "barrier micro optimizations". Was the weakening intentional?

Also, why don't we simply spell the value of `_Barrier_max` as `PTRDIFF_MAX / 2` or `PTRDIFF_MAX >> 1`?
https://github.com/microsoft/STL/blob/c8d1efb6d504f6392acf8f6d01fd703f7c8826c0/stl/inc/barrier#L46

@AlexGuteniev

**Comment by achabense** [comment]
For the constructor, as the check is performed on the shifted value, any negative `_Expected` with 30th/62th bit being zero will pass the check. This error is not catchable after construction, as `_Val._Myval2._Current` itself is positive.
