### ISSUE TITLE
Warning when sorting vector<bool>

### ISSUE THREAD

**Issue by e4lam** [microsoft/STL#382]
I have some generic data structure code that works with type `T`'s of possibly `bool`'s which internally does things with `std::vector<T>` types. When the code uses various algorithms like `std::sort()` or `std::nth_element()` on these arrays where type `T` is `bool`, we get warning C4804's:
```
warning C4804: '<': unsafe use of type 'bool' in operation
```
I also happen to work in a code base where warning C4804 is an error. :(

Currently, using Visual Studio 16.4.1, but also happens with older compiler versions. For your convenience, you can also go here: https://godbolt.org/z/3R2vQ3

Code:
```
#include <algorithm>
#include <vector>
#include <functional>

#if 1 // this warns!

template <typename T>
void algo(std::vector<T>& v) { std::sort(v.begin(), v.end()); }

#if 0 // And so does this:
template <typename T>
void algo(std::vector<T>& v) { std::sort(v.begin(), v.end(), std::less<>()); }
#endif

#else // no warning!

template <typename T>
void algo(std::vector<T>& v) { std::sort(v.begin(), v.end(), std::less<T>()); }

#endif

void sort_bool(std::vector<bool>& v) { algo(v); }
```
Sample run:
```
> cl /c /std:c++14 /permissive- /we4804  foo.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.24.28314 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

foo.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\xstddef(240): error C4804: '<': unsafe use of type 'bool' in operation
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\xstddef(239): note: while compiling class template member function 'bool std::less<void>::operator ()<bool&,std::_Vb_reference<std::_Wrap_alloc<std::allocator<std::_Vbase>>>>(_Ty1,_Ty2 &&) noexcept(<expr>) const'
        with
        [
            _Ty1=bool &,
            _Ty2=std::_Vb_reference<std::_Wrap_alloc<std::allocator<std::_Vbase>>>
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\algorithm(3465): note: see reference to function template instantiation '_BidIt std::_Insertion_sort_unchecked<_RanIt,_Pr>(_BidIt,const _BidIt,_Pr)' being compiled
        with
        [
            _BidIt=std::_Vb_iterator<std::_Wrap_alloc<std::allocator<std::_Vbase>>>,
            _RanIt=std::_Vb_iterator<std::_Wrap_alloc<std::allocator<std::_Vbase>>>,
            _Pr=std::less<void>
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\algorithm(3474): note: see reference to function template instantiation 'void std::_Sort_unchecked<_Iter,_Fn>(_RanIt,_RanIt,__int64,_Pr)' being compiled
        with
        [
            _Iter=std::_Vb_iterator<std::_Wrap_alloc<std::allocator<std::_Vbase>>>,
            _Fn=std::less<void>,
            _RanIt=std::_Vb_iterator<std::_Wrap_alloc<std::allocator<std::_Vbase>>>,
            _Pr=std::less<void>
        ]
foo.cpp(7): note: see reference to function template instantiation 'void std::sort<std::_Vb_iterator<std::_Wrap_alloc<std::allocator<std::_Vbase>>>,std::less<void>>(const _RanIt,const _RanIt,_Pr)' being compiled
        with
        [
            _RanIt=std::_Vb_iterator<std::_Wrap_alloc<std::allocator<std::_Vbase>>>,
            _Pr=std::less<void>
        ]
foo.cpp(16): note: see reference to function template instantiation 'void algo<bool>(std::vector<bool,std::allocator<bool>> &)' being compiled
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\xstddef(242): error C4804: '<': unsafe use of type 'bool' in operation
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\algorithm(3329): note: see reference to function template instantiation 'bool std::less<void>::operator ()<bool&,std::_Vb_reference<std::_Wrap_alloc<std::allocator<std::_Vbase>>>>(_Ty1,_Ty2 &&) noexcept const' being compiled
        with
        [
            _Ty1=bool &,
            _Ty2=std::_Vb_reference<std::_Wrap_alloc<std::allocator<std::_Vbase>>>
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\algorithm(3465): note: see reference to function template instantiation '_BidIt std::_Insertion_sort_unchecked<_RanIt,_Pr>(_BidIt,const _BidIt,_Pr)' being compiled
        with
        [
            _BidIt=std::_Vb_iterator<std::_Wrap_alloc<std::allocator<std::_Vbase>>>,
            _RanIt=std::_Vb_iterator<std::_Wrap_alloc<std::allocator<std::_Vbase>>>,
            _Pr=std::less<void>
        ]
```

This seems to stem from some implementation behaviour via `std:less<void>`. In libstdc++ and libc++, it seems they might just use plain `operator<()` which might avoid this problem. But of course, gcc/clang also don't generate this warning so it's hard to tell.

**Comment by CaseyCarter** [comment]
Minimal repro:
```c++
#include <vector>

void f(bool x, bool y) {
    (void) (x < y); // Fine

    // error C4804: '<': unsafe use of type 'bool' in operation
    (void) (x < *std::vector<bool>{y}.begin());
}
```
Apparently C4804 is triggered by comparing a `bool` with something implicitly convertible to `bool`.

**Comment by e4lam** [comment]
Does this bug need to be redirected to the compiler team then?

**Comment by BillyONeal** [comment]
Seems like a warning doing what it's supposed to do; not much the compiler team could do other than by removing the warning, which you can effectively do by turning it off. Does `#pragma warning(suppress: 4804)` just before the call to `sort` fix the issue?

As an aside, sorting a vector<bool> seems really inefficient when it's the same thing as partition. Or I guess partition with a negater.

**Comment by StephanTLavavej** [comment]
I think this is by design for both the library and the compiler. The library appears to be emitting this from the insertion sort step:
https://github.com/microsoft/STL/blob/07e85d10c051a0a53d522a28affb1fbc43fc24f0/stl/inc/algorithm#L3352-L3361
This is why we're comparing a real `bool` against a proxy element.

And the compiler appears to be intentionally emitting C4804.

I recommend simply sorting with `less<T>`. For containers with real elements (i.e. all Standard containers except `vector<bool>`) there is no difference. For `vector<bool>` this will implicitly convert proxies to bools before comparing them with `operator<` which doesn't emit a warning, as Casey found. Is that perma-workaround problematic for your code?

(As an aside, sorting a `vector<bool>` is a performance nightmare, even with `partition()`, since it will attempt to do so much bitwise work. All that's physically necessary is to count the bits, then fill the underlying storage with all-0 and all-1 values, with at most one partially filled word. Unfortunately, `vector<bool>` doesn't expose enough of its internals to make that possible. If `vector<bool>` performance were considered important, we could write metaprogramming in various STL algorithms, but it's used rarely enough that it wouldn't be worth the effort and increased maintenance cost.)

**Comment by e4lam** [comment]
Alright. I've already gone down that road already. Thanks for looking at this issue!

**Comment by StephanTLavavej** [comment]
If we really had to silence this warning, it might be possible to give `_Vb_reference` (i.e. `vector<bool>::reference`) hidden friend functions for `bool` comparisons. While not depicted in the Standard, I believe it would be very difficult to observe. If this turns out to be more problematic for you, or if more users encounter this warning, we could investigate such an approach.

**Comment by CaseyCarter** [comment]
I suggest filing a suggestion at [Developer Community](https://developercommunity.visualstudio.com/content/idea/post.html?space=62) that the compiler should not emit C4804 when comparing a `bool` with an expression of class type which implicitly converts directly to (possibly `const`) `bool`. The point (I assume) is to allow expressions like `some_bool > other_bool` but forbid `some_bool > 42`, so for consistency we should allow `some_bool > converts_to_bool` and forbid `some_bool > converts_to_int` (which implicitly converts to `bool`, but only indirectly).
