### ISSUE TITLE
Overloading `new` and `delete` on a freestanding device

### ISSUE THREAD

**Issue by MucaGinger** [microsoft/STL#3910]
I'm looking for an effective, multi-thread safe, only fixed size memory container alternative mechanism to default `new` memory allocator and `delete` deallocator. I'm targetting use in C++ where code runs on a _freestanding_ (no underlying operating system) implementation on a memory constrained device (microcontroller device with up to 1Mbyte of RAM/FLASH and sub-gigahertz frequency of CPU operation speed).  Additionally I would be using such a memory allocation mechanism in combination with a pre-allocated (statically, at compile time, fixed-size container) memory and not dynamic (on heap) memory.

Therefore I'm asking whether there are any known solutions for a _freestanding_ implementation in context of STL or outside of it?

P.S.: I'm aware that modern C++ doesn't offer the best solutions for embedded developers which develop their applications on bare-metal devices with restricted specs. That's why I'm asking STL experts about known ways of mangling with existing dynamical memory allocation mechanism (from STL perspective).

**Comment by MucaGinger** [comment]
Okay, can I only ask one more thing, are there any plans in progress to improve compatibility with freestanding implementation for future versions of STL?

**Comment by CaseyCarter** [comment]
Despite recent work in the C++ Standard to specify a more useful set of requirements for freestanding implementations, we don't have plans to move in that direction. I assume the lack of such plans is because the folks above my pay grade who make those decisions haven't seen sufficient customer demand. I recommend [posting a suggestion on Developer Community](https://developercommunity.visualstudio.com/cpp/suggest) if you are interested in freestanding support.
