### ISSUE TITLE
<optional>: Should optional::operator* trigger a debug assert if there is no value?

### ISSUE THREAD

**Issue by matthew-dews** [microsoft/STL#392]
Looking at the implementations of `operator*` in `std::optional` I wondered if it would be helpful if they had debug asserts which check that `has_value()` is true to catch `optional`s being dereferenced when they shouldn't be. Would this make any sense to add or are there reasons not to have something like that?

**Comment by CaseyCarter** [comment]
This sounds perfectly reasonable to me. We should change `operator->` similarly. @BillyONeal, would it make sense to guard these with `_CONTAINER_DEBUG_LEVEL`?

**Comment by BillyONeal** [comment]
Hmmm, that's a good question. I've been trying to draw a strong distinction between settings that affect the containers and settings that affect debug asserts in general, particularly since we did the effort to make iterator asserts work nicely in release builds (e.g. `NDEBUG _ITERATOR_DEBUG_LEVEL=2`. However, the majority of the motivation for that distinction is that `_ITERATOR_DEBUG_LEVEL` affects layout, and `_CONTAINER_DEBUG_LEVEL` does not (the intent being that we expect folks who value security over perf to increase `_CONTAINER_DEBUG_LEVEL` in release builds).

Is this `has_value` check something you might expect those security folks to care about? If so, do we want to consider changing the name `_CONTAINER_DEBUG_LEVEL` since that's new-ish and we can probably get away with doing so?

**Comment by matthew-dews** [comment]
It looks like the default constructor of optional does not initialize the value, so dereferencing an empty optional results in reading uninitialized memory, which seems like a security concern.

**Comment by StephanTLavavej** [comment]
Note that if you want to change the name of a macro, you can still support the old name for backwards compatibility; we did this when unifying `_SECURE_SCL` and `_HAS_ITERATOR_DEBUGGING` into `_ITERATOR_DEBUG_LEVEL` and that was much more complicated.

Perhaps `_STL_SECURITY_LEVEL` would be a better name for an STL-wide feature that enables "cheap" security checks.

**Comment by barcharcraz** [comment]
I think it's probably fine to put this one in particular under `_CONTAINER_DEBUG_LEVEL`. Optional is sorta a container :D.

**Comment by panikc** [comment]
Has this been fixed with https://github.com/microsoft/STL/pull/1362?

**Comment by sylveon** [comment]
Seems like it

**Comment by CaseyCarter** [comment]
Fixed by #1362.

(Good catch, @panikc - I didn't recall the duplicate.)
