### ISSUE TITLE
How to suppress STL warnings?

### ISSUE THREAD

**Issue by j-stephan** [microsoft/STL#4010]
In one of our projects we conditionally include C++20 headers if they are available:

```c++
#if __has_include(<bit>)
#include <bit>
#else
// Our own implementation
#endif
```

This works fine for all platforms except MSVC where the following warning is issued during compilation:

```
warning STL4038: The contents of <bit> are available only with C++20 or later.
```

How do we suppress this warning? As far as I understand this is not something that can be disabled with a `#pragma warning` since the STL warnings are in fact `#pragma message`s.

**Comment by StephanTLavavej** [comment]
`__has_include` is a poor mechanism; the header is always physically present regardless of Standard mode. You should be using feature-test macros instead; `__cpp_lib_bit_cast`, `__cpp_lib_bitops`, `__cpp_lib_byteswap`, `__cpp_lib_endian`, `__cpp_lib_int_pow2` are all available depending on what you're using. (You need to include `<version>` first according to the Standard; in our implementation, including any STL header first is sufficient.)

**Comment by j-stephan** [comment]
Okay, but how do I do this when compiling for C++17? ´<version>` itself is only available from C++20.

**Comment by fsb4000** [comment]
><version> itself is only available from C++20.

according to C++ standard, yes, but

`<version>` is available in any C++ standard mode in libc++ and libstdc++ and in Microsoft STL: https://gcc.godbolt.org/z/qW6aoEbKc

**Comment by bernhardmgruber** [comment]
@StephanTLavavej: I am trying to understand the best practice you are giving. And as @j-stephan said, `<version>` may not be available yet on all compilers in a cross-platform codebase. So you would say the the first schema here:
```c++
#if __has_include(<version>)
#    include <version>
#endif
// later:
#ifdef __cpp_lib_bitops
#    include <bit>
#endif
// later:
#ifdef __cpp_lib_bitops
    std::popcount(value);
#else
    // fallback implementation
#endif
```
is better than this version:
```c++
#if __has_include(<bit>)
#    include <bit>
#endif
// later:
#ifdef __cpp_lib_bitops
    std::popcount(value);
#else
    // fallback implementation
#endif
```
?

I wonder because I tend to write the second version, since it requires one `#ifdef` less. Thank you for your advice!

**Comment by StephanTLavavej** [comment]
We talked about this at the weekly maintainer meeting and we don't really have more specific guidance to give here, because it depends on what other implementations and versions of those implementations you're targeting. We know what works best for this repo but our knowledge rapidly falls off elsewhere. Sorry we can't be of more assistance!
