### ISSUE TITLE
Why shouldn't we replace `_Ref_fn` with `reference_wrapper`?

### ISSUE THREAD

**Issue by frederick-vs-ja** [microsoft/STL#4027]
In #4025 there's attemption to strengthen the exception specification of `_Ref_fn::operator()`.

Given the standard class template `std::reference_wrapper` is already a invocable wrapper and its `operator()` has a propagating exception specification (thanks to LWG-3764), it seems OK to replace the uses of `_Ref_fn` with `reference_wrapper`.

Pros:
- user codes should only use `reference_wrapper`, so we might be able to instantiate less specializations.

Cons:
- `reference_wrapper` is slightly heavier than `_Ref_fn`;
- `reference_wrapper` is assignable, which might be unwanted for the internal details of the implementation.

**Comment by CaseyCarter** [comment]
IMO we should not replace `_Ref_fn` with `reference_wrapper`, because `reference_wrapper` is substantially heavier. `_Ref_fn` is an aggregate so it can be enregistered; `reference_wrapper` is not. This was the original motivation for creating `_Ref_fn`; "we can't accidentally assign to it" is nice, but easily achievable with `const reference_wrapper`.

**Comment by frederick-vs-ja** [comment]
@CaseyCarter Thanks for explonation! Is this design choice documented anywhere?

**Comment by CaseyCarter** [comment]
Sadly no. Our implementation documentation practices were nearly non-existent before open sourcing. The team was so small (1-3 maintainers) that everyone either wrote or reviewed every change, so we didn't really need documentation. Let's turn this into a documentation issue, and I'll submit a quick comment change to fix it.
