### ISSUE TITLE
<numeric>: Warning about integer promotion in `std::adjacent_difference`

### ISSUE THREAD

**Issue by miscco** [microsoft/STL#4038]
# Describe the bug

When passing an array of `char` to `std::adjacent_difference` one gets a warning:
```
C:/data/msvc/14.38.32919-Pre-v1/include\numeric(491): warning C4244: '=': conversion from 'int' to 'char', possible loss of data
C:/data/msvc/14.38.32919-Pre-v1/include\numeric(491): note: the template instantiation context (the oldest one first) is
<source>(7): note: see reference to function template instantiation '_OutIt *std::adjacent_difference<char*,char*>(const _InIt,const _InIt,const _OutIt)' being compiled
        with
        [
            _OutIt=char *,
            _InIt=char *
        ]
C:/data/msvc/14.38.32919-Pre-v1/include\numeric(506): note: see reference to function template instantiation '_OutIt *std::adjacent_difference<_InIt,_OutIt,std::minus<void>>(const _InIt,const _InIt,_OutIt,_BinOp)' being compiled
        with
        [
            _OutIt=char *,
            _InIt=char *,
            _BinOp=std::minus<void>
        ]
Compiler returned: 0
```

See https://godbolt.org/z/dMj5M677v

The underlying issue is that in `std::minus<>{}` happens an integer promotion to `int`. We could avoid that issue by passing in the proper value type of the input sequence `std::minus<_Iter_value_t<_InIt>>{}`

See https://godbolt.org/z/b5qP86dTE

**Comment by CaseyCarter** [comment]
I don't think we could do this always, it would be observable. We probably could get away with `std::minus<_Remove_cvref_t<_Iter_ref_t<_InIt>>>` when `_Iter_ref_t<_InIt>` is `char`/`unsigned char`/`signed char`/`signed short`/`unsigned short`, though.

**Comment by StephanTLavavej** [comment]
We talked about this at the weekly maintainer meeting. This is a tricky case because our usual philosophy is to suppress warnings in STL-internal code, but not to suppress warnings when the user has asked the STL to perform some operation on their behalf, because merely getting the STL to do it doesn't make it safe. That's generally the case for writing the result of a function object call to an output iterator.

This specific case is tricky because if the user directly wrote `*out_char_ptr = *in_char_ptr_1 - *in_char_ptr_2`, the compiler's C4244 warning has a special case, where it *doesn't* warn about truncation from promoted `int` back down to `char` because it can directly see the `char` input operands. However, if the result of a function call is written to `*out_char_ptr`, then the compiler can no longer "see" the source, and will warn about truncation from `int` to `char`, which is what happens with transparent `minus<>`.

Suppressing the warning in this and other STL algorithms would be too aggressive for the reasons mentioned above. Changing the type given to the `minus` operator functor, as @CaseyCarter mentioned, would be tricky (and as we observed during the maintainer meeting, the decision couldn't be made purely based on the type of the input iterator, as the output iterator could be some type that notices when a `char` versus an `int` is being written to it). We think it's reasonable to ask the user to locally suppress truncation warnings in cases like this, as the least bad option.
