### ISSUE TITLE
`<functional>`: `std::not_fn` can accept non-movable function

### ISSUE THREAD

**Issue by hewillk** [microsoft/STL#4048]
It seems that `std::not_fn` should reject the following code according to [[func.not.fn]](https://eel.is/c++draft/func.not.fn#2):

> _Mandates_: `is_constructible_v<FD, F> && is_move_constructible_v<FD>` is `true`.

[godbolt](https://godbolt.org/z/45sq67q55):

```cpp
#include <functional>

struct OnlyCopyableFun {
  OnlyCopyableFun() = default;
  OnlyCopyableFun(const OnlyCopyableFun&) = default;
  OnlyCopyableFun(OnlyCopyableFun&&) = delete;
  bool operator()(auto) const;
};

int main() {
  OnlyCopyableFun f;
  auto nf = std::not_fn(f); // only ill-formed in libc++
}
```
Feel free to correct me if I've missed something.
Not quite sure why these standard call wrapper factories (`std::bind_front`, `std::bind`, etc.) _require_ all argument types to be move-constructible, although the call wrapper produced in the above example is _still_ move-constructible as its underlying type has a copy constructor. 
It seems to me that just requiring `is_constructible_v<FD, F>` is enough, which is what the range adaptor object does.

**Comment by frederick-vs-ja** [comment]
I think we should file an LWG issue to reduce the _Mandates_ and _Preconditions_ of these functions.

**Comment by StephanTLavavej** [comment]
@CaseyCarter noted that the Standard (via the "call wrapper" phrase of power that I forgot about) requires `not_fn()` to produce something that's Cpp17MoveConstructible, so the *Mandates* on it makes sense and its presence isn't a defect.

N4958 \[func.require\]/3: "Every call wrapper meets the *Cpp17MoveConstructible* and *Cpp17Destructible* requirements. An *argument forwarding call wrapper* is a call wrapper [...]"

/4: "A *perfect forwarding call wrapper* is an argument forwarding call wrapper that [...]"

\[func.not.fn\]/4 "*Returns:* A perfect forwarding call wrapper"

Therefore, this is an implementation issue where we should be `static_assert`ing explicitly, instead of assuming that the implementation will "naturally diagnose" the requirement which is not the case here.
