### ISSUE TITLE
<format>: windows defender detect trojan

### ISSUE THREAD

**Issue by luckyweNda** [microsoft/STL#4128]
# Describe the bug
I debug a sample code from https://en.cppreference.com/w/cpp/utility/format/format, but windows defender block ,and report it is a trojan
![535aa09c2f317d33277def06aa915f3a](https://github.com/microsoft/STL/assets/70629889/6adde569-6eb0-40aa-a4c3-f8553332d49f)
![4175fd45caf5af50df21ca6386161777](https://github.com/microsoft/STL/assets/70629889/24b56efb-013f-4693-b5f4-5ffafbaa637e)

# Command-line test case
``` cpp
#include <format>
#include <iostream>
#include <string>
#include <string_view>
 
template <typename... Args>
std::string dyna_print(std::string_view rt_fmt_str, Args&&... args) {
    return std::vformat(rt_fmt_str, std::make_format_args(args...));
}
 
int main() {
    std::cout << std::format("Hello {}!\n", "world");
 
    std::string fmt;
    for (int i{}; i != 3; ++i) {
        fmt += "{} "; // constructs the formatting string
        std::cout << fmt << " : ";
        std::cout << dyna_print(fmt, "alpha", 'Z', 3.14, "unused");
        std::cout << '\n';
    }
}
```
press F5 in vscode
```
 *  Executing task: C/C++: cl.exe build active file 

Starting build...
cl.exe /Zi /EHsc /std:c++latest /nologo /FeC:\Users\23761\Desktop\cpp_tour\.test\format.exe C:\Users\23761\Desktop\cpp_tour\.test\format.cpp
format.cpp

Build finished successfully.
 *  Terminal will be reused by tasks, press any key to close it. 
```

debug console
```
-------------------------------------------------------------------
You may only use the C/C++ Extension for Visual Studio Code
with Visual Studio Code, Visual Studio or Visual Studio for Mac
software to help you develop and test your applications.
-------------------------------------------------------------------
Unable to start debugging. Unable to start program 'C:\Users\23761\Desktop\cpp_tour\.test\format.exe'. Not implemented.
```

# Expected behavior
it is not a trojan. should not be block by windows defender

# STL version
** Visual Studio 2022 Developer Command Prompt v17.7.5
** Copyright (c) 2022 Microsoft Corporation

**Comment by StephanTLavavej** [comment]
Thanks for reporting this issue. I was unable to reproduce it with VS 2022 17.8 Preview 5 x64 and x86 using your exact code and command-line options, running Windows 11 with security intelligence version 1.399.1311.0 (this doesn't appear to be an enterprise version of Windows Defender, but it is my corpnet machine so I'm not 100% sure if this is equivalent to consumer Windows Defender).

In any event, MSVC is unable to do anything about Windows Defender false positives; since you can reproduce the issue, I recommend submitting your generated executable as a malware false positive to https://www.microsoft.com/en-us/wdsi/filesubmission .
