### ISSUE TITLE
`<format>`: failure to reject `basic_format_string` using a non-`integral` precision

### ISSUE THREAD

**Issue by CaseyCarter** [microsoft/STL#4152]
This program:
```c++
#include <format>

int main() {
    char buf[]{};
    (void) std::format("{:.{}}", buf, buf);
}
```
throws `format_error` at runtime since `char*` is not a valid type for a dynamic precision. It _should_ be rejected at compile time since there are no two arguments of type `char*` for which `"{:.{}}"` is a valid format string.

**Comment by frederick-vs-ja** [comment]
Is this addressed by WG21-P2757R3 (#3813)?

**Comment by cpplearner** [comment]
It's more like #2785

**Comment by StephanTLavavej** [comment]
We talked about this at the weekly maintainer meeting and we believe you're both right - this appears to be an exact duplicate of #2785, and is also the exact thing that #3813 addresses (so it is technically by design in C++23).

We thought about closing both of these bugs as dupes (leaving the C++26 feature as the primary), but we're holding off for now as @mordante (a libc++ maintainer) claimed in Discord that microsoft/STL is behaving incorrectly for C++23 here, so we want to understand that rationale.

**Comment by CaseyCarter** [comment]
I disagree this behavior is by design in C++23. [format.fmt.string]/3 clearly states that "A call to [`basic_format_string`'s converting constructor] is not a core constant expression unless there exist `args` of types
`Args` such that str is a format string for `args`." For `basic_format_string<char, char*, char*>`, there are no possible argument values for which `"{:.{}}"` is a valid format string.

Closing as duplicate of #2785.
