### ISSUE TITLE
Difference in `std::unique_ptr<Incomplete>` between `/std:c++20` and `/std:c++latest`

### ISSUE THREAD

**Issue by jovibor** [microsoft/STL#4215]
This code compiles just fine in MSVS 17.8 with the `/std:c++20`
```cpp
//MyClass.h
#pragma once
#include <memory>

class Incomplete;

class MyClass {
public:
	MyClass();
	~MyClass();
	std::unique_ptr<Incomplete> p { std::make_unique<Incomplete>() };
};
```
```cpp
//MyClass.cpp
#include "MyClass.h"

class Incomplete { }; //Completed here.

MyClass::MyClass() { }

MyClass::~MyClass() { }
```
```cpp
//main.cpp
#include "MyClass.h"

int main()
{
	MyClass var;
}
```

But with the `/std::c++latest` it spits out lots of errors:
```cpp
memory(3169,27): error C2027: use of undefined type 'Incomplete'
memory(3169,25): error C2338: static_assert failed: 'can't delete an incomplete type'
memory(3170,9): warning C4150: deletion of pointer to incomplete type 'Incomplete'; no destructor called
```

Which mode is right?

**Comment by cpplearner** [comment]
The destructor of `unique_ptr` is `constexpr` since C++23, which causes it to be instantiated more eagerly. IIUC It's effectively the same problem as in #2720.

**Comment by StephanTLavavej** [comment]
Thanks for the analysis @cpplearner! We talked about this at the weekly maintainer meeting and agree - both the compiler and library are working by design here.

@jovibor It appears to us that you'll need to workaround this new Standard behavior by avoiding the data member initializer here. If you change `MyClass`'s constructor definition to use a classic mem-initializer-list with `: p(std::make_unique<Incomplete>())` then that should work perfectly as the type is complete there.
