### ISSUE TITLE
std::thread throw an exception, main thread can't make dmp

### ISSUE THREAD

**Issue by illidanstormrange** [microsoft/STL#4246]
I allways use Windows Function `SetUnhandleExceptionFilter` to handle process exception, but wen i handle thread exception, find it's not work. here is the code
```C++
#include <thread>
#include <Windows.h>

std::unique_ptr<std::thread> g_thread;

static LONG WINAPI handleExcept(EXCEPTION_POINTERS* p)
{
    printf("handle exception\n");
    return EXCETPION_CONTINE_SEARCH;
}
void crash_thread_throw()
{
    g_thread.reset(new std::thread([](){
        throw "";
    }));
}

void crash_thread_ptr()
{
    g_thread.reset(new std::thread([](){
        int* a = nullptr;
        a[0] = 1;
    }));
}

int main()
{
    auto filter = SetUnhandleExceptionFilter(handleExcept);
    crash_thread_throw();
    // crash_thread_ptr(); // this can be handle
    return 0;
}
```

**Comment by illidanstormrange** [comment]
![image](https://github.com/microsoft/STL/assets/51289228/f1fdd148-acb8-4a8c-a10f-a454981eb03d)
here is the stack

**Comment by StephanTLavavej** [comment]
@illidanstormrange Can you please provide the exact code and exact command line you're using? Your original example contains a typo (`EXCETPION_CONTINE_SEARCH`) so it can't have been what was compiled. This will help us investigate.

**Comment by fsb4000** [comment]
@StephanTLavavej , original code has 2 typos.

`EXCETPION_CONTINE_SEARCH` => `EXCEPTION_CONTINUE_EXECUTION`

`SetUnhandleExceptionFilter` => `SetUnhandledExceptionFilter`

```c++
#include <thread>
#include <Windows.h>

std::unique_ptr<std::thread> g_thread;

static LONG WINAPI handleExcept(EXCEPTION_POINTERS* p)
{
    printf("handle exception\n");
    return EXCEPTION_CONTINUE_EXECUTION;
}
void crash_thread_throw()
{
    g_thread.reset(new std::thread([](){
        throw "";
    }));
}

void crash_thread_ptr()
{
    g_thread.reset(new std::thread([](){
        int* a = nullptr;
        a[0] = 1;
    }));
}

int main()
{
    auto filter = SetUnhandledExceptionFilter(handleExcept);
    crash_thread_throw();
    // crash_thread_ptr(); // this can be handle
    g_thread->join();
    return 0;
}
```

it doesn't need any flags and it can be compiled with 

```
cl test.cpp
```

**Comment by illidanstormrange** [comment]
fsb4000 is right, I didn't copy the code, I typed it by hand, so there was a problem with the spelling.@StephanTLavavej

**Comment by Fulgen301** [comment]
You're throwing a C++ exception, which is subject to C++ `noxcept` rules. `std::thread::_Invoke`, the thread procedure for `_beginthreadex`, is `noexcept`, so `std::terminate` will be called on an exception, which ultimately results in `STATUS_FATAL_APP_EXIT` which can't be caught with an unhandled exceptiion filter.

https://github.com/microsoft/STL/blob/a8888806c6960f1687590ffd4244794c753aa819/stl/inc/thread#L56C35-L56C35

And even if `_Invoke` wasn't `noexcept`, the UCRT is almost certainly compiled with `/EHsc` (`extern "C"` implies `noexcept`), so a C++ exception wouldn't be handed down to the unhandled exception filter anyway.

**Comment by AlexGuteniev** [comment]
I thin k it used to work in some of previous Visual Studio versions.

I can agree with @Fulgen301 that this is standard, but I don't like this behavior either.

**Comment by illidanstormrange** [comment]
> the thread procedure for _beginthreadex, is noexcept, so std::terminate will be called on an exception, which ultimately results in STATUS_FATAL_APP_EXIT which can't be caught with an unhandled exceptiion filter.

`AddVectoredExceptionHandler` can handle this, but i don't know the underlying logic of it, So I'm not sure if it's the opposite of what you say.

**Comment by Fulgen301** [comment]
[Vectored exception handlers are called from where the SEH exception is thrown before the stack is being unwound or any frame handlers are called.](https://learn.microsoft.com/en-us/windows/win32/debug/vectored-exception-handling) Note that that includes both C++ and SEH exceptions that may actually be caught with `try` - `catch` / `__try` - `__except`.

On the contrary, the unhandled exception filter is only called on unhandled exceptions. From a C++ point of view, the exception travels up the stack until it hits the `noexcept` from the thread procedure which results in `std::terminate` being called. This is the behavior the C++ standard mandates. However, from a SEH point of view, there is no unhandled exception in that chain - it travels up the stack until the frame handler that is the `noexcept` machinery handles it. If that thread procedure wasn't `noexcept` (violating the C++ standard) and the thread procedure caller in the UCRT wasn't `noexcept` either (fun with ABI since you're now throwing exceptions over a DLL boundary if the CRT is linked dynamically), `_seh_filter_exe` / `_seh_filter_dll` would be called, which doesn't handle the C++ exception SEH code, so the SEH exception would ultimately end up unhandled, causing the unhandled exception filter to be called.

**Comment by StephanTLavavej** [comment]
We talked about this at the weekly maintainer meeting and we agree with @Fulgen301 - this behavior is by design and mandated by the C++ Standard.
