### ISSUE TITLE
Strange behavior with vectors.

### ISSUE THREAD

**Issue by antoinech13** [microsoft/STL#4333]
hello,

I encountered a strange behavior with vectors, and I don't really know what is going on. I'm sorry if this is not the right section to post this. If someone can explain it to me, I would greatly appreciate it.

here my function: 

`void patternsRecoAlignement::Corrector::__buildPatterns() {

	for (int i = 0; i < this->sequence->size(); i++) {

		this->stars->at(i) = *this->sequence->getStars(i);
		patternsRecoAlignement::dataStructures::Pattern* p = nullptr;
		
		for (int j = 0; j < this->stars->at(i).size(); j++) {

			std::vector<std::pair<float, float>>* closestStars = this->__findClosestStars(i, j);
			std::vector<patternsRecoAlignement::dataStructures::Triangle>* triangles = this->__buildTriangles(closestStars);
			
			p = new patternsRecoAlignement::dataStructures::Pattern(triangles);
			this->patterns->at(i).push_back(*p); // this line is the problem
			
			delete closestStars;

		}
		
	}

}`

my problem is with the like this->patterns->at(i).push_back(*p) where patterns is a vector<vector<pattern>> *:

 `_CONSTEXPR20 _Ty exchange(_Ty& _Val, _Other&& _New_val) noexcept(
    conjunction_v<is_nothrow_move_constructible<_Ty>, is_nothrow_assignable<_Ty&, _Other>>) {
    // assign _New_val to _Val, return previous _Val
    _Ty _Old_val = static_cast<_Ty&&>(_Val);
    _Val         = static_cast<_Other&&>(_New_val);
    return _Old_val;
}`

i put here the stake of calls:

![image](https://github.com/microsoft/STL/assets/57111263/8e38a8c7-9b05-4d7a-8cd3-73654b97bef3)

when I try to debug:

for i =0, j =0 i get:

![image](https://github.com/microsoft/STL/assets/57111263/9cf9d500-210d-4c58-bccc-0f843b9e151d)

but for i = 0, j = 1: 

![image](https://github.com/microsoft/STL/assets/57111263/1de875b4-24a3-4252-a72e-25f70bfd0804)

As you can see, the first element has a size of 0. I don't know why, but it seems like push_back deallocated my first object. It's my first project with C++, so I'm probably doing something wrong, but I really don't understand what is going on with this vector.

Thank you for your help.

**Comment by StephanTLavavej** [comment]
It's hard to tell from a snippet instead of a self-contained example, but it looks like you're getting a pointer to a `vector` element, which is then being invalidated during `vector` reallocation. `vector` owns a block of memory, with a `size()` (number of actually existing elements) that's less than or equal to its `capacity()` (number of elements that can potentially be stored in the current memory block). If you `push_back()` into a `vector` when it has no unused capacity, it must reallocate, which means allocating a larger memory block, moving all existing elements there, and deallocating the old memory block. This is handled for you behind the scenes, but it means that any pointers to elements are *invalidated*, because the elements in the old memory block have been destroyed.

You need to write your code in order to avoid assuming that pointers to `vector` elements will remain perpetually valid. (In some cases, storing indices into a `vector` instead of pointers to its elements is reasonable.)

As an aside, using raw `new` and `delete` is difficult and should be avoided. (It's appropriate in expert-level code implementing data structures.)

> I'm sorry if this is not the right section to post this.

This repo is for STL development, not STL usage, so issues should be reported only when you're confident that you're looking at an STL implementation bug. While beginners are the future of C++ (welcome! :smile_cat:), we don't have the capacity to help teach how to use the STL here (I am replying on the weekend because I have nothing better to do, heh). I recommend other forums like Stack Overflow or the r/cpp_questions subreddit. You can also join the STL Discord (linked at the top of our readme) and ask for help in our off-topic `#non-stl` channel, if you like (the other channels are for STL development).
