### ISSUE TITLE
Should we consistently use `__cpp_char8_t` or `__cpp_lib_char8_t`?

### ISSUE THREAD

**Issue by frederick-vs-ja** [microsoft/STL#4400]
MSVC STL supports C++20/23 without `char8_t` and C++14/17 with `char8_t` dialects (see #2748). As a result, availability of some components is controlled by feature-test macros rather than standard revisions.

However, there doesn't seem a general whether the predefined feature-test macro `__cpp_char8_t` or the library feature-test macro `__cpp_lib_char8_t` should be used for controlling, and both of them are currently used.
https://github.com/microsoft/STL/blob/c53ac59abae552e50654943f7f80f23376a8039a/stl/inc/xstring#L482-L485
https://github.com/microsoft/STL/blob/c53ac59abae552e50654943f7f80f23376a8039a/stl/inc/xstring#L1789-L1791

Presumably we should consistently use one for controlling.

**Comment by StephanTLavavej** [comment]
There was a rationale behind this scheme. I'll get more details for you.

**Comment by StephanTLavavej** [comment]
The rationale is that [`/Zc:char8_t`](https://learn.microsoft.com/en-us/cpp/build/reference/zc-char8-t?view=msvc-170) is (perhaps surprisingly) available as an opt-in mode in C++14/17. In the STL, we enable minimal recognition of C++14/17 with `char8_t` by inspecting the compiler macro `__cpp_char8_t`. This is usually in always-available components that need to *react* to `char8_t`'s presence, e.g. the type traits like `is_integral_v`:

https://github.com/microsoft/STL/blob/c53ac59abae552e50654943f7f80f23376a8039a/stl/inc/xtr1common#L187-L193

However, we still don't want to enable C++20 library tech downlevel, so that's what `__cpp_lib_char8_t` guards. We would usually use plain `_HAS_CXX20` guards, except that `/Zc:char8_t-` acts as an *opt-out* here. So that's why library tech like `u8string_view` is guarded this way:

https://github.com/microsoft/STL/blob/c53ac59abae552e50654943f7f80f23376a8039a/stl/inc/xstring#L1789-L1791
