### ISSUE TITLE
<chrono>: Consider caching QueryPerformanceFrequency()

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#448]
`steady_clock::now()` says:

https://github.com/microsoft/STL/blob/a83d8c0061eca6e22d1de0963dfbbdb916f91267/stl/inc/chrono#L612-L614
https://github.com/microsoft/STL/blob/a83d8c0061eca6e22d1de0963dfbbdb916f91267/stl/src/xtime.cpp#L92-L96

As the comment indicates, [QueryPerformanceFrequency](https://docs.microsoft.com/en-us/windows/win32/api/profileapi/nf-profileapi-queryperformancefrequency) documentation says: "The frequency of the performance counter is fixed at system boot and is consistent across all processors. Therefore, the frequency need only be queried upon application initialization, and the result can be cached."

This code originally used magic statics, but TFS checkin 1586419 on March 16, 2016 removed that. My checkin notes claimed (emphasis added):

> Remove intentional but unnecessary use of magic statics in `steady_clock::now()` calling `_Query_perf_frequency()`. Calling QPC is very fast (when I originally profiled `now()`, IIRC I could call it 6-7 times before the tick changed). **Calling QPF will be comparably fast,** so we may as well just do that instead of paying the magic statics cost. I've left the "system boot" comment, since it's helpful to know.

I had no evidence for this performance assumption and it was incorrect. In DevCom-505019, where this issue was originally reported, Damian Zwoliński noted that while QPC is indeed efficient on most platforms (aside: IIRC, on certain VMs it is expensive), QPF is not efficient.

We're avoiding magic statics for a reason (its use of Thread Local Storage is problematic for some users), but we should investigate whether it's possible to restore caching without TLS and without breaking ABI. For example, we could have a static `long long` initialized to `0` (no magic) and use interlocked operations to cache QPF, since `0` is never a valid value for it.

**Comment by jwtowner** [comment]
Hi! Agree, with the use of a global `long long`, but no need to use interlocked operations or any form of hardware memory fences, since you don't need to synchronize access to any other state in relation to the variable. All you need to do is guarantee atomicity of the load and store operations. It's alright if multiple threads end up racing independently in an attempt to initialize it. 

So, it should be sufficient to use equivalent of only the `load()` and `store()` operations on an `std::atomic<long long>` with `std::memory_order_relaxed` ordering.

I believe .NET Core uses this same technique deep in the internals of System.Threading.SpinWait to record a measurement of the time that the x86 PAUSE instruction takes, since this can vary depending on the architecture (for example, Skylake's PAUSE takes much longer than previous Intel microarchitectures). It doesn't use interlocked operations, atomics, or locking since I believe the C# memory model for loads/stores on non-volatile variables of types `bool`, `char`, `byte`, `sbyte`, `short`, `ushort`, `uint`, `int` and `float` is basically the same as `std::memory_order_relaxed`.

**Comment by AlexGuteniev** [comment]
Other thing to consider for this area:

https://github.com/microsoft/STL/blob/a83d8c0061eca6e22d1de0963dfbbdb916f91267/stl/inc/chrono#L616-L619

There's `_mul128` and `_div128` for x64.

By replacing highlighted code with the following:
```
#ifdef _M_X64
            long long _High;
            long long _Rem_unused;
            long long _Low = _mul128(period::den, _Ctr, &_High);
            long long _Res = _div128(_High, _Low, _Freq, &_Rem_unused);
            return time_point(duration(_Res));
#else
          // old code
#endif
```
Can have one division instead of two.

But on my system QPC takes most of the time.
I'm proposing to consider this, since there are apparently systems where QPC is faster.

It also may be not worth of trouble bringing intrinsic functions to that header. 
And digging it into .cpp is API change.

**Comment by AlexGuteniev** [comment]
Looked at this once more:
https://github.com/microsoft/STL/blob/a83d8c0061eca6e22d1de0963dfbbdb916f91267/stl/inc/chrono#L616-L618

I think `_Ctr` and `period::den` can be swapped. This would result in:
```
  const long long _Whole = (period::den / _Freq) * _Ctr;
  const long long _Part  = ((period::den % _Freq) * _Ctr) / _Freq;
  return time_point(duration(_Whole + _Part));
```
`period::den / _Freq` and `period::den % _Freq` are cache-able, so it is possible to have just one division on any system:
```
   // pseudocode, sure no magic static in real code
  static const [_Quot, _Rem] = lldiv(period::den, _Freq);
  const long long _Whole = _Quot * _Ctr;
  const long long _Part  = (_Rem * _Ctr) / _Freq;
  return time_point(duration(_Whole + _Part));
```

As a bonus: There are cases where `QueryPerformanceFrequency` always gives `10000000` value. For those systems, the dividend is zero, this makes the division part very fast.

**Comment by MikeGitb** [comment]
> We're avoiding magic statics for a reason (its use of Thread Local Storage is problematic for some users)

Maybe a bit off topic, but why do magic statics need thread local storage?

**Comment by BillyONeal** [comment]
@MikeGitb The 'Magic Statics' algorithm uses a thread-local read to see 'did this thread already see that this value' to avoid synchronization if the current thread has already seen that the value is initialized.

**Comment by AlexGuteniev** [comment]
(If we started this off-topic) what are reasons to avoid TLS ?  I recall there are issues with .NET, but this can be ruled out by preprocessor.  There was dll in XP problem, but XP is no longer there. Some more exotic, like kernel mode drivers, executable packers / protectors, malware ? This STL is not suited for such scenarios anyway.

**Comment by BillyONeal** [comment]
Adding a .TLS section to a DLL that previously didn't have one can push a program over the TLS slot limit, so it's a breaking change.

**Comment by AlexGuteniev** [comment]
TLS slot limit? I though the algorithm that exists since Vista has no limits, it would reallocate TLS as many times as needed.

**Comment by AlexGuteniev** [comment]
(Sure such TLS reallocation may be heap expensive for a program with many threads, and many DLLs already loaded, and may cause reaching heap limit on x86, but then any adding change can cause that)

**Comment by BillyONeal** [comment]
@AlexGuteniev My understanding is the limit in Vista was changed from ~58 to ~1000ish but that there is still a limit.
