### ISSUE TITLE
<random>: uniform_*_distribution Not Satisfy RandomNumberDistribution Named Requirements

### ISSUE THREAD

**Issue by c0nstexpr** [microsoft/STL#4679]
# Describe the bug
`uniform_int_distribution::param()` member is inherited from `uniform_int`. 
https://github.com/microsoft/STL/blob/8dc4faadafb52e3e0a627e046b41258032d9bc6a/stl/inc/random#L2140
Thus the return type is `uniform_int::param_type` not `uniform_int_distribution::param_type`, which conflicts [RandomNumberDistribution](https://timsong-cpp.github.io/cppwp/rand.req.dist#tab:rand.req.dist).

**Comment by frederick-vs-ja** [comment]
The correct `param` function is now here, which is not inherited from `uniform_int`.
https://github.com/microsoft/STL/blob/8dc4faadafb52e3e0a627e046b41258032d9bc6a/stl/inc/random#L2264-L2266

Same for `uniform_real_distribution`.
https://github.com/microsoft/STL/blob/8dc4faadafb52e3e0a627e046b41258032d9bc6a/stl/inc/random#L3155-L3157

The issue was existing before but fixed in #4284. You can use [VS 2022 17.10](https://github.com/microsoft/STL/wiki/Changelog#vs-2022-1710-preview-2) to check the status.
