### ISSUE TITLE
`<execution>`: Should threadpool callback priority be influenced by parent thread priority?

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#4781]
Our C++17 parallel algorithms use the Windows threadpool:

https://github.com/microsoft/STL/blob/165fc9459c85faa65cd3dec313eb10f55bab154c/stl/inc/execution#L213
https://github.com/microsoft/STL/blob/165fc9459c85faa65cd3dec313eb10f55bab154c/stl/src/parallel_algorithms.cpp#L23-L26

We're passing null to [`CreateThreadpoolWork`](https://learn.microsoft.com/en-us/windows/win32/api/threadpoolapiset/nf-threadpoolapiset-createthreadpoolwork) for the callback environment:

> If this parameter is NULL, the callback executes in the default callback environment. For more information, see [`InitializeThreadpoolEnvironment`](https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-initializethreadpoolenvironment).

Therefore, the threadpool callbacks have default priority, regardless of the parent thread priority.

Think-cell reported this to us, raising the concern of priority inversion.

In theory, we could alter our code to set up a callback environment, and use [`SetThreadpoolCallbackPriority`](https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-setthreadpoolcallbackpriority) to request low, normal, or high priority. However, it is unclear to me whether "The priority for the callback relative to other callbacks in the same thread pool." would control the priority relative to the parent thread, which is what would be needed to address priority inversion concerns.

Ultimately, the conclusion may be that thread priority is outside the realm of the Standard, so if an application has used the Windows API to alter its thread priorities, then the C++17 parallel algorithms are a poor fit for it.

**Comment by wanghan02** [comment]
In our tests, setting the thread priority in the callback to the thread priority of the parent thread, and restoring it on exit of the callback works, does not have a big overhead, and makes a significant difference in the performance of UI thread running simultaneously. Doing it once per range item is obviously inefficient, but once per callback is probably fine and potentially helps a lot.

**Comment by AlexGuteniev** [comment]
> Doing it once per range item is obviously inefficient, but once per callback is probably fine and potentially helps a lot

This semi-defeats the purpose of parallel algorithms by adding heavy (though constant time) operation to each callback, and making scheduling callbacks less efficient. Though if you won't do it for normal priority parent thread, the normal case won't be penalized, so it may be fine.

(I wouldn't want even `GetThreadPriority()` of parent thread penalty, but that's not my call)

**Comment by AlexGuteniev** [comment]
> Many interactive applications, which is arguably the majority of applications on Windows, will use thread priorities to make the UI thread more responsive

This doesn't sound as anything common or widespread. I never encountered such a recommendation, or seen the code of an UI application that actually does this.

**Comment by schoedl** [comment]
Well, maybe they should because it makes the UI thread 3x faster. There is nothing special about what we are doing, besides both UI and background being CPU-bound. I have no reason to believe other applications would not get a similar result.

**Comment by StephanTLavavej** [comment]
We talked about this at the weekly maintainer meeting and we don't believe that any changes should be made here.

Having threadpool callbacks manually adjust the priority of threadpool worker threads (which the STL has not directly created, and could be reused by other components) would "contaminate" the thread pool, which seems undesirable. Even if the callback attempts to restore the threadpool worker thread's priority, because the STL isn't directly controlling how callbacks are executed in the threadpool, the chance for unwanted interactions seems high.

It sounds to us like C++17 parallel algorithms are a poor fit for your scenario (because of the Standard's lack of recognition of thread priority), and/or other designs should be investigated - e.g. a UI thread probably shouldn't start a parallel algorithm and block on its completion, instead that scenario sounds like it's suited for promises/futures, so that the UI thread can periodically check whether the long-running operation is complete, and display a placeholder/spinner/etc. while the operation is running.

**Comment by AlexGuteniev** [comment]
> There is nothing special about what we are doing, besides both UI and background being CPU-bound

Well, that sounds special. To make the UI responsive, you avoid making UI thread CPU-bound. From my experiences, this has always been feasible, even when showing quasi-relatime 60 fps chart. I acknowledge that this may be not feasible for your case, but this is definitely not a problem encountered by most of application, not something usual.

**Comment by wanghan02** [comment]
> Having threadpool callbacks manually adjust the priority of threadpool worker threads (which the STL has not directly created, and could be reused by other components) would "contaminate" the thread pool, which seems undesirable. Even if the callback attempts to restore the threadpool worker thread's priority, because the STL isn't directly controlling how callbacks are executed in the threadpool, the chance for unwanted interactions seems high.

In [Thread Pools.Best Practices.3](https://learn.microsoft.com/en-us/windows/win32/procthread/thread-pools#:~:text=Clean%20up%20all%20resources%20created%20in%20the%20callback%20function%20before%20returning%20from%20the%20function.%20These%20include%20TLS%2C%20security%20contexts%2C%20thread%20priority%2C%20and%20COM%20registration.%20Callback%20functions%20must%20also%20restore%20the%20thread%20state%20before%20returning.), it says user should restore thread priority before returning from the call back function. If modifying thread priority in the call back would "contaminate" the thread pool, it should be forbidden instead of restoring the original thread priority as in the best practices.

> Clean up all resources created in the callback function before returning from the function. These include TLS, security contexts, thread priority, and COM registration. Callback functions must also restore the thread state before returning.

The problem we are facing is that, parallel algorithms from c++17 should be able to handle CPU-bound tasks gracefully. If we have a low priority background thread doing some CPU-bound work and it calls a parallel algorithm, this parallel algorithm should **NOT** simply dispatch the work loads onto THREAD_PRIORITY_NORMAL threads. The current implementation with Thread Pool does so which makes those supposed-to-be low priority work loads from low priority background thread

- win the competition against other low priority threads which greatly delays other low priority threads, and
- compete against other normal priority threads which makes those normal priority threads much slower. 
    
I can see that modifying the thread priority in each call back function is not the most efficient thing and even the impact of the modification is not clear or at least well documented. But throwing everything onto the threads (which are THREAD_PRIORITY_NORMAL) of the Thread Pool is simply wrong. If Thread Pool cannot handle it gracefully we need another implementation. As a workaround, we found that modifying thread priority in the call back function work as expected even though it's not perfect.
