### ISSUE TITLE
<mutex>: Problem using mutex with pybind.

### ISSUE THREAD

**Issue by zizhang-qiu** [microsoft/STL#4875]
# Describe the bug
I use std::lock_guard and std::unique_lock in my code and use pybind to generate python library.
The program crashed in python but not in C++.

# Command-line test case
```
C++
#include "pybind11/pybind11.h"
#include <mutex>
class ThreadSafeCounter {
 public:
  ThreadSafeCounter() : count(0) {}

  void increment() {
    std::lock_guard<std::mutex> guard(mutex_);
    ++count;
  }

  int get() const {
    std::lock_guard<std::mutex> guard(mutex_);
    return count;
  }

 private:
  mutable std::mutex mutex_;
  int count;
};

PYBIND11_MODULE(pybindtest, m) {
  py::class_<ThreadSafeCounter>(m, "ThreadSafeCounter")
      .def(py::init<>())
      .def("increment", &ThreadSafeCounter::increment)
      .def("get", &ThreadSafeCounter::get);
}

Python
import pybindtest
counter = pybindtest.ThreadSafeCounter()
counter.increment()
print(counter.get())
```

# Expected behavior
The python program should run successfully and output "1".

# STL version
Microsoft Visual Studio Community 2022
Version 17.10.5

# Additional context
I switch to visual studio 2019 and this bug disappears.
Microsoft Visual Studio Professional 2019
Version 16.11.38

**Comment by AlexGuteniev** [comment]
Looks like #4730 

You need to make sure Python uses the latest C++ runtime library.

**Comment by zizhang-qiu** [comment]
Thanks. I don't know how to  make sure Python uses the latest C++ runtime library, but I solved this by adding the macro `_DISABLE_CONSTEXPR_MUTEX_CONSTRUCTOR` in my CMakelist.

**Comment by StephanTLavavej** [comment]
Yep, thanks @AlexGuteniev. Ideally this should be reported upstream (to pybind?), if they aren't redistributing a sufficiently new VCRedist (either system-wide or app-local), assuming this issue is in pybind itself and not in the usage of it. While our documented requirement is to have an equal or newer version, in this case one can physically get away with a VCRedist as old as VS 2022 17.8 being used with VS 2022 17.10's headers, so the VCRedist has to be quite old in order for this to be a problem.
