### ISSUE TITLE
GitHub: Consider using Projects

### ISSUE THREAD

**Issue by miscco** [microsoft/STL#490]
Github Projects help keeping track of larger epics that are going on. 

Rather than having everything only inside the issues tab one could split the larger blocks into well defined blocks. From the top of my head I would come up with the following categories

* Language Support C++20 (or C++23 when it is time)
* vNext
* Bugs
* Enhancements

It would not be necessary that everything is inside a project but I believe that this would greatly help with visibility and avoiding duplicated work as that is better tracked there as through labels

**Comment by StephanTLavavej** [comment]
This is a neat idea and I’ll look into it.

**Comment by StephanTLavavej** [comment]
Ok, we've started using both Milestones and Projects.

@cbezault set up a [Conformance Milestone](https://github.com/microsoft/STL/milestone/1), tracking all `cxx20` features and `lwg` issues (excluding `vNext`). In the future, when we start working on the `vNext` branch, we'll probably set up a corresponding Milestone. At this time, we don't have any Milestones for bugs/performance improvements/etc. but we're open to ideas. (I could imagine focused Milestones for specific areas that need bugfixes or perf work - e.g. we have groups of `<locale>`, `<random>`, `<regex>` bugs that might be best to tackle in groups.)

I just set up a [Code Reviews Project](https://github.com/microsoft/STL/projects/1), adding visibility to the workflow that we've already been informally following. It's semi-automated and should be easy for us to maintain in the future, since it'll directly drive what we're reviewing.

If you have any more suggestions, please let us know! 😺

**Comment by AlexGuteniev** [comment]
Is excluding "LWG issue needed" from the milestone a bit of cheating?

**Comment by StephanTLavavej** [comment]
There's a distinction between improving our implementation to match the Working Paper, and improving the Working Paper itself. Not a sharp distinction, as resolving `LWG issue needed` is likely to result in an `lwg` issue that needs to be implemented.

In any event, the Milestone is an artificial construct, created purely to guide our work and make understanding our progress easier. Depending on experience and feedback, we'll adapt our use of Milestones accordingly.

**Comment by AlexGuteniev** [comment]
I think I can propose other milestone. You can have GitHub Migration milestone.

https://github.com/microsoft/STL#github-migration-status

**Comment by StephanTLavavej** [comment]
We've created a [GitHub Migration](https://github.com/microsoft/STL/projects/2) project, instead of a milestone, because we don't have issues filed for everything yet, and the work naturally falls into different "columns" instead of a single list. Thanks for the idea!
