### ISSUE TITLE
Vectorize `sort` using Intel library

### ISSUE THREAD

**Issue by AlexGuteniev** [microsoft/STL#4981]
There's https://github.com/intel/x86-simd-sort library available under BSD 3-Clause License.

Can/should we use it?

**Comment by StephanTLavavej** [comment]
At this time, the only licensing that we're automatically comfortable with (because we've used it before) is Apache License v2.0 with LLVM Exception and the Boost Software License. Any other license would require review on our side, which is a time-consuming process.

It appears to us that BSD 3-Clause has the cascading attribution issue (like MIT), so it would *not* be acceptable as an STL dependency. (We are definitely-not-a-lawyer-cat, but it's fairly safe to say when we think that something *wouldn't* work.)
