### ISSUE TITLE
`<vector>`: `assign_range()` is missing Mandates

### ISSUE THREAD

**Issue by hewillk** [microsoft/STL#5076]
According to [[sequence.reqmts]](https://eel.is/c++draft/containers#sequence.reqmts-60), `a.assign_range(rg)` has the _Mandates_ of `assignable_from<T&, ranges​::​range_reference_t<R>>` s modeled, however, this is missed in the MSVC-STL implementation.

The following should be rejected:

```cpp
#include <vector>
 
struct Int {
  void operator=(int);
  Int(int);
};

int main() {
  std::vector<Int> v;
  v.assign_range(std::vector{42}); // only libstdc++ rejects
}
```
https://godbolt.org/z/TrGsbcndj

Not sure if other containers have similar issues.

**Comment by CaseyCarter** [comment]
I'm sure I missed enforcing this requirement on the type and value category of the assignment expression for all of the `assign_range` implementations, we should audit.

**Comment by frederick-vs-ja** [comment]
I believe our assignment expressions are fine:

https://github.com/microsoft/STL/blob/25dc2b72b6f594326253cf3a05543f7a5750f802/stl/inc/vector#L1388
https://github.com/microsoft/STL/blob/25dc2b72b6f594326253cf3a05543f7a5750f802/stl/inc/vector#L1446
https://github.com/microsoft/STL/blob/25dc2b72b6f594326253cf3a05543f7a5750f802/stl/inc/deque#L878
https://github.com/microsoft/STL/blob/25dc2b72b6f594326253cf3a05543f7a5750f802/stl/inc/list#L1331
https://github.com/microsoft/STL/blob/25dc2b72b6f594326253cf3a05543f7a5750f802/stl/inc/forward_list#L946

For `vector<bool, A>`, we're using copy-initialization instead of assignment. I think this is still conforming - but if I'm wrong, we need to swich to use `bool _Tmp; _Tmp = *_First;`.

https://github.com/microsoft/STL/blob/25dc2b72b6f594326253cf3a05543f7a5750f802/stl/inc/vector#L3291
https://github.com/microsoft/STL/blob/25dc2b72b6f594326253cf3a05543f7a5750f802/stl/inc/vector#L3314

----

Note that `std::is_assignable_v<Int&, std::ranges::range_reference_t<std::vector<int>&>>` is `true` for your example. So I guess this is arguably a defect in the standard that it's overly strict to use `assignable_from` in _Mandates_ of `assign_range` functions. Perhaps it would be OK to just reuse the well-formedness of `declval<T&>() = *ranges::begin(rg)`.
(`is_assignable_v` can be overly strict when the iterator of `rg` dereferences to a prvalue, the element type of `rg` is not movable, and the `operator=` takes that element type by value.)

**Comment by hewillk** [comment]
>  
> For `vector<bool, A>`, we're using copy-initialization instead of assignment. I think this is still conforming - but if I'm wrong, we need to swich to use `bool _Tmp; _Tmp = *_First;`.
> 
> [STL/stl/inc/vector](https://github.com/microsoft/STL/blob/25dc2b72b6f594326253cf3a05543f7a5750f802/stl/inc/vector#L3291)
> 
> 
>  `const bool _Tmp = *_First;`
>  


`_Container_compatible_range<bool>` guaranteed this is ok, right?

**Comment by frederick-vs-ja** [comment]
Also, `common_reference_with` in `assignable_from` doesn't seem correct to me. I found that it was originally added in ericniebler/stl2#150 (although significantly modified in C++20).

I think when we use `assignable_from` to constrain something, it just corresponds to some assignment expressions where `common_reference_t` is unnecessary.

**Comment by StephanTLavavej** [comment]
We talked about this at the weekly maintainer meeting and we think that adding a bunch of `static_assert`s to enforce these Mandates is quick and easy, with the disclaimer that such `static_assert`s imply nothing about the moral worth of the Standard's yucky requirements :vomiting_face: (which @CaseyCarter wishes he could take back - I am omitting an entire glorious rant about the `assignable_from` concept here :joy_cat:).

**Comment by hewillk** [comment]
Note that `string::assign_range` doesn't have Mandates for this, not sure if this deserves an LWG.

**Comment by CaseyCarter** [comment]
> Note that `string::assign_range` doesn't have Mandates for this, not sure if this deserves an LWG.

Speaking for only myself, I'm more likely to submit an LWG issue to remove the requirement elsewhere than to submit an issue to add it to `basic_string`.
