### ISSUE TITLE
Question about feature test macros usage style

### ISSUE THREAD

**Issue by 2underscores-vic** [microsoft/STL#517]
Hello. I wonder why feature test macros are checked using form
```c++
#ifdef __cpp_feature
```
 while [SD-6](https://isocpp.org/std/standing-documents/sd-6-sg10-feature-test-recommendations#examples) suggests
```c++
#if __cpp_feature
```
?

Note: [The standard states](http://eel.is/c++draft/cpp.cond#11) that all unknown/undefined identifiers are replaced with `0`.

**Comment by StephanTLavavej** [comment]
This is to avoid the wrath of [warning C4668](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-4-c4668?view=vs-2019) "'symbol' is not defined as a preprocessor macro, replacing with '0' for 'directives'".

This is an off-by-default warning (enabled by `/Wall` but not `/W4`), and it warns that the compiler is going to do what the Standard requires it to do. For the former, we're attempting to be increasingly `/Wall` clean these days (see #186). While the latter is often sufficient reason for us to suppress a warning STL-wide, in this case we've chosen not to defend the STL against it, and to ensure that the STL is clean with respect to it. This is because some customers find it valuable to detect typos in preprocessor conditionals, and this provides some value to the STL too - consider `#if KITENS_ARE_YOUNG_CATS`. (Typos in variable names, function names, etc. usually result in compiler errors, so silently compiling and being treated as `0` in the preprocessor is unusually risky.)

**Comment by MikeGitb** [comment]
Btw.: Is that really a SD6 suggestion or just personal style of whoever wrote up the examples?

**Comment by StephanTLavavej** [comment]
It is effectively an SD-6 suggestion, since it’s approved by WG21. If you think that the guidance should be clarified regarding `#if` versus `#ifdef`, I recommend contacting the authors.
