### ISSUE TITLE
constexpr instead of _CONSTEXPR17 in some parts of the code

### ISSUE THREAD

**Issue by maksw2** [microsoft/STL#5193]
things like [this](https://github.com/microsoft/STL/blob/7643c270e5bfb1cfad62f8b5ff4045c662bdaf81/stl/inc/array#L562) feel like defeating the purpose of _CONSTEXPR17. did i notice something or is it intended?

**Comment by CaseyCarter** [comment]
`_CONSTEXPR17` is used to annotate functions that were not `constexpr` in C++14 but became `constexpr` in C++17. The `const` overload of `array::back` was `constexpr` in C++14, but the non-`const` overload was not until C++17. [Cppreference's page for `array::back`](https://en.cppreference.com/w/cpp/container/array/back) illustrates this with it's "constexpr since meow" comments on each overload.
