### ISSUE TITLE
LWG-3379 `safe` in several library names is misleading

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#546]
LWG-3379 `safe` in several library names is misleading

**Comment by SuperWig** [comment]
Just curious, is there any reason why a couple of these LWG issues aren't "good first issue"?

**Comment by CaseyCarter** [comment]
> is there any reason why a couple of these LWG issues aren't "good first issue"?

Generally, I suspect the reason is that @StephanTLavavej wasn't thinking about which things would be good first issues when he was classifying the 109 LWG issues that were approved in Prague. For this particular issue, I may have mentioned that I have the changes implemented in code that will be out for PR soon.

**Comment by StephanTLavavej** [comment]
Yep. Also, we don’t have test automation running yet, so I’ve generally reserved `good first issue` for things that don’t require test changes. Looking forward to lifting that restriction 😸
