### ISSUE TITLE
<charconv>: std::from_chars 1e+1000 should be inf instead of reporting error code

### ISSUE THREAD

**Issue by expnkx** [microsoft/STL#596]
if (_Normal_exponent > _Traits::_Maximum_binary_exponent) {
        // The exponent is too large to be represented by the floating-point type; report the overflow condition:
        _Assemble_floating_point_infinity(_Is_negative, _Result);
        return errc::result_out_of_range; // Overflow example: "1e+1000"
    }
should be inf????

**Comment by expnkx** [comment]
No true

**Comment by StephanTLavavej** [comment]
This is LWG-3081 "Floating point `from_chars` API does not distinguish between overflow and underflow". I sent the following mail to the LWG reflector on May 10, 2019:

I sent a mail to the LWG reflector about this topic last year ("charconv underflow" on Feb 7, 2018), which got some interesting replies but no clear consensus, and Greg Falcon opened this issue on Mar 12, 2018. The last update was on Aug 23, 2018, Batavia issues processing: "Status to Open; Marshall to reword".

I'd like to contribute my implementation experience and suggest different semantics for the PR. When I originally implemented `from_chars()` (derived from our CRT's code), I was still new to floating-point, and didn't have a good sense of how the function should behave. Given the unclear Standardese, I chose to implement "overflow is successful infinity, underflow is successful zero". We've received a highly-voted bug report from users who are unhappy with this behavior. Having spent a year in the floating-point trenches, I agree with them.

I now believe that `from_chars()` should behave like `strtod()` (de facto, if not de jure - as usual, the C Standard is less than maximally helpful). Since LWG-3081 is still not yet resolved, I'm going to change our implementation to "overflow is infinity with `errc::result_out_of_range`, underflow is zero with `errc::result_out_of_range`". This aligns with `strtod()`'s behavior on Windows (and on Unix via Wandbox; I don't know about every conceivable platform). Because this is the only scenario where floating-point `from_chars()` sets `errc::result_out_of_range`, users can detect this output and substitute different values if they so choose (or treat it as an actual error). Finally, this differs from the current Proposed Resolution, which suggests "overflow is `numeric_limits<T>::max()` with `errc::result_out_of_range`". I disagree strongly with that approach, as (1) `strtod()` doesn't do that so it would be novel, and (2) it would say that `"1e1000000"` should be reported as slightly over `10^308` (for 64-bit double) instead of infinity.
