### ISSUE TITLE
<filesystem>: std::filesystem::exists throws exception when checking a path pointing to a non-existing UNC location

### ISSUE THREAD

**Issue by BillyONeal** [microsoft/STL#615]
**Describe the bug**
This is a dual of DevCom-950424. When a host is not found, the system returns `ERROR_BAD_NETPATH` but we don't map that to a file not found error.

**Command-line test case**
```
#include <Windows.h>
#include <iostream>
#include <filesystem>
#include <assert.h>
namespace fs = std::filesystem;

int main()
{
    try
    {
        auto ret = fs::exists(fs::path("//asdfkjhasdfkjhasdf/dfjhasdfj/docs"));
        // Or, use this path:
        //auto ret = fs::exists(fs::path("//*D~!@(*@#$??OC_DIRECTORY=../../docs"));
    }
    catch (fs::filesystem_error & e)
    {
        auto c = e.code();
        auto& cat = c.category();
        if (c.category() == std::system_category() && c.value() == ERROR_BAD_NETPATH) {
            std::cout << "Got bad netpath error\n";
           assert(false);
        }
    }
}
```

**STL version**
Microsoft Visual Studio Professional 2019 Version 16.4.6 VisualStudio.16.Release/16.4.6+29905.134

**Comment by JeanPhilippeKernel** [comment]
@BillyONeal  can you assign me this ?

**Comment by BillyONeal** [comment]
@JeanPhilippeKernel I almost already have it fixed

**Comment by totalgee** [comment]
I'm getting this same exception thrown for `std::filesystem::exists()` when passing in a path like this: `"D:/Some/Path"` on a machine where there is no `D:` drive. (When there is a `D:` drive, then `exists()` will correctly return true or false according to whether the path actually exists there.)

This is on VS 2022 (v143; 17.4.1) with Windows SDK 10.0.22000.0.

**Comment by BillyONeal** [comment]
What is in the exception?

________________________________

**Comment by BillyONeal** [comment]
> in this case getting the fs::status() throws on the same path. 

Right, that's why I'm asking what's in the exception. If the error code is something like "network drive doesn't exist" or whatever we need to add that to the list of error codes to treat as 'not found'. If it's "network I/O error" or similar, then throwing or otherwise reporting an error is correct.

**Comment by totalgee** [comment]
I tried on another machine accessing a drive letter that didn't exist there, and *didn't* get the error thrown there for `exists()` or `status()`.

However, back on the "problematic" machine, I checked and the `filesystem::status()` call returns `file_type::none`, but it sets the `error_code` to `_Myval = 21` (aka `ERROR_NOT_READY`) with category 7 (`_System_addr`).

I don't know why I don't get that same error on another machine, there must be something different in their setups (the one that doesn't throw errors was Windows 10 Pro that migrated to Windows 11, the other with the problem was a clean install of Windows 11 Pro). Both are compiling with VS 2022 17.4.1 and Windows SDK 10.0.22000.0.

**Comment by totalgee** [comment]
Maybe the `__std_win_error` enum should have a new entry added for system error 21 (`ERROR_NOT_READY` --> `_Not_ready`) and this case added to the switch in `__std_is_file_not_found()`?

https://github.com/microsoft/STL/blob/main/stl/inc/xfilesystem_abi.h#L53-L56

**Comment by totalgee** [comment]
Aha! One other interesting note, on further debugging. This **only** happens when I try to access a file on the **D:** drive (which doesn't exist on that machine). If I try other drives, like A:, B: or X: -- which also don't exist on that machine -- the `filesystem::status()` call politely returns `false` and does **not** throw. It only throws when I query status of a file path that starts with "D:" (when there is no D: drive on the machine). Weird...

**Comment by totalgee** [comment]
Finally, I checked in Disk Management (partition manager), and there had been (at some point) a removable disk mounted as `D:` on the machine. So, it still showed up as "*Disk 1: Removable - No Media*" (when the USB was not plugged in), but with drive `D:` assigned to it. I right-clicked the disk to "Change Drive Letter and Paths..." and removed the `D:` assignment. After that, the throw in `fs::exists()` no longer happens, it just returns `false` when asking for a path that starts with `D:`.

Still, it might be nice to add this exception to the logic above in `__std_is_file_not_found()`?

Thanks again.

**Comment by BillyONeal** [comment]
I think `ERROR_NOT_READY` is an I/O error, not a not exists error, so reporting that as an I/O error is appropriate. If you want to treat not-exists and io-error together as not-exists, you need to use the `error_code` overload or catch the resulting exception.

**Comment by totalgee** [comment]
Okay, I thought it was quite similar to the case covered by this issue (`BAD_NETPATH`, which could also happen if a network drive was not mounted at the moment of the call, similar to a USB drive not being connected). But never mind, I've already handled it in my own code, in the way you describe. Thanks for looking into it.

**Comment by Squall-Leonhart** [comment]
This exception also gets thrown if the path is a locked bitlocker protected volume,

**Comment by BillyONeal** [comment]
> This exception also gets thrown if the path is a locked bitlocker protected volume,

That seems correct, since the answer to 'does the path exist' is "we don't know, volume is locked"
