### ISSUE TITLE
<atomic>: atomic<bigger than 8 bytes> is much inferior to other STLs

### ISSUE THREAD

**Issue by ned14** [microsoft/STL#668]
Consider the following repro which turned up at work recently:

```c++
#include <atomic>

struct alignas(64) Foo { int a[16];};

void test_write_large_atomic(std::atomic<Foo> &a, Foo &b) {
#ifndef _MSC_VER
    static_assert(sizeof(std::atomic<Foo>) == sizeof(Foo));
#endif
    a.store(b, std::memory_order_release);
}

Foo test_read_large_atomic(std::atomic<Foo> &a) {
    return a.load(std::memory_order_acquire);
}
```
You can see the difference comparing codegen between MSVC, GCC + libstdc++, and clang + libc++ at https://godbolt.org/z/ctMDVv

- Both GCC and clang do NOT use extra storage for `std::atomic<Foo>` i.e. `static_assert(sizeof(std::atomic<Foo>) == sizeof(Foo));` is true. They use a runtime helper function `__atomic_store` which can accept arrays of bytes arbitrarily long.
- MSVC appears to add a spinlock to the front of the storage. Unfortunately, because `Foo` has alignment of 64 bytes, this swells `sizeof(std::atomic<Foo>)` to 128 bytes, which is not helpful.

Can you please fix the `std::atomic` implementation in future MSVCs (after your next ABI break obviously) to have similar QoI to the `std::atomic` implementation in libstdc++ and libc++?

**Comment by BillyONeal** [comment]
We want the lock to be embedded in the atomic because we want atomic to be usable across standard library instances (e.g. 2 DLLs that each statically link the standard library). We view lack of separately-compiled dependencies as more important than saving that space here.

Notably, libc++ and libstdc++ don't have this problem because they don't allow their customers to statically link or app-locally deploy their standard library.

**Comment by StephanTLavavej** [comment]
I agree with Billy and I believe that this should be resolved as `wontfix`; there is a design tradeoff here and we're comfortable with the existing choice.

**Comment by ned14** [comment]
> We want the lock to be embedded in the atomic because we want atomic to be usable across standard library instances (e.g. 2 DLLs that each statically link the standard library). We view lack of separately-compiled dependencies as more important than saving that space here.

I vaguely remember STL telling me about some mechanism which ensures that singleton instances of `std::system_category` are genuinely unique in the process. Surely the same mechanism could be used here for a 64 byte shared table?

If that is not possible, this is not a large shared state in play here. Me personally, I'd use a local Atom table (`AddAtom`), it's already a user-space implemented hash table so it'll be relatively fast. What I'd do is take the address of the `std::atomic` instance, convert it into hex with a string prepend of "vs_std_atomic_", and if this is the first time that atom is seen, you have the lock. Otherwise loop the call until you get the lock.

So you don't actually need any extra libraries here. Win16 supplies all you need!

> Notably, libc++ and libstdc++ don't have this problem because they don't allow their customers to statically link or app-locally deploy their standard library.

They do permit static linking, though don't encourage it. All our binaries at work are 100% statically linked, because they get deployed onto multiple Linux flavours. I would suspect that this is why their libatomic is a completely separate shared library, as it really does need to be a single copy per process.

Niall

**Comment by BillyONeal** [comment]
> I vaguely remember STL telling me about some mechanism which ensures that singleton instances of `std::system_category` are genuinely unique in the process. Surely the same mechanism could be used here for a 64 byte shared table?

No, there is no such mechanism. We make operator== compare all the different `system_category` instances compare equal but they are still distinct instances. See https://github.com/microsoft/STL/blob/42d5df07d025f1e635ee16f45b6c688394634947/stl/inc/system_error#L109

> What I'd do is take the address of the `std::atomic` instance, convert it into hex with a string prepend of "vs_std_atomic_", and if this is the first time that atom is seen, you have the lock. Otherwise loop the call until you get the lock.

That would break deploying the STL in environments where user32 is not present, such as Nano Server or XBox. And it's to optimize a case where arguably the caller did something that asked for bad perf; create an atomic bigger than 2 pointers, which is going to be lock free on no hardware of which I am aware. They would have been better served by an explicit mutex. (And we're talking about ABI broken world here, where `sizeof(mutex)` == `sizeof(void*)` at most)

I have some sympathy for `atomic<16 bytes>` on amd64 and I think we might be able to drop support for old Opterons from 2005 by the time we do an ABI breaking release, but no such sympathy for `atomic<64 bytes>`.

Finally, non-lock-free `atomic_ref` will be a workaround, since that's going to need the lock table inside the standard library and as such won't be able to cross library boundaries like `atomic` can today; it'll be just like `vector`. That's OK: `atomic_ref` doesn't have the special role of being the lowest level hardware access mechanism.

>I would suspect that this is why their libatomic is a completely separate shared library, as it really does need to be a single copy per process.

Then they don't, in fact, support static linking. Although the POSIX process-wide symbol table makes making things a singleton possible since they deduplicate symbols in the operating system loader.

**Comment by ned14** [comment]
> That would break deploying the STL in environments where user32 is not present, such as Nano Server or XBox.

I'd assume the lack of user32 is detectable by preprocessor macro?

> And it's to optimize a case where arguably the caller did something that asked for bad perf; create an atomic bigger than 2 pointers, which is going to be lock free on no hardware of which I am aware. They would have been better served by an explicit mutex. (And we're talking about ABI broken world here, where sizeof(mutex) == sizeof(void*) at most)

Well sure there is a moral argument here, but to be honest, that ship sailed with C11 (not C++). If you strongly believe in that moral argument, then you should make `std::atomic` refuse to compile bad perf code, or at least warn loudly. What caused me to report this issue was tracking down a nasty perf bug in work code, where the excessive padding was blowing out L2 cache footprint on Windows only. We were seeing 80% performance loss here :(

I would counter argument against your moral argument that very few people know that atomics work with any TC type, and those who deploy such a thing understand intimately the tradeoffs implied here. The guys who wrote our work code assumed that all platforms used a process-wide shared hash table, and the code performs very well under that assumption. It was therefore an unpleasant surprise when the Windows build suffered such a heavy performance loss.

Re `atomic<16 bytes>`, GCC still isn't getting that right at compile time, even with sufficient `-march`. At runtime libatomic detects new enough CPUs and does the right thing. clang does do the right thing with sufficient `-march`. However, to be honest, on Windows you have `InterlockedCompareExchange128()`, so things are nothing like as urgent on MSVC as on POSIX. I'm actually very relaxed, therefore, about you guys supporting `atomic<16 bytes>`.

Niall

**Comment by BillyONeal** [comment]
>I'd assume the lack of user32 is detectable by preprocessor macro?

Nope.

>to be honest, that ship sailed with C11 (not C++)

My understanding is that the design we have is out of a desire to have any atomics at all, as there are CPUs that effectively have nothing. Getting a locking atomic in place of a non-locking atomic that is slow but preserves correctness is the goal, so that you can declare `atomic<short>` and have that code work on strange hardware. `atomic<more than 16 bytes>` is supported on nothing, so it really isn't dovetailing into that design goal, it's an accident.

>I would counter argument against your moral argument that very few people know that atomics work with any TC type, and those who deploy such a thing understand intimately the tradeoffs implied here.

I guess we have to agree to disagree.

>What caused me to report this issue was tracking down a nasty perf bug in work code, where the excessive padding was blowing out L2 cache footprint on Windows only. We were seeing 80% performance loss here :(

Then for you we will have `atomic_ref` long before we will have an ABI breaking release.

>on Windows you have InterlockedCompareExchange128(), so things are nothing like as urgent on MSVC as on POSIX. I'm actually very relaxed, therefore, about you guys supporting atomic<16 bytes>

That instruction still needs the CPU to have cmpxchg16b, and CPUs supported by still-in-support versions of Windows do not have that instruction. If we had to ship an ABI breaking release today we wouldn't be able to do that yet, so `atomic<16 bytes>` would be 32 bytes.

**Comment by AlexGuteniev** [comment]
> If we had to ship an ABI breaking release today we wouldn't be able to do that yet, so `atomic<16 bytes>` would be 32 bytes.

If this happens, I expect you to detect such CPU at runtime, and if supported, use cmpxchg16b. Does not help with original request about size (and I tend to take your side on that), but helps with efficiency otherwise.

**Comment by AlexGuteniev** [comment]
(Honestly, an atomic built only on CAS is not nearly as good as full set of operations atomic. When I discovered that 16b atomic is not lock free, I assumed I could try boost atomic. They indeed have cmpxchg16b based atomic, but it didn't help much with performance, ultimately I resorted to not using 16 bytes atomic at all)

**Comment by AlexGuteniev** [comment]
> My understanding is that the design we have is out of a desire to have any atomics at all, as there are CPUs that effectively have nothing. Getting a locking atomic in place of a non-locking atomic that is slow but preserves correctness is the goal, so that you can declare `atomic<short>` and have that code work on strange hardware. `atomic<more than 16 bytes>` is supported on nothing, so it really isn't dovetailing into that design goal, it's an accident.

I actually do see the point of having `atomic<more than 16 bytes>`. 
And this point advocates having spin mutex embedded into atomic.

The point is for that spin mutex _Hardware Lock Elision_ can be used. So:
- `std::atomic<T>` would be better than `T` under a `std::mutex`, since general-purpose `std::mutex` will not have HLE.
- HLE succeeds when there's no contention, so it is very helpful to keep contention at minimum.

I've filled #679

**Comment by AlexGuteniev** [comment]
Another point to consider against this proposal is putting atomics to inter-process shared memory.
Standard asks for this to work for lock-free atomics:
https://eel.is/c++draft/atomics.lockfree#5
> [ Note: Operations that are lock-free should also be address-free. That is, atomic operations on the same memory location via two different addresses will communicate atomically. The implementation should not depend on any per-process state. This restriction enables communication by memory that is mapped into a process more than once and by memory that is shared between two processes. — end note ]
Though notes in square brackets are not formal, it is useful to follow it, and strengthen it to any atomics.

**Comment by ned14** [comment]
Well I tried my best. Thanks for the detailed feedback.
