### ISSUE TITLE
<memory_resource>: std::pmr::polymorphic_allocator<T>::destroy missing

### ISSUE THREAD

**Issue by jmlundberg** [microsoft/STL#753]
https://en.cppreference.com/w/cpp/memory/polymorphic_allocator/destroy
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/n4713.pdf §23.12.3.2 #14
Seems to be missing.
https://github.com/microsoft/STL/blob/master/stl/inc/xpolymorphic_allocator.h#L190
https://godbolt.org/z/iFfpPT

I had expected something like:

        template<class _Ty>
        void destroy(_Ty* _Ptr) {
            // destroys _Ptr as if by _Ptr->~_Ty().
            _Ptr->~_Ty();
        }

If this is indeed so, I can provide a PR.

Also tracked by DevCom-394908 and Microsoft-internal VSO-737704 / [AB#737704](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/737704).

**Comment by StephanTLavavej** [comment]
This was reported as DevCom-394908 (Microsoft-internal VSO-737704).

When @CaseyCarter implemented `polymorphic_allocator`, he noticed that its `destroy` didn't do anything special, so he filed LWG-3036 and speculatively implemented its proposed resolution, which is entirely reasonable and fairly common when we notice simple deficiencies in Standardese with obvious fixes. While we intentionally shipped `polymorphic_allocator` this way, this issue has unexpectedly remained open for 2.5 years, although the LWG has discussed it a couple of times.

Since you and other customers have noticed the absence of `polymorphic_allocator::destroy`, I believe that we should implement it in order to follow the Standard; if and when LWG-3036 is resolved, we can remove it again.

Please go ahead and submit a PR!

**Comment by StephanTLavavej** [comment]
Note that we do have a metaprogramming optimization that detects the Standard `std::allocator` (when it hasn't been user-specialized) and skips calling its `destroy` (which does nothing fancy). If we add `destroy` to `polymorphic_allocator`, we should extend that metaprogramming to avoid unnecessary debug codegen.
