### ISSUE TITLE
Provide AVX-512 implementations of vector algorithms

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#814]
Currently, `stl/src/vector_algorithms.cpp` provides optimized implementations for SSE2, SSE4.2, and AVX2; for example:

https://github.com/microsoft/STL/blob/11150ca6679507461ae9f64e90c678c498cfe908/stl/src/vector_algorithms.cpp#L39

Presumably, AVX-512 would further increase performance. 
`C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.26.28801\include\isa_availability.h` defines `__ISA_AVAILABLE_AVX512` which can be used to detect AVX-512 support.

Inspired by #813.

**Comment by StephanTLavavej** [comment]
Closing, as in #2104 we were unable to find positive performance effects. We're still open to using AVX-512 if benchmarks can be found indicating significant performance improvements.

**Comment by AlexGuteniev** [comment]
<details>
<summary>It is time!</summary>
<img width="1000" height="812" alt="Image" src="https://github.com/user-attachments/assets/dd1ea1e3-7fa6-4f27-810a-391670e183c7" />
</details>

It is time to reconsider.

#2104 may still be unsuccessful. Back then we only had swizzling algorithms that are very likely to be memory operations bound, and so double vector width would not help.

Now we have some other vector algorithms that would clearly benefit from AVX-512:
 * **replace**
   - AVX-512 can add 8-bit and 16-bit flavor. This will avoid oddness of vectorizing only for some integer sizes and make the vectorization coverage on par with possible future Arm64 SVE implementation.
   - AVX-512 can dramatically improve AMD performance. See #5068. The CPU mentioned by @muellerj2 is Zen 4, so it has AVX-512 that doesn't have masked store perf problem, but AVX2 masked stores are problematic, and resulted in almost no vectorization benefit.
   - This will make these algorithms on par with ARM64 SVE implementation.
      * We may simplify fallback testing then
      * And simplify away header macros complexity
 * **remove**, **unique**, **remove_copy**, **unique_copy**
   - `vpcompress` variants will allow not using additional memory for lookup tables, reducing memory operations number
   - Not having a lookup table will lift the elements number from 8 to full vector
   - `_copy` variant will not need to use intermediate buffer
   - This all again will make these algorithms on par with possible future ARM64 SVE implementation.
 * **find_meow_of**
   - The AVX2 bitmap approach probably can be scaled up more than twice, because there are 16-bit shuffles and 16-bit shifts. Can use 16-bt elements in a wider vector giving 4x speedup
   - This speedup is likely to be actually observed, as due to some number of operations, and no stores, this is not likely to end up like   #2104
 * **minmax_element**
   - The unsigned comparison will enable avoiding "sign correction"
   - See also #6176

This may be not exhaustive list; other algorithms may benefit too. Basically, `reverse`, `reverse_copy` and `swap_ranges` that existed during the previous attempt are the least likely to benefit from AVX-512.
