### ISSUE TITLE
constinit support / macro fallback

### ISSUE THREAD

**Issue by bernd5** [microsoft/STL#826]
I'd like to declare some fields with `constinit `(which already works with clang and gcc).
Currently MSVC has this feature not ready. As a fallback I'd like to define a macro constinit this way:

```C++
#if !defined(__cpp_constinit) && !defined(constinit)
#define constinit
#endif
```

Unfortunately this does not work because of [xkeycheck](https://github.com/microsoft/STL/blob/master/stl/inc/xkeycheck.h#L127-L131)

It has the following code:
```C++
#if defined(constinit) && _HAS_CXX20
#define constinit EMIT WARNING C4005
#error The C++ Standard Library forbids macroizing the keyword "constinit". \
Enable warning C4005 to find the forbidden define.
#endif // constinit
```

Could you change it to:
```C++
#if defined(constinit) && _HAS_CXX20 && defined(__cpp_constinit)
#define constinit EMIT WARNING C4005
#error The C++ Standard Library forbids macroizing the keyword "constinit". \
Enable warning C4005 to find the forbidden define.
#endif // constinit
```

**Comment by MikeGitb** [comment]
I think the more common approach is to use a `PROJECT_NAME_CONSTINIT` macro that is either defined to constinit if available or nothing otherwise.

**Comment by bernd5** [comment]
I want to avoid macros as much as possible. Macros are usually bad, look ugly and should be used only if really necessary. So I want to use the real C++ keywords.

I have seen it works with `_ALLOW_KEYWORD_MACROS` Macro. But in my option these warnings/errors are fine and such keyword-macros should be only allowed if these keywords are not handled by the compiler to allow compilation with older compilers.

**Comment by MikeGitb** [comment]
> Macros are usually bad, look ugly and should be used only if really necessary.

Which is exactly why I want them to stick out in my code. Personaly opinion: In a world where macros are unscoped, macronizing any keyword is pure evil. There is just too much of a chance that they ruin someone's day somewhere at sometime. 
But in any case: I'm not affiliated with this project, so my personal opinion isn't really relevant.

**Comment by StephanTLavavej** [comment]
I consider this to be By Design. The STL wants to defend itself from keyword macros, because we're early adopters of new features. If we changed `<xkeycheck.h>` to permit macroizing keywords in the absence of compiler support, users could begin taking dependencies on their favorite `#define future_tech HorribleUserStuff` macros. Then, when compiler support appears and the STL wants to use `future_tech`, it would have to reject user macros then - causing users to complain that we broke their "perfectly working code" that had shipped in production for however many megaseconds.

It is possible that `<xkeycheck.h>` will go away in the future, if and when the MSVC compiler itself gains the ability to forbid keyword macros - at which point the compiler team will need to decide how early to "reserve" keywords.

**Comment by AlexGuteniev** [comment]
Regarding macros, my observation that it has been previously handled with macros like `_NODISCARD` and `_CONSTEXPR_IF`.  Also the macro will be needed until `/std:c++14` and `/std:c++17` modes are dropped, which is definitely not something I expect to happen soon.

So possibly it could be `_CONSTINIT` macro.

**Comment by MikeGitb** [comment]
@AlexGuteniev: I think @bernd5 was talking about macros he defines in his own code and that STL headers that get included after this definition complain about due to the check in `<xkeycheck.h>` . Not about a macro he would like to introduce into the STL itself via a PR.

**Comment by StephanTLavavej** [comment]
Note that the STL’s `_UGLY` macros for features aren’t intended for users; we’ve removed them in the past (notably `_NOEXCEPT`) and will continue to remove them in the future. Please define your own `MEOW_FEATURE` user macros.

**Comment by bernd5** [comment]
I just want that my code which uses C++20 features compiles with MSVC in C++20 mode.
It doesn't because it does not know what "constinit" means.
I want to say, okay then ignore it.

**Comment by bernd5** [comment]
The best would be if I had to define no macro at all.
Perhaps it could be a temporary fix in the STL. Just to allow constinit declarations without really supporting them.

The good thing is, that a compiler which really supports `constinit` has to define the feature-macro: `__cpp_constinit` which can be used to create a temporary workaround.

**Comment by miscco** [comment]
But this is not a fix. A keyword that is not supported is not supported.

What I am reading is that you do not like `MEWO_CONSTINIT` and would prefer that you could use `constinit` yourself and move all the cost to the compiler / library.

That doesnt make any sense because the compiler / library has an insurmountably larger user group than your project and even worse this solution would actively break user code in the future.

**Comment by AdamBucior** [comment]
I don't think this issue is worth fixing as you can just define `_ALLOW_KEYWORD_MACROS`. When MSVC implements `constinit` you can just remove this definition together with `#define constinit`. I also don't think that STL should define `constinit` as it would only confuse people, but I'm not opposed to defining keywords in private projects (I currently `#define consteval constexpr` as it seems far more reasonable than flooding code with `// TODO: replace constexpr with consteval`).

**Comment by MikeGitb** [comment]
> I don't think this issue is worth fixing as you can just define _ALLOW_KEYWORD_MACROS. 

Agreed

> I currently #define consteval constexpr as it seems far more reasonable than flooding code with // TODO: replace constexpr with consteval).

This goes a bit off topic, but Is there any reson why you'd ever change something marked constexpr to consteval?

**Comment by AdamBucior** [comment]
> This goes a bit off topic, but Is there any reson why you'd ever change something marked constexpr to consteval?

Yes, ex. if you want to force compiler to execute some function in compile-time. If there was no reason to do that `consteval` would not exist.

**Comment by MikeGitb** [comment]
Sorry, mixed up consteval with constinit

**Comment by CaseyCarter** [comment]
> The good thing is, that a compiler which really supports `constinit` has to define the feature-macro: `__cpp_constinit` which can be used to create a temporary workaround.

Your argument assumes the converse to be true: that `constinint` is not a keyword in a compiler which doesn't define `__cpp_constinit`. This premise doesn't necessarily hold. Consider the curiously complex case of `consteval`: https://godbolt.org/z/DYncCS. Defining a feature-test macro indicates that a feature is complete and supported, not defining a feature-test macro can indicate either absence of a feature or partial completion. The latter is much more common with library feature-test macros than compiler feature-test macros - we've been filling in bits of `__cpp_lib_ranges` for months - but keywords should nevertheless be considered off limits in the corresponding language mode.

**Comment by bernd5** [comment]
Fortunately new keywords are introduced rarely. Some new keywords like co_yield can't be "simulated" easily. But some of them don't change "the whole logic". With `consteval` you can say clearly what is your intent - but while it is not available it should work with `constexpr`, too (it just can't be executed during runtime).

All this is only required while we work with partial implementations of the next c++ standard we want to use now.  If the implementation is done, such a "hack" should be removed. 

In the past there was something similar with `nullptr`.
