### ISSUE TITLE
<mutex>: Question about CLR support 

### ISSUE THREAD

**Issue by AlexGuteniev** [microsoft/STL#838]
I'm seeing that `shared_mutex` is supported with `_M_CEE`, whereas `mutex` is not.
And both are banned on include level under `_M_CEE_PURE`.

What is the situation with C++ support for `_M_CEE`?

Are `_M_CEE` and `_M_CEE_PURE` the only .Net modes, so that other special modes like C++/CX or OneCore are usual compilation, with full C++ support?

**Comment by AlexGuteniev** [comment]
I'm also assuming regarding compatibility of mix that:
 
 - `_M_CEE` without `_M_CEE_PURE` has also platform, such as `_M_X64` defined, and must be ABI-compatible with native compilation for that platform
 - `_M_CEE_PURE` does not necessarily assume a platform, it is .Net IL code, and it does not mix with native compilation

**Comment by StephanTLavavej** [comment]
We can get definitive answers to these questions - is this blocking any feature work?

**Comment by AlexGuteniev** [comment]
It only blocking some speculation on how mutexes should be done for vNext

**Comment by AlexGuteniev** [comment]
Actually now it does block #52

`<atomic>` is not supported in `_M_CEE_PURE`
Supporting `<latch>`, `<barrier>`, `<semaphore>` without `<atomic>` is interesting. 
If there is such need, I need to clarify some more details.

**Comment by CaseyCarter** [comment]
> Actually now it does block #52
> 
> `<atomic>` is not supported in `_M_CEE_PURE`
> Supporting `<latch>`, `<barrier>`, `<semaphore>` without `<atomic>` is interesting.
> If there is such need, I need to clarify some more details.

/clr:pure and C++20 are mutually exclusive; no C++20 features need to support `_M_CEE_PURE`.

**Comment by AlexGuteniev** [comment]
Thanks, for now would be enough to know that

**Comment by AlexGuteniev** [comment]
In a related question, what is the status of C++/CX ?

**Comment by StephanTLavavej** [comment]
C++/CX continues to be supported since customers use it, but "C++/WinRT is Microsoft's recommended replacement for the C++/CX language projection" (see [this intro](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/intro-to-using-cpp-with-winrt)). The STL needs to work correctly with the `/ZW` compiler option. Fortunately, this generally happens automatically, and we've needed only a few workarounds that specifically detect `/ZW` via [`__cplusplus_winrt`](https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=msvc-170).

**Comment by sylveon** [comment]
Also to note that C++/CX and C++20 are mutually exclusive, so new C++20 features need not to support CX
