### ISSUE TITLE
<cmath>: pow(float, int) doesn't return double

### ISSUE THREAD

**Issue by Amaroker** [microsoft/STL#890]
This bug was reported a long time ago at Developer Community, but I couldn't find an open issue here. Has it been forgotten?

```
#include <cmath>
#include <iomanip>

int main()
{
    // This should be OK since C++11
    static_assert( std::is_same<decltype(std::pow(10.f, 2)), double>::value );
}
```

See also DevCom-183102 and Microsoft-internal VSO-553723.

**Comment by StephanTLavavej** [comment]
@Berrysoft's fix will ship in VS 2019 16.8 Preview 1. Thanks again for reporting this!

**Comment by Amaroker** [comment]
@StephanTLavavej 

Great! Do you want help to port more bugs from Developer Community to GitHub, even though they have low priority? You say you already have a list, can you share it? Otherwise I can't add references to the corresponding Microsoft-internal numbers.

**Comment by StephanTLavavej** [comment]
@Amaroker That would be helpful, yes. Porting has been surprisingly time-consuming (and therefore de-prioritized since we really need to make progress implementing C++20 features and reviewing PRs), since we've been trying to draft clear writeups and reduced test cases, so contributors can more easily understand the nature of each bug and how to fix them.

I should be able to gather a cross-referenced list of Developer Community bugs and their internal counterparts on Azure DevOps (formerly Visual Studio Online, hence the VSO abbreviation we use in citations). (The full list of VSO bugs is trivial - it's the DevCom cross-references that are a bit harder to find.) I ran out of time this week, but I should have some time next week - I'll file a `documentation` issue and ping you there. Thanks! :smile_cat:
