### ISSUE TITLE
<iomanip>: get_time should parse format without delimiters

### ISSUE THREAD

**Issue by Amaroker** [microsoft/STL#944]
**Command-line test case**
```
#include <iostream>
#include <sstream>
#include <iomanip>
#include <assert.h>

int main()
{
  {
    // Parsing with delimiters (such as spaces) works fine.
    std::tm t = {};
    std::istringstream ss("2020 06 20");
    ss >> std::get_time(&t, "%Y %m %d");
    assert( !ss.fail() );
  }

  {
    // Parsing without delimiters fails, but should work too.
    std::tm t = {};
    std::istringstream ss("20200620");
    ss >> std::get_time(&t, "%Y%m%d");
    if( ss.fail() )
        std::cout << "test failure\n";
  }
}
```

**STL version**
    Microsoft Visual Studio Professional 2019
    Version 16.6.2

**Additional context**
The standard draft WG21-N4861 says that the conversion specification is valid for the ISO/IEC 9945 function strptime.

Looking at strptime, it says "The application shall ensure that there is white-space or other non-alphanumeric characters between any two conversion specifications unless all of the adjacent conversion specifications convert a known, fixed number of characters."

The number of characters for each conversion specifier is listed.
https://pubs.opengroup.org/onlinepubs/9699919799/functions/strptime.html

See also: DevCom-9505, DevCom-140618, DevCom-246365 and Microsoft-internal VSO-370548 / [AB#370548](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/370548).

**Comment by StephanTLavavej** [comment]
Thanks, I've linked the Microsoft-internal bug to this issue! I also updated your standard draft citation (much appreciated!) to use our repo's custom autolinks; GitHub doesn't allow `N` as an autolink prefix because it's too short, so `WG21-N` activates the magic. (Also `WG21-P` for P-numbered papers, but you have to omit any revision like `R2`.)

**Comment by Amaroker** [comment]
It seems that you forgot to close the internal bug, because the status of the DevCom issues haven't changed.

**Comment by StephanTLavavej** [comment]
@Amaroker Thanks for pointing that out - I actually did resolve and close the internal bug VSO-370548, but for some reason I don't understand, that didn't propagate to the linked internal "FeedbackTickets" that are themselves internal mirrors of the DevCom bugs. Perhaps it's because we had one VSO bug linked to multiple FeedbackTickets.

I've tried manually setting those three FeedbackTickets to "Fixed Pending Release" which seems to have caused the Feedback Bot to post replies to two of them, but not to the third, again for unknown reasons, and I haven't seen the DevCom bug statuses change yet. :crying_cat_face:

**Comment by randydu** [comment]
The VS 2019 Preview 3 (Visual Studio 2019 Developer Command Prompt v16.9.0-pre.3.0) is installed but the following code cannot parse iso-string properly:

```c
    std::tm tm{0};
    std::istringstream ss(str);
    ss >> std::get_time(&tm, "%Y%m%dT%H%M%S");
    if (ss.fail())
        throw std::invalid_argument("Invalid argument: " + str);

   //str = "19700101T000001"
```

Expected:

```c
  CHECK(tm.tm_sec == 1); //should be 1 second
  CHECK(tm.tm_min == 0);
```

Actual:

```c
  CHECK(tm.tm_sec == 0);
  CHECK(tm.tm_min == 1); // 1 min ?
```

The same test works fine for gcc on linux and clang on mac.
