### ISSUE TITLE
<filesystem>: weakly_canonical behavior is different if input path exists or not

### ISSUE THREAD

**Issue by draycs** [microsoft/STL#947]
**Describe the bug**
`weakly_canonical`'s return value is dependent on whether the input path exists or not.

If the input path exists, a trailing path-separator is not present in the return value.
If the input path does not exist, a trailing path-separator is still present in the return value.

**Command-line test case**
```
C:\Temp>type repro.cpp
#include <iostream>
#include <filesystem>

namespace std {namespace fs = filesystem;};

int main() {
    std::filesystem::create_directories("./foo/does_exist/");

    std::cout << R"(std::fs::weakly_canonical("./foo/does_exist/"): )" << std::fs::weakly_canonical("./foo/does_exist/") << std::endl;
    std::cout << R"(std::fs::weakly_canonical("./foo/not_exist/"): )" << std::fs::weakly_canonical("./foo/not_exist/") << std::endl;

    std::cout << R"(std::fs::weakly_canonical("./foo/does_exist/").remove_filename(): )" << std::fs::weakly_canonical("./foo/does_exist/").remove_filename() << std::endl;
    std::cout << R"(std::fs::weakly_canonical("./foo/not_exist/").remove_filename(): )" << std::fs::weakly_canonical("./foo/not_exist/").remove_filename() << std::endl;
}

C:\Temp>cl /EHsc /W4 /WX /std:c++17 .\repro.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.25.28612 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

repro.cpp
Microsoft (R) Incremental Linker Version 14.25.28612.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:repro.exe
repro.obj

C:\Temp>repro.exe
std::fs::weakly_canonical("./foo/does_exist/"): "C:\\Temp\\foo\\does_exist"
std::fs::weakly_canonical("./foo/not_exist/"): "C:\\Temp\\foo\\not_exist\\"
std::fs::weakly_canonical("./foo/does_exist/").remove_filename(): "C:\\Temp\\foo\\"
std::fs::weakly_canonical("./foo/not_exist/").remove_filename(): "C:\\Temp\\foo\\not_exist\\"

C:\Temp>dir .\foo
 Volume in drive C is Windows
 Volume Serial Number is EAC2-DA69

 Directory of C:\Temp\foo

06/30/2020  03:02 PM    <DIR>          .
06/30/2020  03:02 PM    <DIR>          ..
06/30/2020  03:02 PM    <DIR>          does_exist
               0 File(s)              0 bytes
               3 Dir(s)  19,470,991,360 bytes free
```

**Expected behavior**
Trailing path-separator behavior is consistent whether the input path exists or not. Either of the following two sample outputs would be acceptable:
```
std::fs::weakly_canonical("./foo/does_exist/"): "C:\\Temp\\foo\\does_exist\\"
std::fs::weakly_canonical("./foo/not_exist/"): "C:\\Temp\\foo\\not_exist\\"
std::fs::weakly_canonical("./foo/does_exist/").remove_filename(): "C:\\Temp\\foo\\does_exist\\"
std::fs::weakly_canonical("./foo/not_exist/").remove_filename(): "C:\\Temp\\foo\\not_exist\\"
```

```
std::fs::weakly_canonical("./foo/does_exist/"): "C:\\Temp\\foo\\does_exist"
std::fs::weakly_canonical("./foo/not_exist/"): "C:\\Temp\\foo\\not_exist"
std::fs::weakly_canonical("./foo/does_exist/").remove_filename(): "C:\\Temp\\foo\\"
std::fs::weakly_canonical("./foo/not_exist/").remove_filename(): "C:\\Temp\\foo\\"
```

**STL version**
```
Microsoft Visual Studio Enterprise 2019
Version 16.5.2
```

**Additional context**
The lines using `remove_filename` are not directly relevant to this bug. They are included to demonstrate a possible impact of the bug, and how it can cause surprising behavior for the caller.

This behavior is consistent in Clang and GCC too: https://godbolt.org/z/YepEWZ

**Comment by StephanTLavavej** [comment]
Thanks for the report!

As an aside, the Standard forbids this:
```cpp
namespace std {namespace fs = filesystem;};
```
This adds a declaration to `namespace std`, which isn't allowed by WG21-N4861 [[namespace.std]/1](https://eel.is/c++draft/namespace.std#1). You can define a namespace alias at global scope, though:
```cpp
namespace fs = std::filesystem;
```

The fact that MSVC, Clang/libc++, and GCC/libstdc++'s implementations behave identically is a strong indication that this is by design, and not a bug. (Not 100% for sure, though! Sometimes we're all wrong in the exact same way.)

Stepping through our implementation:

https://github.com/microsoft/STL/blob/5ef22f2a884706442257cea3dd9d5a6186f15c07/stl/inc/filesystem#L4024-L4031

`_Input` is `L"./foo/does_exist/"` and `_Canonical` sets `_Temp` to `L"C:\\Temp\\foo\\does_exist"`. This is then returned, hence the behavior of lacking a trailing backslash. (We'll look into `canonical`'s behavior below.)

For the nonexistent path, `_Canonical` fails, so we call `lexically_normal()` to get `_Normalized` being `L"foo\\not_exist\\"`. `_Normalized_relative` gets the same value:

https://github.com/microsoft/STL/blob/5ef22f2a884706442257cea3dd9d5a6186f15c07/stl/inc/filesystem#L4043-L4047

Then as we loop over its elements to build up the return value:

https://github.com/microsoft/STL/blob/5ef22f2a884706442257cea3dd9d5a6186f15c07/stl/inc/filesystem#L4051-L4052

`_Elem` is `L"foo"`, `L"not_exist"`, and finally `L""`. This empty element (because `_Normalized_relative` ended with a backslash) causes `_Result /= _Elem;` to generate a backslash at the end.

Now let's look at what the Standardese says. [[fs.op.weakly.canonical]/2](https://eel.is/c++draft/fs.op.weakly.canonical#2):

> *Effects:* Using `status(p)` or `status(p, ec)`, respectively, to determine existence, return a path composed by `operator/=` from the result of calling `canonical()` with a path argument composed of the leading elements of `p` that exist, if any, followed by the elements of `p` that do not exist, if any.

What are elements? [[fs.path.itr]/4.4](https://eel.is/c++draft/fs.path.itr#4.4) says that there's an empty element at the end "if a trailing non-root *directory-separator* is present".

So, I interpret this as saying that the observed behavior of `weakly_canonical` for the nonexistent path is correct - the `not_exist` element is followed by an empty element. Because `not_exist` doesn't exist, that's when `weakly_canonical` just starts appending elements with `/=`, so the empty element should be appended at the end, generating a trailing backslash.

What about the existent path? All of the elements exist (including the "empty element" after the `does_exist` element), so they should all be given to `canonical()`. (Nothing is appended for the "followed by the elements of `p` that do not exist, if any" phase.) [[fs.op.canonical]/1](https://eel.is/c++draft/fs.op.canonical#1) says:

> *Effects:* Converts `p` to an absolute path that has no symbolic link, dot, or dot-dot elements in its pathname in the generic format.

[[fs.op.canonical]/2](https://eel.is/c++draft/fs.op.canonical#2):

> *Returns:* A path that refers to the same file system object as `absolute(p)`.

That's definitely happening here (`L"./foo/does_exist/"` is converted to `L"C:\\Temp\\foo\\does_exist"`). It doesn't say anything about preserving trailing directory-separators, so I interpret this as saying that the behavior of `canonical()` is allowed by the Standard.

I believe this should be resolved as "by design, not a bug" but I'll ask the other maintainers for a double-check.

**Comment by BillyONeal** [comment]
I agree with Stephan's analysis. I also note that the trailing slash is significant on POSIX systems. Consider: `/a/b/exists_but_is_a_broken_link/`. For POSIX the trailing slash indicates that the symbolic link must be followed (even by, say, `lstat`). If the target exists, `canonical` will remove all the symbolic links and give you a fully resolved path, so no trailing slash is necessary, but if the target does not exist it must not remove the trailing slash because that would potentially refer to a different location should the symbolic link become unbroken.

/cc Davis Herring @opensdh

**Comment by draycs** [comment]
Thanks for the detailed explanation! I agree that this behavior is standard conformant, particularly because of the wording of [[fs.op.canonical]/2](https://eel.is/c++draft/fs.op.canonical#2) you mentioned:
> Returns: A path that refers to the same file system object as absolute(p).

It allows a different (without a trailing directory-separator) path to be returned as long as it refers to the same file system object.

------

I'm pretty new to Standardese, but I wonder if the behavior could be made less surprising by a change like the following in [[fs.op.weakly.canonical]/2](https://eel.is/c++draft/fs.op.weakly.canonical#2)
> Effects: Using status(p) or status(p, ec), respectively, to determine existence, return a path composed by operator/= from the result of calling canonical() with a path argument composed of the leading elements of p that exist, if any, followed by the ~~elements of p that do not exist, if any~~ __remaining elements of p, even if they do not exist__.
For the first form, canonical() is called without an error_­code argument.
For the second form, canonical() is called with ec as an error_­code argument, and path() is returned at the first error occurrence, if any.

This would mean that the empty element should be appended to the value returned by `canonical`, preserving the trailing directory-separator when the path exists.

------

Overall happy to have this closed as standard conformant though, thanks again for your time (and the namespace tip)!

**Comment by StephanTLavavej** [comment]
You're welcome! Proposing a behavioral change would have to be submitted as an LWG issue (whereas purely clarifying the wording can be submitted as an editorial issue at https://github.com/cplusplus/draft/issues ).
